### ISSUE TITLE
Unable to create new DB on iPad

### ISSUE THREAD

**Issue by mcuix** [SQLiteFlow/SQLiteFlow-Issues#1]
Installed on iPad but unable to create new DB

**Comment by SQLiteFlow** [comment]
Hey @mcuix, I just tested the create new DB feature with SQLiteFlow(iOS) version 1.3.1 on a iPad Air, the test steps are:
1. Tap + at SQLiteFlow's initial page.
2. Enter a database name.
3. Tap OK.
The a new database has been created without any issue.

So I may need more information to check this issue, and can I get these information?
iOS version:
iPad model:
SQLiteFlow version:

**Comment by SQLiteFlow** [comment]
Hello @mcuix, do you still meet this issue on the latest version of SQLiteFlow?

**Comment by SQLiteFlow** [comment]
Close for now. If this still an issue in the latest version, please send us a new issue, thank you.

**Comment by SQLiteFlow** [comment]
In SQLiteFlow(iOS) 1.3.5, we fix an issue that causes load database library failed when there's another app that declares it owns SQLite database file type, this fix may relative to this issue.
