### ISSUE TITLE
User Guide?

### ISSUE THREAD

**Issue by zenmom** [SQLiteFlow/SQLiteFlow-Issues#10]
I'm new to SQLite, and downloaded SQLiteFlow after seeing it recommended as a GUI for SQLite. I created a table and defined the fields, but I can't figure out how to enter my data. It looks like a typical table view, but all the headings are grayed out and there doesn't seem to be anywhere to enter data. Is there a User Guide for SQLiteFlow anywhere online? Or maybe a couple of video tutorials? Thanks.

**Comment by SQLiteFlow** [comment]
Hello @zenmom 
Thank you for using SQLiteFlow, and I assume you are on SQLiteFlow(macOS), to enter data to a table through GUI, I attached an image as a tutorial, please have a look to see if I answered your question.
![enter data](https://user-images.githubusercontent.com/38027540/50862593-fa9c7f00-13d6-11e9-8d30-50635b64069b.png)

For SQLiteFlow(iOS), the behavior is similar.

**Comment by zenmom** [comment]
Thank you.
