### ISSUE TITLE
[macOS] Export table to csv file : ask the separator character to be used

### ISSUE THREAD

**Issue by GT85** [SQLiteFlow/SQLiteFlow-Issues#100]
"," as today, or ";" or Tab or any other specified character.
Because the default separator in Excel is not the same in every culture.
Thanks,
Gilbert

**Comment by SQLiteFlow** [comment]
@GT85 
I’m not quite get the question, so you are asking what is the separator that SQLiteFlow uses for exporting CSV?
If so, it’s the comma(,) character, following the ietf guide. 🙂
https://tools.ietf.org/html/rfc4180

**Comment by GT85** [comment]
Hello. 
I know it is the comma, that’s the problem. When I open the csv file with Excel (in France), all data are in one column. For Excel, the separator is culture dependant. I know I can change this in Excel options, but I do not want to change everytime, depending on the origin of the csv to be imported. 
Therefore it would be very userfriendly to have the possibility to define the separator to be used at export time, at least between comma, semicolumn or TAB. 
Regards,
Gilbert

**Comment by SQLiteFlow** [comment]
@GT85 Oh, sorry for the misunderstanding. And sure, I can add it.

**Comment by SQLiteFlow** [comment]
Finished. 
Now both import and export CSV can use the `tab` character or the `;` as delimiter. 

Screenshots attached.
![export](https://user-images.githubusercontent.com/38027540/82185536-ef872680-991b-11ea-8343-7bc61960233f.png)
![import](https://user-images.githubusercontent.com/38027540/82185537-f01fbd00-991b-11ea-94d9-e8c2239f3b06.png)

**Comment by SQLiteFlow** [comment]
SQLiteFlow(macOS) 4.0.0 has been released.
