### ISSUE TITLE
[macOS] Add a preference for spaces instead of tabs

### ISSUE THREAD

**Issue by robertmiles3** [SQLiteFlow/SQLiteFlow-Issues#101]
Great app! Can we maybe add a preference to make the Tab key insert spaces in the editor instead of a tab character?

**Comment by SQLiteFlow** [comment]
@robertmiles3 Thank you. And sure, I can add a setting to allow users to choose if they would like to use the Tab key to inserts tab character or to inserts tab width spaces.

**Comment by SQLiteFlow** [comment]
Finished.
Add a setting 'Tab Key Behavior' to 'Preference - Text Editing' to allow users set the Tab key behavior to 'Inserts Tab Character' or 'Inserts Spaces'.

Screenshot attached.
![pic](https://user-images.githubusercontent.com/38027540/81934351-6ae98f00-9621-11ea-9d54-329394508693.png)

**Comment by robertmiles3** [comment]
Awesome! Thanks for the quick work on that! I'll keep a watch out for the release.

**Comment by SQLiteFlow** [comment]
SQLiteFlow(macOS) 4.0.0 has been released.

**Comment by robertmiles3** [comment]
Thanks for the release. Closing this.

**Comment by SQLiteFlow** [comment]
You are welcome!
