### ISSUE TITLE
Failed import of csv file to SQLiteFlow

### ISSUE THREAD

**Issue by Dionysu** [SQLiteFlow/SQLiteFlow-Issues#102]
I tried to import this file into a 6-field database and got the message:  "Med Travel has 6 columns but 2 value were supplied".  This csv file was made from a spreadsheet, which is the way I usually import data into a SQLiteFlow database.  What is wrong with this file?
[Medical Travel Calculation 2019x.csv.zip](https://github.com/SQLiteFlow/SQLiteFlow-Issues/files/4637285/Medical.Travel.Calculation.2019x.csv.zip)

**Comment by SQLiteFlow** [comment]
@Dionysu 
I can import the file that you offered successfully at my side.
What's your configuration when you do the importing? Mind offer me a screenshot?

**Comment by Dionysu** [comment]
Thanks for the reply to my request for help. I lost the file I attached.  Would you send me a copy?  As t configuration:  do you mean the table setup?

Thanks

dennis

**Comment by SQLiteFlow** [comment]
I mean what’s your importing steps? Mind offer me the screenshot of your importing window?
PS: The file you attached is still attached at your initial post.

**Comment by Dionysu** [comment]
Attached are the relevant screen shots.  One has the name of the file to be imported; the other has the error message.

**Comment by Dionysu** [comment]
Just to make sure you have the screen shots referred to in my
<img width="540" alt="Screen Shot 2020-05-18 at 12 54 50 PM" src="https://user-images.githubusercontent.com/48733891/82244861-84335980-9907-11ea-8e6a-8749f2a71257.png">
<img width="543" alt="Screen Shot 2020-05-18 at 12 54 19 PM" src="https://user-images.githubusercontent.com/48733891/82244866-872e4a00-9907-11ea-9880-398500689916.png">

 last note:

**Comment by SQLiteFlow** [comment]
The csv file you attached is a Tab separated file, I saw the screenshots you attached, the ‘Separator’ field you choose is the comma(,) character.
When you import a Tab separated csv file, you need to set the ‘Separator’ field to ‘tab’.

**Comment by Dionysu** [comment]
Thank you!  That is the difference between csv files saved from a Numbers spreadsheet and a LibreOffice spreadsheet,

dennis j tuchler

**Comment by SQLiteFlow** [comment]
You are welcome. Does these two issues created with the same reason?

https://github.com/SQLiteFlow/SQLiteFlow-Issues/issues/103

https://github.com/SQLiteFlow/SQLiteFlow-Issues/issues/104

**Comment by Dionysu** [comment]
Yes, the issues are related.  I am wondering whether anbd how to use of SQLiteFlow with wome other apps.

Thanks again for your help.

dennis tuchler
