### ISSUE TITLE
Viewing, altering fields in a table

### ISSUE THREAD

**Issue by Dionysu** [SQLiteFlow/SQLiteFlow-Issues#105]
I have versioon 3.8.1. and run it under Mac OS 10.15.4 (Catalina)

I want to know how I can open a table so that I may view and edit it.  The illistration on your web site does not help. Here is a screen shot of my  opening screen for a database:
<img width="1583" alt="Screen Shot 2020-05-18 at 12 11 36 PM" src="https://user-images.githubusercontent.com/48733891/82240968-ec327180-9900-11ea-8697-bcff2f26eb76.png">

**Comment by SQLiteFlow** [comment]
Does double click the table name help?

**Comment by Dionysu** [comment]
No, double clock does not do it.  BUT Control-click does (dit drops a menu which includes Sekect Rows, Drop Table and Alter Table.  You get out of the menu by Option-Click.
You might add this to your web site section on altering tables.

**Comment by SQLiteFlow** [comment]
Thank you for the suggestion, I may add it in future.
So does that get your issue solved?

**Comment by Dionysu** [comment]
The problem is resolved.  The instructions for access to the table are duly entered in my Manuals file. Thank you,

dennis j tuchler
