### ISSUE TITLE
[macOS] Add an option 'Allow select all file types' to Open Database panel to allow user opening database files with arbitrary extensions from the Open Database panel.

### ISSUE THREAD

**Issue by paul-go** [SQLiteFlow/SQLiteFlow-Issues#106]
**Version**
 - Platform: [e.g. macOS 10.13.6]
 - SQLiteFlow: [e.g. 3.8.1]

**Steps to Reproduce**
1. Use the open file dialog to navigate to a folder that contains SQLite database files with arbitrary extensions. Such files are disabled. 

**Expected behavior**
The open files dialog should allow these to be opened from the open file dialog. Dragging and dropping these files in from Finder works as expected.

**Comment by SQLiteFlow** [comment]
Sure. 

The reason that SQLiteFlow behave like that is it helps user find their SQLite databases with common file extensions(db, db3, sqlite, sqlite3) more quickly.

In next version, I will add an option 'Allow select all file types' to Open Database panel to allow user opening database files with arbitrary extensions from the Open Database panel.

Screenshots attached.

![pic1](https://user-images.githubusercontent.com/38027540/82746386-aaeb0780-9dc1-11ea-87fb-bac7110c4f30.png)
![pic2](https://user-images.githubusercontent.com/38027540/82746390-ae7e8e80-9dc1-11ea-9214-97cd69846923.png)

**Comment by SQLiteFlow** [comment]
SQLiteFlow(macOS) 4.0.1 has been released.

**Comment by paul-go** [comment]
Works on my Mojave machine. On my High Sierra machine (which is my main), it seems App Store won't download the update (it just sits there forever). Is there a way to get a .dmg outside of the App Store? Maybe this should be moved to a separate issue.

(Thanks for this by the way, will be buying a license, probably 2 actually)

**Comment by SQLiteFlow** [comment]
> On my High Sierra machine (which is my main), it seems App Store won't download the update

It’s probably a glitch of App Store in macOS 10.13 if the App can’t be downloaded as an update.
I remember there was a user experienced the same issue, seems like delete then re-download the App will work. The relate issue is https://github.com/SQLiteFlow/SQLiteFlow-Issues/issues/48.


> Is there a way to get a .dmg outside of the App Store?

SQLiteFlow currently only available on the App Store, so there’s no .dmg package available outside the App Store.


> will be buying a license, probably 2 actually

Thank you! 
If you use the same Apple ID account in the two Mac machines, I don’t think buying 2 licenses is necessary, if you bought it in one machine, it will available in another machine without duplicate purchases.
If you use two different Apple ID accounts, and using the paid account to login the unpaid account’s machine’s App Store to download the App can’t be an option, then maybe buying 2 licenses is the left option.
