### ISSUE TITLE
sqliteflow資料庫匯出亂碼

### ISSUE THREAD

**Issue by sugrass** [SQLiteFlow/SQLiteFlow-Issues#109]
你好，
我今天試著將iphone7 plus SQLiteFlow 裡的資料匯出CSV格式
，突然發現全部都變成亂碼了？有辦法解決這問題嗎？
<img width="440" alt="擷取" src="https://user-images.githubusercontent.com/58017086/83959673-675cc700-a8b2-11ea-8a68-b890427fe77f.PNG">

**Comment by SQLiteFlow** [comment]
@sugrass 
方便附加上一個可以重現這個問題的資料庫以及您已經匯出好的有問題的CSV檔案嗎?
我可以試著先重現一下這個問題。

**Comment by sugrass** [comment]
有兩個檔案 ，
ori是原始的檔案，最初只有編輯一筆資料後，即匯入手機編輯。
out是匯出的，在手機裡編輯後的資料，匯出後就變成亂碼

[新增資料夾.zip](https://github.com/SQLiteFlow/SQLiteFlow-Issues/files/4741370/default.zip)

**Comment by SQLiteFlow** [comment]
@sugrass 兩個檔案我都看到了。
在我這裡，用SQLiteFlow開啟兩個檔案，都沒有顯示亂碼呀？（附加了兩個截圖）
請問需要怎樣才可以重現匯出亂碼呢？

OriCSV:
![OriCSV](https://user-images.githubusercontent.com/38027540/83960155-09cb7900-a8b8-11ea-826a-772b6d3b41f1.png)

OutCSV:
![OutCSV](https://user-images.githubusercontent.com/38027540/83960157-0b953c80-a8b8-11ea-8693-a41d56b89ab2.png)

**Comment by sugrass** [comment]
呃…我不知道怎會跟你的不一樣…
會是簡、繁體語係的問題嗎？
不然我就得自已研究了…

SQLiteFlow <notifications@github.com>於 2020年6月7日 週日，12:13寫道：

**Comment by SQLiteFlow** [comment]
@sugrass 
需要再瞭解多一些資訊才可能能判斷是哪裡的問題，我看我能不能幫助到您。
1. 您用SQLiteFlow中檢視記錄的時候，顯示的文字時正常的還是亂碼？
2. 您提到的匯出後的CSV檔案亂碼，是用什麼軟體檢視的這個CSV檔案呢，我看您發的截圖不是在用SQLiteFlow檢視的，而是用了一個其它軟體，是什麼軟體呢，有沒有可能是這個軟體沒有將CSV檔案顯示正確？
3. 另外，用SQLiteFlow開啟這個CSV檔案是否也是顯示亂碼呢？

**Comment by sugrass** [comment]
1.我在SQLite手機檢視是時正常的。
2.手機匯出來的CSV我是用office的EXCEL來開啟的，這時就變成亂碼了。
3.最早之前我是將CSV檔匯入時是亂碼，也開了一個issue來處理，不過後來你們出了更新就解決了這問題，再匯入系統也都是正常的。但現在匯出就是亂碼了

SQLiteFlow <notifications@github.com>於 2020年6月7日 週日，12:25寫道：

**Comment by SQLiteFlow** [comment]
@sugrass 

> 2.手機匯出來的CSV我是用office的EXCEL來開啟的，這時就變成亂碼了。

您的意思是Train_OUT.csv這個檔案用EXCEL開啟是亂碼是吧？
那麼用SQLiteFlow開啟Train_OUT.csv顯示正常嗎？

**Comment by sugrass** [comment]
是的，你說的沒錯

SQLiteFlow <notifications@github.com>於 2020年6月7日 週日，12:34寫道：

**Comment by SQLiteFlow** [comment]
@sugrass 
我在我的iPhone上和Mac上都下載了微軟的Excel試了一下，的確像您描述的那樣，顯示為亂碼。
但是用其它軟體開啟，比如TextEdit，Sublime Text，還有Numbers，均能正常顯示。
所以現在看起來應該是Excel沒有正確地把這個檔案開啟。
附加了一個截圖：
![pic](https://user-images.githubusercontent.com/38027540/83960678-36828f00-a8be-11ea-925f-6777d1847adf.png)

**Comment by sugrass** [comment]
看來這就是問題點了，顯然不再是貴公司得問題。
感謝你的協助，
可以結案了
謝謝

從我的iPhone傳送

**Comment by SQLiteFlow** [comment]
@sugrass 
不客氣，應該的。
如果您還有什麼我們軟體使用上的問題，歡迎再來提問～
