### ISSUE TITLE
Window Size Not Remembered.

### ISSUE THREAD

**Issue by MattGrdinic** [SQLiteFlow/SQLiteFlow-Issues#11]
Loving the app, fantastic work!

One issue however: The app doesn't appear to remember the last set window size. Not a huge deal, but it can be a bit cumbersome to always have to resize the window upon start.

**Comment by SQLiteFlow** [comment]
@MattGrdinic Glad you like it! 
And the last set window size not be remembered seems like a bug, I will look into that.

**Comment by SQLiteFlow** [comment]
@MattGrdinic SQLiteFlow(macOS) 3.3.0 has been released. The issue of window size remembered should be fixed in this version.
