### ISSUE TITLE
[macOS] No loading spinner on first Tab Page

### ISSUE THREAD

**Issue by bitxianaiz** [SQLiteFlow/SQLiteFlow-Issues#118]
Steps:
1. Start SQLiteFlow
2. Open a database file
3. Double-click a LARGE table (it may take 20-40 seconds or more to open)
4. No loading spinner shows while the table is loading. It looks like the App is frozen

When multiple Tab Pages are open, the loading spinner shows OK but no loading spinner shows when there is only one page loading.

<img width="358" alt="SQLiteFlow" src="https://user-images.githubusercontent.com/64098128/85177968-451c5f00-b24b-11ea-8750-23d0e06af3ed.png">

**Comment by SQLiteFlow** [comment]
In next version, when a table is loading, I will let the loading spinner spinning at the position of the refresh button, and meanwhile the refresh button will be hidden.

When loading:
![whenloading](https://user-images.githubusercontent.com/38027540/85190634-b9f3a580-b2ec-11ea-875e-797d8bf04566.png)

When not loading:
![whennotloading](https://user-images.githubusercontent.com/38027540/85190667-050db880-b2ed-11ea-8fb3-3c4ebbeead65.png)

**Comment by SQLiteFlow** [comment]
SQLiteFlow(macOS 4.1.1) has been released.

**Comment by bitxianaiz** [comment]
Great! 

If you want to go the extra mile in a future release, you may want to keep the loading spinner spinning at the position of the refresh button, but remove the duplicate loading spinner from the Tabs to avoid duplicate user interface objects as per Mac GUI conventional guidelines. Thanks for another great update!

![Drop Tab duplicate spinners](https://user-images.githubusercontent.com/64098128/85954471-b93ebd00-b945-11ea-8774-c4c3099cc851.png)

**Comment by SQLiteFlow** [comment]
You are welcome!
And I will consider your suggestion, thank you.
