### ISSUE TITLE
macOS Touch Bar Support

### ISSUE THREAD

**Issue by nalexander50** [SQLiteFlow/SQLiteFlow-Issues#119]
I would love to see some simple controls added to the Touch Bar. Most specifically, I would love a Run and Run Selected Query button added to the Touch Bar. Other controls are welcomed, but those in particular would be nice.

**Comment by SQLiteFlow** [comment]
Sure.

**Comment by SQLiteFlow** [comment]
SQLiteFlow(macOS) 4.2.0 has been released.
It adds some basic Touch Bar support, including Run and Run Selected Query.

May bring more Touch Bar support in future version of SQLiteFlow.
And if you found what else I can do to help you to use Touch Bar more conveniently, please let me know.
