### ISSUE TITLE
Allow user to save new database to local file directory.

### ISSUE THREAD

**Issue by amandarawls** [SQLiteFlow/SQLiteFlow-Issues#120]
I would like to use your iPad application but I cannot choose the save location for a new database. I would like to be able to access the dB from a Jupyter notebook so it needs to be in a shared location.

**Comment by SQLiteFlow** [comment]
It probably can. 
So what do you mean the "local file directory"? A file directory that can be accessed through "Files" app?

**Comment by amandarawls** [comment]
Yes, that’s what I mean.

If it can already do that then it needs to be easily found. I spent 10 minutes trying to find any option to specify a directory

**Comment by SQLiteFlow** [comment]
Well, we call a file directory that can be accessed through the "Files" app an "External Folder".

SQLiteFlow(iOS) supports open External Folder.
To open an External Folder, go to Browse -> External Files -> Tap  '+' -> Open an External Folder.

And to create a new database in External Folder, go to the folder -> Tap  '+' -> New Database.

Maybe I'm the developer, I personally feel it's easy to found, but sounds like it's not easy enough all people, any suggestion that what changes can let you feel it's easier to found?

**Comment by amandarawls** [comment]
Thank you.

The workflow you described:
1. Declare storage location
2. Select create database in storage location view

However, most if not all? Apps I’ve used allow you to 
1. Select create database button
2. UI prompt to declare storage location

Also 
1. Select existing file (database)
2. Allow user to move database (current long-press options are duplicate/rename, trailing swipe action is delete).

This last two workflows was what I was looking for and couldn’t find.

Thank you for this app. This allows me to create a database for and examine the database changes I execute with Python in a Jupyter notebook.

**Comment by SQLiteFlow** [comment]
> However, most if not all? Apps I’ve used allow you to
> 
> 1. Select create database button
> 2. UI prompt to declare storage location

Okay, about that, I think this is the creating new file philosophy in Mac or PC.
If you look at apps like Numbers, Keynotes, Adobe Acrobat PDF, etc in iOS, they are all follow the philosophy that require opening a storage location first, then in that location creating new files.

<br/>

> 1. Select existing file (database)
> 2. Allow user to move database (current long-press options are duplicate/rename, trailing swipe action is delete).

Currently, you can use Drag & Drop to moving files.
And I think I will add the moving file workflow you mentioned in the list.

**Comment by SQLiteFlow** [comment]
Oh, I forget to mention that, currently Drag & Drop to moving files only works in Browse - SQLiteFlow folder.
In an External Folder, you can't do it yet in SQLiteFlow app, however, since it's an External Folder, you can always do it in "Files" app.

And in addition, in case you need it, if you want to copy a file in Browse - SQLiteFlow folder to an External Folder, you can Tap 'Select' -> Choose a file -> Tap the share icon in the left-bottom of screen -> Choose 'Save to Files'.
