### ISSUE TITLE
Missing '!=' (not equal) filter combo choice

### ISSUE THREAD

**Issue by rene-aguirre** [SQLiteFlow/SQLiteFlow-Issues#125]
**Version**
 - Platform: [e.g. macOS 10.15.x]
 - SQLiteFlow: [e.g. 4.3.0]

**Steps to Reproduce**
- Open a db
- Create a new filter
- Change criteria to 'not match a value', select from combo choices, example: [AND], [column],[not equal]

Not equal (`!=`) choice missing

Cherry on top: it would be nice to have also a does 'not contain' choice (`NOT LIKE 'pattern'`)

:-)

**Comment by SQLiteFlow** [comment]
Thank you for the suggestion!
I will add `!=` and `not contains` in next version.

**Comment by SQLiteFlow** [comment]
Finished.
Filter in Data Editor now supports `!=` and `not contains` operator.
This feature will available in next version.

Screenshot attached.
![screenshot](https://user-images.githubusercontent.com/38027540/86878060-c1071a00-c11a-11ea-8572-50bca1056e34.png)

**Comment by SQLiteFlow** [comment]
SQLiteFlow(macOS) 4.3.1 has been released.
