### ISSUE TITLE
Feature Suggestion/Request

### ISSUE THREAD

**Issue by bitxianaiz** [SQLiteFlow/SQLiteFlow-Issues#126]
Feature Suggestion/Request: Include the left sidebar Tables context menu and Views context menu on the App top menu bar, as recommended in the Mac Human Interface Guidelines (https://developer.apple.com/design/human-interface-guidelines/macos/menus/contextual-menus/).
![Mac Human Interface Guidelines](https://user-images.githubusercontent.com/64098128/87350905-8c360100-c526-11ea-81d1-d8f3c74ba1b6.png)

Table contextual menu
![Table](https://user-images.githubusercontent.com/64098128/87350988-ad96ed00-c526-11ea-949b-603f5b65ef03.png)

File > Database > Table
![File   Database   Table](https://user-images.githubusercontent.com/64098128/87351098-e6cf5d00-c526-11ea-8aac-eb6241f19b7a.png)

View contextual menu
![View](https://user-images.githubusercontent.com/64098128/87351194-13837480-c527-11ea-8149-680169e7600e.png)

File > Database > View
![File   Database   View](https://user-images.githubusercontent.com/64098128/87351211-1da57300-c527-11ea-87cf-d03706f98549.png)

--When no left-sidebar table or view is selected, the entire File > Database menu would be grayed out.
--When a left-sidebar Table is selected, the File > Database > Table menu would be enabled.
--When a left-sidebar View is selected, the File > Database > View menu would be enabled.

**Comment by SQLiteFlow** [comment]
Sounds good. I will look into that. 
Thank you.

**Comment by SQLiteFlow** [comment]
Finished.
Add "Database" menu item to the menu bar. And a screenshot attached.

![pic](https://user-images.githubusercontent.com/38027540/91122090-f916ec00-e6cb-11ea-96ee-935fe37004d1.png)

**Comment by SQLiteFlow** [comment]
SQLiteFlow(macOS) 4.5.0 has been released.
