### ISSUE TITLE
[iOS] Data Editor, supports arrow keys to move selection between cells.

### ISSUE THREAD

**Issue by jheddings** [SQLiteFlow/SQLiteFlow-Issues#131]
**Version**
 - Platform: iOS
 - SQLiteFlow: 4.3.4

**Steps to Reproduce**
In the data editor, use arrow keys to navigate between cells.
Note that nothing happens when arrow keys are pressed.

**Expected behavior**
Expected to move between cells, similar to a spreadsheet.

**Screen shots**

**Comment by SQLiteFlow** [comment]
Sure. I will implement it.

**Comment by SQLiteFlow** [comment]
Finished. This is a feature that requires iOS 13.4 or iPadOS 13.4.
- Supports arrow keys to move selection.
- Supports Shift + arrow keys to append selection.
- Supports Shift + Command + arrow keys to append selection to end of the of rows or columns.
- Supports Command + C to copy selected data.

**Comment by SQLiteFlow** [comment]
SQLiteFlow(iOS) 4.3.5 has been released.

**Comment by jheddings** [comment]
This works great!  Thanks for the quick turn around!!

-jh
