### ISSUE TITLE
已购买了手机版app，但在Mac中无法恢复购买，请帮忙解决下，谢谢

### ISSUE THREAD

**Issue by richardrich00007** [SQLiteFlow/SQLiteFlow-Issues#132]
**Version**
 - Platform: [e.g. macOS 10.14.5]
 - SQLiteFlow: [e.g. 3.6.0]

**Steps to Reproduce**

**Expected behavior**

**Screen shots**


**Comment by SQLiteFlow** [comment]
SQLiteFlow(iOS)和SQLiteFlow(macOS)是两个独立的应用，它们的购买是不通用的。
