### ISSUE TITLE
I have purchased the mobile app, but I can't resume the purchase in MAC. Please help me solve it. Thank you

### ISSUE THREAD

**Issue by richardrich00007** [SQLiteFlow/SQLiteFlow-Issues#133]
**Version**
 - Platform: [e.g. macOS 10.14.5]
 - SQLiteFlow: [e.g. 3.6.0]

**Steps to Reproduce**

**Expected behavior**

**Screen shots**

**Comment by SQLiteFlow** [comment]
SQLiteFlow(iOS) and SQLiteFlow(macOS) are two standalone apps which are currently selling separately one in iOS App Store and another in macOS App Store, and they are not sharing a same purchase.
