### ISSUE TITLE
Editor font size is way to small

### ISSUE THREAD

**Issue by drich-web** [SQLiteFlow/SQLiteFlow-Issues#137]
Editing cells is difficult with the tiny font.

**Comment by SQLiteFlow** [comment]
Which platform are you in? macOS or iOS?
When you mentioned "Editor", you mean Query Editor or Data Editor?
And could offer me a screenshot that point out which part that makes you feel too small?

**Comment by drich-web** [comment]
Thank you for your quick reply.  I'm using macOS High Sierra with a Dell Ultra Sharp 27" 2K monitor.

Please see the screenshot with the id, name and description columns.  I believe it is the Data Editor.

Cheers
![Screen Shot 2020-08-03 at 11 08 28 PM](https://user-images.githubusercontent.com/69180393/89248999-1251de80-d5df-11ea-91a2-482b60df6d2f.png)

**Comment by SQLiteFlow** [comment]
I attached a screenshot of some macOS apps, like Safari, Mail, Activity Monitor, and highlight some area of them, are the highlight parts of these apps also have a very small font to you?

![pic](https://user-images.githubusercontent.com/38027540/89250576-a5266380-d647-11ea-848b-6962deae92cb.png)

**Comment by drich-web** [comment]
Thanks for you help with this.  My font size looks the same for Mail, and my fonts seem 2-3 points larger than your screenshots for Safari and Activity Monitor.

**Comment by drich-web** [comment]
Just checked and my monitor resolution is 2560 x 1440.  The last time I used SQLiteFlow I had a 23" 1080 monitor.  Maybe this is part of the issue?

**Comment by SQLiteFlow** [comment]
The Data Editor's font size in SQLiteFlow should same as the Activity Monitor's font size, since they all use the default font size for macOS's table view.
And yes, it could be that you are not get used to the 2560 x 1440 resolution in a 27" monitor yet.
If so, you can use the System Preference to change the display resolution to the one that makes you feel more comfortable.

![pic](https://user-images.githubusercontent.com/38027540/89253550-875cfc80-d64f-11ea-98eb-3c826c028061.png)

**Comment by drich-web** [comment]
Thank you for your support.  SQLiteFlow is a great product and performs queries other products can't do.

**Comment by SQLiteFlow** [comment]
You are welcome.

**Comment by SQLiteFlow** [comment]
SQLiteFlow(macOS) version 4.7.0 now supports adjust font size in Preferences - Data Editor, so you can zoom out the font if you feel it's too small. Please see the screenshot. 
![pic](https://user-images.githubusercontent.com/38027540/98204668-720aad80-1f71-11eb-8e61-3ffac8883b9b.png)

**Comment by drich-web** [comment]
Good morning.  Looks great!  Thank you.

**Comment by SQLiteFlow** [comment]
You are welcome.
