### ISSUE TITLE
Dropping Table: Error dialog box > "no such table: ca_adjusted_gross_income"

### ISSUE THREAD

**Issue by bitxianaiz** [SQLiteFlow/SQLiteFlow-Issues#139]
**Version**
 - Platform: macOS 10.15.6 (19G2021)
 - SQLiteFlow: 4.3.1

**Steps to Reproduce**
1. Double-click a Table to open it.
2. Right-click the table and select "Drop Table".
![drop-1](https://user-images.githubusercontent.com/64098128/90697033-7d401e00-e24b-11ea-9bba-93a92c12d608.png)

3. Click OK to drop table.
![drop-2](https://user-images.githubusercontent.com/64098128/90697076-947f0b80-e24b-11ea-9996-80ef0b856b67.png)

4. Modal dialog box comes up with error message "no such table: table-name.
![drop-3-error](https://user-images.githubusercontent.com/64098128/90697198-d6a84d00-e24b-11ea-8129-c5e68b970997.png)

**Expected behavior**
Table should be dropped with no error message.

**Screen shots**

**Comment by SQLiteFlow** [comment]
The error is prompted by the Data Editor when it trying to reload a table that already not existed.

The Data Editor actually did prompt the right thing but it do looks weird in this situation, I will think a way to improve that.

Thank you for the report.

**Comment by SQLiteFlow** [comment]
Fixed. In this situation, let SQLiteFlow remove the tab automatically instead of promoting an error.

**Comment by bitxianaiz** [comment]
Great!


Sent from Yahoo Mail for iPhone


On Thursday, August 20, 2020, 6:32 AM, SQLiteFlow <notifications@github.com> wrote:




Fixed. In this situation, let SQLiteFlow remove the tab automatically instead of promoting an error.

**Comment by SQLiteFlow** [comment]
SQLiteFlow(macOS) 4.5.0 has been released.
