### ISSUE TITLE
SQLiteFlow not starting under iOS 14

### ISSUE THREAD

**Issue by wilpert** [SQLiteFlow/SQLiteFlow-Issues#141]
Hi,

SQLiteFlow does not start under the latest iOS 14 beta (iPhone X). iOS 14 has not yet been officially released, but I thought I just let you know.

Best regards,
Alexis

**Comment by SQLiteFlow** [comment]
Thank you. 
I will check it and release a fix soon.

**Comment by SQLiteFlow** [comment]
Fixed in SQLiteFlow(iOS) 4.3.6. And it available in App Store now.
