### ISSUE TITLE
无法恢复购买

### ISSUE THREAD

**Issue by MountainAndMorning** [SQLiteFlow/SQLiteFlow-Issues#148]
**Version**
 - Platform: [e.g. macOS 10.14.5]
 - SQLiteFlow: [e.g. 3.6.0]

**Steps to Reproduce**

**Expected behavior**

**Screen shots**

**Comment by SQLiteFlow** [comment]
1. Which platform are you in? macOS or iOS?

2. Which version of SQLiteFlow are you using?

3. What error message did you see? Can I get a screenshot?
