### ISSUE TITLE
Keyboard and mouse support (iPadOS)

### ISSUE THREAD

**Issue by kspeeckaert** [SQLiteFlow/SQLiteFlow-Issues#149]
Currently, there is no specific keyboard or mouse support in the app (e.g. long-press on the command key doesn’t show the popover with key combinations).

I’m convinced that there are quite a few areas where this might improve the app substantially (e.g. CMD-Enter to execute a query).

**Comment by SQLiteFlow** [comment]
The shortcut for running query is CMD + R.
The shortcut for formatting query is CMD + I.

The popover tip with command key is not show up currently, because of the shortcuts doesn't always work when I'm testing them, maybe caused by iOS's bug or maybe caused by I implemented them with a not quite right way. I will see what I can do to improve it.

And where else do you also expect to have keyboard shortcuts? Please let me know and I will see what I can do.

**Comment by kspeeckaert** [comment]
Great, I didn’t realise that there was already support!

Maybe a popup menu in the tables/views list, when right-clicking on a table or view? I don’t know how easy/difficult this is to achieve.

As for the keyboard, the only thing I’m really missing when writing a query is  shortcut to trigger the “intellisense”, keeping me from having to guess a table name or going back to the list of tables.

**Comment by SQLiteFlow** [comment]
> As for the keyboard, the only thing I’m really missing when writing a query is shortcut to trigger the “intellisense”, keeping me from having to guess a table name or going back to the list of tables.

SQLiteFlow supports multiple windows for iPadOS, please see the screenshot below. 
The table list is on the left window, and the query editor is on the right window. 
Can this feature fulfill your needs? 
![pic1](https://user-images.githubusercontent.com/38027540/97936030-493db900-1db5-11eb-8a28-eff45cb94de7.png)


> Maybe a popup menu in the tables/views list, when right-clicking on a table or view? I don’t know how easy/difficult this is to achieve.

Sorry, I'm not quite sure what the question is, you mean right-click to bring up the "Rename" popup menu?
![pic2](https://user-images.githubusercontent.com/38027540/97936225-d4b74a00-1db5-11eb-8451-5fa558d3598c.png)

**Comment by SQLiteFlow** [comment]
In SQLiteFlow(iOS) 4.8.0, long-press on the command key will show the shortcuts tip (if available), and the shortcuts looks statable in iOS 14 now.
