### ISSUE TITLE
Hotkey for "Run selected query"

### ISSUE THREAD

**Issue by dhf** [SQLiteFlow/SQLiteFlow-Issues#15]
Currently there is only a hotkey for Run Query (CMD+R), is it possible to implement also a hotkey for "Run selected query"?

**Comment by SQLiteFlow** [comment]
@dhf Yes, I can implement it in next version. Is Cmd + Shift + R good for you?

**Comment by dhf** [comment]
That sounds good :)

**Comment by SQLiteFlow** [comment]
@dhf Okay, it's been implemented now. The hotkey will available in next version.

**Comment by SQLiteFlow** [comment]
@dhf 
The new version of SQLiteFlow has been released, and it contains an update: 
Add shortcut Cmd + Shift + R to ‘Run selected query’.

**Comment by dhf** [comment]
Great, thanks for your reply, already installed :)

**Comment by SQLiteFlow** [comment]
@dhf You are welcome.
