### ISSUE TITLE
Import CSV (iOS)

### ISSUE THREAD

**Issue by kspeeckaert** [SQLiteFlow/SQLiteFlow-Issues#150]
I have a few improvements I’d like to suggest for the Import CSV dialog:

- First line as header as default. This would make it consistent with the Export CSV dialog which also has this option turned on by default.

- After importing a CSV without giving it a table name, the table name is derived from the filename. However, it isn't cleared when selecting a different CSV. I don’t know if this is intentional though.

- Offer the option to truncate a table before importing.

**Comment by SQLiteFlow** [comment]
> First line as header as default. This would make it consistent with the Export CSV dialog which also has this option turned on by default.

Sure.

> After importing a CSV without giving it a table name, the table name is derived from the filename. However, it isn't cleared when selecting a different CSV. I don’t know if this is intentional though.

It's an unintentional behavior, will fix it.

> Offer the option to truncate a table before importing.

Sure.

**Comment by SQLiteFlow** [comment]
SQLiteFlow(iOS) 4.6.1 has been released.
