### ISSUE TITLE
Shortcuts support

### ISSUE THREAD

**Issue by kspeeckaert** [SQLiteFlow/SQLiteFlow-Issues#151]
While probably not easy to accomplish, being able to perform actions on a database from Shortcuts would be fantastic.

Example actions:

- Truncate a table and load data from a CSV
- Execute a query and receive the result in CSV or JSON

**Comment by SQLiteFlow** [comment]
You mean from the Shortcuts app, right?
It's very interesting to me. I will see what I can do to support it.
The example actions you mentioned above may come up first.

**Comment by SQLiteFlow** [comment]
Status update:

In next version of SQLiteFlow(iOS), will add two "Intents" supports, one is "Run Query", and another is "Import CSV",  they will appear in Shortcuts.

This feature will requires iOS 14.0 or later to work properly. 
Two screenshots attached.

For the "Run Query" intent, user can input a SQL to execute on a database that in an "External Folder" which is added in SQLiteFlow's "External Files" section. 
User can choose the query results export as CSV, JSON or MarkDown format.

For the "Import CSV" intent, user can select a CSV file or a piece of CSV text to import it to a table. The importing configuration is basically same as it is in the main app.

And the main app is not required to launch to run these two intents.

![RunQuery](https://user-images.githubusercontent.com/38027540/99753242-bd0ce080-2a9a-11eb-8b78-7a84a47a35f7.png)
![ImportCSV](https://user-images.githubusercontent.com/38027540/99753250-c007d100-2a9a-11eb-9c79-34727fe968f4.png)

**Comment by SQLiteFlow** [comment]
SQLiteFlow(iOS) 4.6.1 has been released. Now it supports Shortcuts.

**Comment by kspeeckaert** [comment]
I’ve tested the Import intent, and it works, except for one of the CSV files. The file in question imports without issue in the app itself, but fails every time when executing the Import through Shortcuts. The file itself is 8.5MB, and contains ca. 65.000 records.

Below is the error generated when running the import through Shortcuts:

![7CE74453-DF7C-4A54-83F3-174516864C67](https://user-images.githubusercontent.com/6348619/100147037-1611b580-2e9b-11eb-9653-592f1af6fcf4.jpeg)

And when the same file is imported in the app itself:

![8CE56DFF-8412-4005-82DC-109793F557EB](https://user-images.githubusercontent.com/6348619/100147045-17db7900-2e9b-11eb-9cb9-1ccc7a0536d6.jpeg)

If interested, the file itself is publicly available [here](https://epistat.sciensano.be/Data/COVID19BE_CASES_MUNI.csv).

**Comment by SQLiteFlow** [comment]
Thanks for the report. 
I reproduced this issue on my iPhone 7 device with the CSV file you attached.

The error `"Could not run Import CSV. There was a problem communicating with the app"` indicate that the Import CSV intent extension crashed.

And it crash because of it try to use more than 30 MB memory to process the CSV file, a screenshot attached to show that crash error. 

Looks like 30 MB memory is the max size that an intent extension could use in iPhone 7, the value may be a little different in other iOS devices.

And, if interested, there's another limit to an intent extension, that is it should run less than 10 seconds a time.

Looks like Apple wants user avoid to do too much heavy work with an intent extension.

So I wonder if I can know more about your use case with the Import CSV intent extension, so I can see what I can do with it under these two limitations I mentioned above.

![MemorySizeLimit](https://user-images.githubusercontent.com/38027540/100200449-971f8a00-2f39-11eb-9172-dc8679b15d9c.png)

**Comment by kspeeckaert** [comment]
> So I wonder if I can know more about your use case with the Import CSV intent extension, so I can see what I can do with it under these two limitations I mentioned above.

For this example, I pull several CSV files from the Internet, load them into SQLiteFlow and then perform several SQL queries on them to aggregate/format the data, taking the CSV output and then passing it on to [Charty](https://chartyios.app) to turn it into a graph. Charty can process CSV data (file or text), but cannot easily aggregate, reformat, etc. I've done this in the past using a Python script (using [Pythonista](http://omz-software.com/pythonista/)), but being able to use plain SQL would allow for much more flexibility.

> Looks like 30 MB memory is the max size that an intent extension could use in iPhone 7, the value may be a little different in other iOS devices.

I've seen the same thing in other apps that offer integration with Shortcuts, where they have the option to either run the action within Shortcuts (and be limited in the amount of resources / time available), or switch to the app, perform the action there (without any restrictions) and return back to Shortcuts. [Scriptable](https://scriptable.app/) is an example of such an app with that kind of implementation (with the intents _Run Script_ and _Run Inline Script_).

Alex Hay (author of [Toolbox Pro](https://toolboxpro.app)) has written extensively on integrating an app with Shortcuts ([part 1](https://toolboxpro.app/blog/adding-shortcuts-to-an-app-1), [part 2](https://toolboxpro.app/blog/adding-shortcuts-to-an-app-2), [part 3](https://toolboxpro.app/blog/adding-shortcuts-to-an-app-part-three) and [part 4](https://toolboxpro.app/blog/adding-shortcuts-to-an-app-part-four)), if you're interested.

**Comment by SQLiteFlow** [comment]
Thank you. I will have a look at it and see what I can do.

**Comment by SQLiteFlow** [comment]
SQLiteFlow(iOS) 4.6.2 has been released.

1. Now both Run Query and Import CSV intent supports "Run In App".

2. Run Query Intent now supports save the query results to an "External Folder", see screenshot 1. 
So "load them into SQLiteFlow and then perform several SQL queries on them to aggregate/format the data, taking the CSV output to a folder" now can be done in one action.

3. Import CSV intent now supports choose a CSV file from an "External Folder", see screenshot 2.
So choose a CSV file and do import CSV now can be done in one action.

Screenshot 1:
![screenshot 1](https://user-images.githubusercontent.com/38027540/100684454-57332980-33b5-11eb-8b8f-dbfdff345482.png)

Screenshot 2:
![screenshot 2](https://user-images.githubusercontent.com/38027540/100684475-5dc1a100-33b5-11eb-978f-969d69015d27.png)

**Comment by kspeeckaert** [comment]
I haven't tested it extensively yet, but just by enabling the _Run In App_ in my existing test shortcut, the CSVs imported without any issue (and pretty dang fast too!). Thank you!

**Comment by SQLiteFlow** [comment]
You're welcome!
