### ISSUE TITLE
Export database to .sql file

### ISSUE THREAD

**Issue by moodeaudio** [SQLiteFlow/SQLiteFlow-Issues#152]
Hi,

Is there a way to export a database to a .sql file?

-Tim

**Comment by SQLiteFlow** [comment]
It can't yet. I can implement this in future version.
Which platform are you in? macOS or iOS?

**Comment by moodeaudio** [comment]
macOS

**Comment by SQLiteFlow** [comment]
Sure. Thank you.

**Comment by SQLiteFlow** [comment]
SQLiteFlow(macOS) 4.8.0 is available on App Store now. 
It includes an update that supports dump database to a SQL file.
