### ISSUE TITLE
Button alignment

### ISSUE THREAD

**Issue by kspeeckaert** [SQLiteFlow/SQLiteFlow-Issues#155]
**Version**
 - Platform: iPadOS 14.2
 - SQLiteFlow: 4.6.2

**Steps to Reproduce**

Open SQLiteFlow, and then add a second window. Play around with the split (50/50, 30/70, …) and see the _Select_ button in the top toolbar change positions.

**Expected behavior**

The position of the button should remain aligned with the other controls.

**Screen shots**
![image](https://user-images.githubusercontent.com/6348619/100920151-04539200-34db-11eb-9f4a-09e398425622.png)
![image](https://user-images.githubusercontent.com/6348619/100920165-09184600-34db-11eb-9ecb-a66c128dc7fe.png)
![image](https://user-images.githubusercontent.com/6348619/100920191-0d446380-34db-11eb-8190-987186f340b8.png)

**Comment by SQLiteFlow** [comment]
This is a SQLiteFlow's compatible issue in iOS 14, will check and fix it.
Thank you.

**Comment by SQLiteFlow** [comment]
This issue has been fixed in SQLiteFlow(iOS) 4.8.0, and it's available on App Store now.
