### ISSUE TITLE
Query files

### ISSUE THREAD

**Issue by kspeeckaert** [SQLiteFlow/SQLiteFlow-Issues#156]
I'm a little confused when it comes to query files (used to store SQL). I think my initial confusion came from opening the query file directly, without first opening the database. Suddenly, my queries started throwing errors, stating that the table couldn't be found.

Going back and opening the database, then selecting Queries and opening the SQL file, resolved the issue.

I suspect this allows SQL files to be database independent, allowing reuse. But perhaps the query files should be hidden initially (as it doesn't make sense opening them outside of a database context)?

**Comment by SQLiteFlow** [comment]
1. When open a SQL file without selecting a database, a SQLite [in-memory database](https://sqlite.org/inmemorydb.html) will be automatically associated to the SQL file, so user is actually opening it inside of a database context.

2. With that, user could view/edit, do some calculating things through temp tables, or just run some simple queries like `SELECT sqlite_version();`  which don't require a database that is a disk file, etc.

3. In SQLiteFlow, "Browse" works like that: it behave like a lite file browser, so every file can be displayed, but only supported files (like SQLite database, SQL file, CSV file, JSON file, Markdown file, Folder) can be opened, others are grayed out and can't be opened.

4. To see which database is associated with an opened SQL file, and avoid confusing, currently user can check the back button at the navigation bar, if a database that is a disk file is associated, the title of it will be the name of the database.

**Comment by kspeeckaert** [comment]
Thank you for clarifying!
