### ISSUE TITLE
App requests Apple ID credentials on first start up?

### ISSUE THREAD

**Issue by janczawadzki** [SQLiteFlow/SQLiteFlow-Issues#158]
The dialog looks like it belongs to the app, not the Apple Store.

I'm concerned that you're collecting credentials, this certainly looks bit scary.

**Comment by SQLiteFlow** [comment]
It's belong to the App Store. This app does not collect data from users, so just relax.
The "2-week Trail" is actually a one-time in-app purchase item with cost $0. 
On Mac, I think you will be requested to input credentials (if you are not on a Mac with Touch ID) when you are buying any in-app purchase item.

Attached a screenshot from Mac App Store.
<img width="335" alt="1" src="https://user-images.githubusercontent.com/38027540/108618045-cb7de600-7455-11eb-9ff4-7e506a5cacd0.png">

**Comment by zakaria20021** [comment]
2 weeks

**Comment by janczawadzki** [comment]
I switched AppStore to use fingerprint recognition and that clearly worked as described.  This is a screw up on Apple's part - the dialog appears to be part of the app, not an Apple generated prompt, so it'd be trivial for an app to create one that looks just like it.  I've seen a few negative comments on the AppStore about this, you might want to put a heads-up before this prompt to let people know a) it's AppStore, and b) you can use fingerprint to deal with this if uncomfortable with the risk of giving app your Apple credentials.

**Comment by SQLiteFlow** [comment]
@janczawadzki Thank you. Maybe in future version of SQLiteFlow, I will put a heads-up to mention more detail about the credentials inputting prompt to avoid users feel too scary.
