### ISSUE TITLE
Exporting Table Does Not Suitably Escape Column Names

### ISSUE THREAD

**Issue by ssnkhan** [SQLiteFlow/SQLiteFlow-Issues#159]
**Version**
 - Platform: macOS 10.15.7
 - SQLiteFlow: 4.8.3

**Steps to Reproduce**
1. Use the wizard to import the following CSV: [countries.txt](https://github.com/SQLiteFlow/SQLiteFlow-Issues/files/6136415/countries.txt)
2. Export the table as an _Insert Statement,_ with _Include Create Table_
3. Try importing the resulting `.sql` file via the CLI, using `.read countries.sql`
4. Generate a plethora of `Error: near line 17: near "-": syntax error` errors, due to a hyphen in various column names 

**Expected behavior**
1. The export should automatically escape/double quote/backtick enclose those columns with special characters, like the hyphen

I appreciate that ordinarily it would be best not to use hyphens in the column names, but I frequently need to use similar CSV files, and this would be the most convenient process for me.

Thanks!

**Comment by SQLiteFlow** [comment]
I think it's bug. I will fix it.

**Comment by SQLiteFlow** [comment]
This issue has been fixed in SQLiteFlow(macOS) 4.8.4, and it's available on App Store now.

**Comment by ssnkhan** [comment]
Thank you :)

**Comment by SQLiteFlow** [comment]
You're welcome.
