### ISSUE TITLE
Export queries

### ISSUE THREAD

**Issue by clsnyder** [SQLiteFlow/SQLiteFlow-Issues#16]
Is it possible to export the results of a query (without copying the query, opening a terminal window, and running and saving the query to csv file, for example)?

Thanks!

**Comment by SQLiteFlow** [comment]
Hello @clsnyder,
I am not quite understand the question right now.
You want to save the results of a query to a CSV file eventually?

**Comment by clsnyder** [comment]
Yes
I must be missing something, but just wanting to export the results of a query

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by SQLiteFlow** [comment]
@clsnyder 
Currently SQLiteFlow supports copy query results as CSV to memory, a screen shot has been attached, can this feature fulfill your need?

![screen shot](https://user-images.githubusercontent.com/38027540/53690302-e8213f00-3da2-11e9-8c23-f776aa8bd90e.png)

**Comment by clsnyder** [comment]
Yes
Thank you for your help!

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by SQLiteFlow** [comment]
@clsnyder 
You are welcome!
