### ISSUE TITLE
Feature Request: Save as View

### ISSUE THREAD

**Issue by ssnkhan** [SQLiteFlow/SQLiteFlow-Issues#160]
It would be super helpful to be able to right click on a valid `SELECT` query within the Editor, and be given the option to save it as a View. A prompt could up asking for the View name, which the app could execute as `CREATE VIEW $NAME AS ...`.

Double clicking on such a saved View should then execute `SELECT * from $VIEW`.

Hope this makes sense, would certainly make things very convenient for me!

**Comment by SQLiteFlow** [comment]
Make sense to me.
How about implement the routine like this:
(A demo video has been attached.)

1. User select a string in query editor.
2. If the selected string has prefix "SELECT", then a "Create View..." menu item will appear in the right click menu.
3. User click the "Create View..." menu item, a new query editor as a sheet with a view creating query based on the user selected string will be presented.
4. User can choose to change the name of the view.
5. After review the view creating query, user can either click the run query button or type "cmd + r" to execute the query.
6. Then after the query execute finished, the sheet will disappear, and the view list will be refreshed, user can double click a view in the view list to check the data.

https://user-images.githubusercontent.com/38027540/111254291-aee95e00-864f-11eb-94b8-be554c09da7e.mp4

**Comment by ssnkhan** [comment]
That’s perfect, thank you!

**Comment by SQLiteFlow** [comment]
SQLiteFlow(macOS) 4.9.0 has been released. This feature now is available.
