### ISSUE TITLE
Feature Request: Preference for Click Action

### ISSUE THREAD

**Issue by ssnkhan** [SQLiteFlow/SQLiteFlow-Issues#161]
It would be great if there was a user preference to specify the single click action. Currently, clicking in a row allows a user to edit the cell value straight away. I would like it such that with this setting enabled:

1. Single Click = highlight/select cell only
2. Double Click = Enter edit mode

Really appreciate all your work on this app, thanks!

**Comment by SQLiteFlow** [comment]
This feature sounds cool to me, I will look into it.
You're welcome by the way.

**Comment by SQLiteFlow** [comment]
After some investigation, I found another solution for fitting your requirement (select a row with a single click, and without triggering editing).

The solution is, make a floating header at the left of the table view in Data Editor, so you can always select a row by clicking the area of the floating header without triggering editing. 
A screenshot has been attached, and do you think this solution is still looks good for you?

Regards.

![Floating Header](https://user-images.githubusercontent.com/38027540/111577226-d45f9e80-87ec-11eb-997b-d2cee4e4600d.png)

**Comment by ssnkhan** [comment]
This is great -- guessing it's floating as it persists even when scrolling to the right?

**Comment by SQLiteFlow** [comment]
Yes, the floating header mentioned above will always show up at left, just like currently the title header always show up at top.

**Comment by SQLiteFlow** [comment]
SQLiteFlow(macOS) 4.9.0 has been released. Now you can try this feature to see if you like it or not, and please let me know if you have any questions.
