### ISSUE TITLE
Silent failure in Shortcuts action

### ISSUE THREAD

**Issue by pointlessone** [SQLiteFlow/SQLiteFlow-Issues#162]
**Version**
 - Platform: iOS 14.4.1
 - SQLiteFlow: 4.8.3

**Steps to Reproduce**

I do t know how to reproduce initial conditions.

Once in a while do file appears as not downloaded. When that happens Shortcuts action fails with an unhelpful message.

Once I open the app and tap the Download button the issue gets resolved.

**Expected behavior**

Should be great if action could automatically download the db file whenever it gets unloaded. 

**Screen shots**

I didn’t think to take one and it works now. Next time I’ll take some screenshots.

**Comment by SQLiteFlow** [comment]
I will look into it and see what I can do.

**Comment by SQLiteFlow** [comment]
SQLiteFlow(iOS) 4.8.4 has been released. 
Now it will download any required files before actually do its job.

And one thing you may be interested in is, if the option "Run in App" is turned off, you may experience a timeout error if the downloading time is too long (like exceed 10 seconds) for a shortcut action.
