### ISSUE TITLE
New filter: "SQL expression" 

### ISSUE THREAD

**Issue by rene-aguirre** [SQLiteFlow/SQLiteFlow-Issues#163]
I'm loving the app, I really like the filtering simplicity.

But sometimes I need more "power", and there are things that would be easily expressed in a SQL expression.

So my proposal here is to add a new "<SQL expression>" like option to the columns combo and leave empty/grayed out the operator selection combo... or use "<other>" for column selection and use "SQL" in the operations selection combo.

Some advantages:
* Access to other SQL operators (like `in`)
* filter using table joins!

**Comment by SQLiteFlow** [comment]
Sounds cool to me, I will see what I can do.

**Comment by SQLiteFlow** [comment]
Hello @rene-aguirre,

After some investigation, I found to support "access to other SQL operators (like in)", I can implement it without too much work by just adding another operator, maybe called "SQL", to the operator selection combo.

And to support filter using table joins, as you mentioned before, a "" string option may be added to the columns selection combo. However, currently the filter function in SQLiteFlow is all based on "where" clause, so any table joins relate SQL should appear before the "where" clause. And that makes the "" string option in the columns selection combo should only be specified before any filter that is based on "where" clause, or SQL error will appear.

So could you give me a use case that you write table joins relate SQL in the filter function? That could help me have a concrete sense or goal to implement the feature.

Regards.

**Comment by SQLiteFlow** [comment]
How about implement the feature like this? A screenshot has been attached.

1. In Data Editor, add an operator  “SQL” to enable some customize filters like “in” base on “WHERE” clause.
2. To add some more complex filters like table joins, copy the query showing at the bottom of the Data Editor and paste it to a Query Editor, then tweak the query and execute the query.

![filter](https://user-images.githubusercontent.com/38027540/115953328-6447e500-a51d-11eb-892b-2284505a8473.png)

**Comment by rene-aguirre** [comment]
I like the SQL operator idea

**Comment by SQLiteFlow** [comment]
Then I will implement the SQL operator idea first.

**Comment by SQLiteFlow** [comment]
SQLiteFlow(macOS) 5.0.0 has been released, and this feature is available now.
