### ISSUE TITLE
can't open password protected sqlite databases

### ISSUE THREAD

**Issue by marchharesoftware** [SQLiteFlow/SQLiteFlow-Issues#165]
Hi!

I just started the free trial of your app on the Mac App Store.

I can't open any password protected sqlite database.

The database is created:

                    SQLiteConnection.CreateFile(c1.sqlitedb);
                    c1.sqlitecx = new SQLiteConnection("Data Source=" + c1.sqlitedb + ";Version=3;");
                    if ((c1.sqlitepass != null) && (c1.sqlitepass != ""))
                    {
                        if (c1.sqlitepassset)
                            c1.sqlitecx.SetPassword(c1.sqlitepass);

We open it like this:

                    sqlcnxstr = "Data Source=" + c1.sqlitedb + ";Password=" + c1.sqlitepass + ";Version=3;";
                    c1.sqlitecx = new SQLiteConnection(sqlcnxstr);
                    c1.sqlitecx.Open();

Can you adapt your product so it has the ability to open password protected sqlite databases?

I can't believe anyone uses unencrypted databases beyond prototyping maybe…

Regards,

Arthur

**Comment by SQLiteFlow** [comment]
Which encryption library are you using?

**Comment by marchharesoftware** [comment]
Just the default Windows .NET with C# - it includes encryption a described.

Apparently what this actually is is not well documented (though it must be open source), not sure why it's not been ported more widely.  

I am looking into whether we can use Zetetic SqlCipher ADO as a more portable solution...

**Comment by SQLiteFlow** [comment]
In theory, SQLiteFlow for macOS could support SQLite encryption by embedded a SQLCipher library, but need some time to investigate it.

**Comment by SQLiteFlow** [comment]
In next version of SQLiteFlow(macOS), will add support for handle encrypted SQLite database which is encrypted by SQLCipher library.

To open such a database,
1. In Preference - General, set SQLite Library to "SQLCipher".
![pic1](https://user-images.githubusercontent.com/38027540/116957257-03ad6a80-acca-11eb-9758-b9f4b8437c94.png)

2. Then Open the dababase like open a normal database, an configuration dialog will show up, you can input encryption key or other information there.
![pic2](https://user-images.githubusercontent.com/38027540/116957345-4111f800-acca-11eb-9250-cde317e9e166.png)

3. After finished configuration, click "Open" to open it.

**Comment by SQLiteFlow** [comment]
SQLiteFlow(macOS) 5.0.0 has been released, and this feature is available now.

**Comment by marchharesoftware** [comment]
Thanks - I’ve tested this and it works.

Can I make some suggestions?

1)
SQLCipher is OK, but our database was originally encrypted with the ’native’ System.Data.SQLite encryption.

I’ve since found a library which will open this, even on MacOS:
https://github.com/utelle/wxsqlite3/

Specifically the ’native’ Win32 encryption is "RC4 - No HMAC"

Now that’s not a great level of encryption, so even though I’ve now found a 3rd party, cross platform solution for reading it, I am likely to stick with SQLCipher or something like it.

But for the purpose of your app, and people finding it immediately useful with ’native’ encrypted SQLite databases from the windows world, I think adding wxsqlite3 and making it clear that “RC4 - No HMAC” is the right setting for ’native’ win32 encrypted databases would be worth the effort.

2)

I think that having the SQLCipher option ‘buried’ in preferences is not ideal, especially in the trial period. When I open SQLiteFlow I see a blank screen with the ‘open a database..’ Button, my suggestions include:
- two buttons - open database, open encrypted databases, or
- the button first opens a dialog for you to choose which sqlite library before the filename
- the ‘options’ button on the file dialog has an option for sqlite library
- below the ‘open a database’ button, some plain text saying something about choosing SQLCipher in preferences.
- if ‘opening’ a database fails, but the file does exist, maybe a prompt for ‘is this an encrypted database?’ Which would leave a user to say ‘yes’ and then select the correct sqlite library/cipher



I really can’t imagine many professional developers don’t encrypt their databases, so now your product supports encrypted databases with SQLCipher you do want to make it easy for people evaluating your product to find the option and use it.

Now I can actually open the database in SQLiteFlow - I’ll have a closer look at its features.

Regards,


Arthur


On 5 May 2021, at 12:24 am, SQLiteFlow ***@***.******@***.***>> wrote:



SQLiteFlow(macOS) 5.0.0 has been released, and this feature is available now.

**Comment by SQLiteFlow** [comment]
1) I will think about it.

2) I understand the current behavior may feel a little wired at the first time, and your suggestion about the open database behavior better makes some sense to me too.

But Unfortunately this is not how SQLiteFlow currently work. Currently, the SQLite library this a global config or variable for the app, and too many features (or maybe most?) rely on this variable to be global to work correctly, so I would like to keep the current behavior unchanged currently.

And another reason that the current behavior is worth to exists is that it's just a one time config, it could makes users feel convenience in most of time. For example, when you choose use to use SQLCipher library in Preference, you may want to keep this config unchanged for a period of time because your app that you are developing is using this library, and with this config, you can not only open an encrypted database with a specific key but also can still open an unencrypted directly without any interruption.
