### ISSUE TITLE
Is syntax UPDATE from CTE available?

### ISSUE THREAD

**Issue by natnapong** [SQLiteFlow/SQLiteFlow-Issues#167]
Hello,

I would like to UPDATE some data after using WITH _CTE_ AS (.....) but it can't find my _CTE_. Is this syntax available on SQLiteFlow? Thank you.

**Comment by SQLiteFlow** [comment]
It supports.

To see which SQLite version you're using, go to SQLiteFlow - Preferences - General - SQLite Library if you are on Mac. Or execute query `SELECT sqlite_version();` in an Query Editor.

To see which features in CTE are available on which SQLite version, you can go to [https://sqlite.org/changes.html](url) and search `common table expressions`.

Regards.
