### ISSUE TITLE
App doesn't seem to enforce foreign keys

### ISSUE THREAD

**Issue by tiltowait** [SQLiteFlow/SQLiteFlow-Issues#169]
The app doesn't seem to enforce foreign keys inside the editor. If I have a key set to cascade updates/deletions, changes are not applied in the table that references those fields, nor do insertions that violate the foreign key fail.

From some testing, it's clear my foreign key constraints are correct; SQLiteFlow doesn't seem to have the `foreign_keys` PRAGMA enabled inside the main editor. If I manually enable it in an SQL query, the changes cascade as expected; however, that only happens within the context of that query object and not in the main editor.

Is there a way to run the equivalent of `PRAGMA foreign_keys=ON;` inside the main editor?

**Comment by SQLiteFlow** [comment]
Yes. Go to Preferences - General, set Enable Foreign Key Constraints to On.

**Comment by SQLiteFlow** [comment]
And here's a screenshot.
![fk](https://user-images.githubusercontent.com/38027540/124664128-91c9eb00-dedd-11eb-9ee3-d9af020f34e5.png)

**Comment by tiltowait** [comment]
Perfect! Thanks for the great app.
