### ISSUE TITLE
Free trial

### ISSUE THREAD

**Issue by Jjjjoejedi** [SQLiteFlow/SQLiteFlow-Issues#170]
I have agreed trial i AM wondering if it automatically renews

**Comment by SQLiteFlow** [comment]
There's no subscription purchase schema in SQLiteFlow, that is there's no automatically renew thing.

You buy "2-week Trial" with $0 for taking a 2 weeks free trial.

After the trial end, app will be locked, and no automatically renews would happen.

You can buy "Full App" to unlock the app though, the "Full App" is just a one-time in-app purchase too.
You purchased the "Full App", you own the app lifetime.

Regards.
