### ISSUE TITLE
File Size

### ISSUE THREAD

**Issue by Kandan2112** [SQLiteFlow/SQLiteFlow-Issues#177]
What is the max SQL File size that can be edited.  Seems to be less than 9K.  I have some large stored procedure files that I am trying to edit and the app just shuts down.

**Comment by SQLiteFlow** [comment]
I don't think there're any size limit for editing a SQL file.

To better assist you, I may need more information about the issue you met.

Which platform are you in? macOS or iOS?
Which device model are you using?
Which app version are you using?
Can I get a demo video for reproducing the crash?
Can I get a crash log?

**Comment by SQLiteFlow** [comment]
Close for now. This issue is welcome to be reopened at any time.
