### ISSUE TITLE
CSV import to table with autoincrement field

### ISSUE THREAD

**Issue by tiltowait** [SQLiteFlow/SQLiteFlow-Issues#178]
I have a table with a primary key that is simply an autoincrementing index. I'm trying to import several CSV files, which do not have the index column. If I attempt to import, SQLiteFlow says that there's a column number mismatch. If I add an empty column, I am informed of a data type mismatch.

Short of generating the keys by hand for every CSV I want to import, is there a way for SQLiteFlow to automatically generate the proper value?

See [this](https://stackoverflow.com/questions/15994231/import-csv-into-sqlite-with-autoincrementing-primary-key) post for further explanation of what I'm talking about.

**Comment by SQLiteFlow** [comment]
I think you already get a right answer in the post you attached.
That is,
1. Import the CSV file to a new table. 
    In SQLiteFlow, at the Import dialog, you can just leave the "Table" fields empty to create a new table.
    After the data imported, the new table may be created as `_csv_20210901`

![Screen Shot 2021-09-01 at 6 00 30 AM](https://user-images.githubusercontent.com/38027540/131581781-183325fb-dcc4-4eb1-a95a-d83b0142a329.png)

2. Open a new query, then run a query like
```
INSERT INTO YourTable
SELECT
   NULL,
   *
FROM _csv_20210901
```
to import the data to your table.

**Comment by SQLiteFlow** [comment]
In the latest version(5.8.2) of SQLiteFlow, one of a feature added is:

_Import CSV, if “First Line in CSV is Header” is enabled, and is set to import to an existing table, then if the header fields is a subset of the table fields, you can now import it correctly if database constraints allows._

Maybe that could help you do the job if your CSV has a header line and only the column of auto increment field is not included.
