### ISSUE TITLE
Export Table to JSON File - data appear out of order

### ISSUE THREAD

**Issue by billywizzz** [SQLiteFlow/SQLiteFlow-Issues#185]
Created a simple table to store settings and values - only two fields with the setting as the primary key. When the table is exported to JSON the setting and value are randomly out of order. Example output is below...
[
  {
    "setting" : "webcamEast",
    "value" : "test1"
  },
  {
    "value" : "test2",
    "setting" : "webcamWest"
  },
  {
    "value" : "test3",
    "setting" : "webcamNorth"
  },
  {
    "setting" : "webcamSouth",
    "value" : "test4"
  },
  {
    "value" : "test5",
    "setting" : "webcamHome"
  }
]

**Comment by SQLiteFlow** [comment]
Is there a particular reason you want the keys to be sorted? 
Since order of JSON object is not defined in JSON specification.

**Comment by billywizzz** [comment]
Thanks, that’s useful to know. I assumed the order in the table would be the order in the json file.
Also thank you for the regular updates to the app and the great support.

**Comment by SQLiteFlow** [comment]
You're welcome！
