### ISSUE TITLE
SQLite system tables

### ISSUE THREAD

**Issue by maxoriggi** [SQLiteFlow/SQLiteFlow-Issues#186]
Hello,
great app first of all!
As a new user I'm just starting using it and... I have a feature request: an option to display also the sqlite system tables, really useful to debug issues.

**Comment by SQLiteFlow** [comment]
You mean sqlite_master?

**Comment by maxoriggi** [comment]
Yes, but also other sqlite_ prefixed tables that it generates such as sqlite_sequence, sqlite_autoindex, sqlite_stats which are generated in specific conditions.

**Comment by SQLiteFlow** [comment]
I think sqlite_master is the only table that SQLiteFlow will not display in table list currently.
Tables that could be retrieved in `select * from sqlite_master;` will show up in table list, including sqlite_sequence, sqlite_stats, etc, that you mentioned above.

**Comment by maxoriggi** [comment]
Ok nice!

**Comment by SQLiteFlow** [comment]
So, does the currently behavior of SQLiteFlow still an issue for you?

**Comment by maxoriggi** [comment]
I would say no, while it would be nice to have the master table a click away, it's not that useful now as the other tables are displayed anyway and so it would add any additional info.

**Comment by SQLiteFlow** [comment]
If you wonder, the reason that SQLiteFlow not display it in table list, is because there's already a GUI form of sqlite_master table in SQLiteFlow, which is, basically, the entire app.😄

So is that good for you? 😄

**Comment by maxoriggi** [comment]
True, my initial question started from my doubt that it did show any system table, but as they are there (and also the creation query I missed in my first tour around the app), there isn't anything more from master to show as you just said.
Thanks for your quick reply, I'll likely post more questions as I use the app in the coming weeks to debug an iOS app I'm working on 😉
