### ISSUE TITLE
Purchase

### ISSUE THREAD

**Issue by GalrionDev** [SQLiteFlow/SQLiteFlow-Issues#188]
Hi,
after the trial I bought this App for 23,99 Euro.
Then I got the message "An error occured".
I can see the app in the app store in bought apps, of course (the trial).
When I try to start SQLiteFlow the "Trial complete" window appears.
"Restore Previous Purchase" doesn't work.
What went wrong?

Markus

**Comment by SQLiteFlow** [comment]
Could you offer me some additional informations to better assist you?

1. What's your Mac model and macOS system version?

2. Are you sure the purchase succeeded once? I mean, for example, if there was a network error lead to purchase failed, you actually not cost any money, so could you check that? And if you not cost money for that, the "Full App" in-app purchase is not be bought of course.

3. You can also send your receipt file which is at location `/Applications/SQLiteFlow.app/Contents/_MASReceipt/receipt`, to my email `sqliteflow_AT_hotmail.com`, to let me check if you bought the "Full App" in-app purchase successfully or not.

**Comment by GalrionDev** [comment]
1. MacBook Pro (i9, 15 Zoll, 2019), Monterey 12.1
2. not really sure if the purchase was completed, no receipt from Apple until now
3. [receipt.zip](https://github.com/SQLiteFlow/SQLiteFlow-Issues/files/7767875/receipt.zip)
.

**Comment by SQLiteFlow** [comment]
Checked the receipt, can only see the "Free Trial" in-app purchase which is purchased at 2021-12-07, and there's no "Full App" in-app purchase in it, which means the purchase was not completed.

You can try purchase it again, and it's safe, if App Store recognize you purchased it, there's will be a promote from App Store says something like you purchased it, you don't need to pay it again.

And if the purchased is never made, then you can purchase it like normal.

**Comment by GalrionDev** [comment]
Ok. Thank you! :)

**Comment by SQLiteFlow** [comment]
You're welcome!
