### ISSUE TITLE
Free Trial

### ISSUE THREAD

**Issue by Toddwsmith** [SQLiteFlow/SQLiteFlow-Issues#190]
I downloaded the SQLiteFlow App and initiated the free trial on my iPad through my Apple account, but I do not see it listed under “Subscriptions” under settings. If an amount was already charged to my credit card, I’d like to cancel the account and get a refund. If I was subscribed, I’d like to cancel the free trial and free period. Thank you.

**Comment by SQLiteFlow** [comment]
Please see https://github.com/SQLiteFlow/SQLiteFlow-Issues/issues/170.
