### ISSUE TITLE
Updated Database

### ISSUE THREAD

**Issue by bingharsan** [SQLiteFlow/SQLiteFlow-Issues#193]
I used SQLite Flow  app on my iPohne & iPad Pro to Open / Edit / Update my Sqlite database on my iCloud. 
Unfortunately, my updates never get reflected on my iCloud database. What could be the reason for that?  Please help me out on this.

Regards,
Misfer Shamrani

**Comment by SQLiteFlow** [comment]
Sure.

1. Is your database in the local device get updated?

2. How you update your database? Through data editor or query editor?

3. How you check your database changes not get reflected on iCloud database?

4. Can other type of file's updates get reflected on your iCloud file, like SQL file?

5. Can this issue be reproduced by creating a new Sample database through SQLiteFlow -> + > New Sample Database?

**Comment by SQLiteFlow** [comment]
Could you attach a screenshot so I can know which pages are you on, and let you know what should do next to save changes.

**Comment by SQLiteFlow** [comment]
And please attach the screenshot through GitHub website not through the email you receive, or I can’t get it.

**Comment by bingharsan** [comment]
في سبت، 11 يونيو، 2022 في 12:02 ص، كتب SQLiteFlow ***@***.***

**Comment by SQLiteFlow** [comment]
Could you go to the Github website to enter your content? I can only see messy code from your previous post.

**Comment by SQLiteFlow** [comment]
```
Could you please tell me the mechanism SQLiteFlow Updates/Saves data to the
iClod Database.
```
Sure. It just run query to update SQLite database that on your device. There's nothing relate to _iCloud_.

```
My main issues about *SQLiteFlow are: *
*1. It does not update my Database, *
*2. I could not find any option to commit or save database changes. *
```
There's are many places or pages that SQLiteFlow could make changes to your database, like Data Editor, Query Editor, Import CSV, Alter Table, Rename Table, Delete Table, etc. There's a "Done" button in Data Editor that let you save changes, there's run query button let you run query to make changes to your database, and "Import" button in Import CSV let you import csv data to your database...
The save changes option should be obvious in each page, so which page are you on?

**Comment by SQLiteFlow** [comment]
Close for now caused by lack of response for a period of time.
This issue is welcome to reopen at anytime.
