### ISSUE TITLE
Price?

### ISSUE THREAD

**Issue by carbonmetrics** [SQLiteFlow/SQLiteFlow-Issues#197]
Hi, 
after downloading I saw that this is paid software.
I can't find the price anywhere on your website.
Before starting to evaluate software, I want to know what is cost.
So: what is the price of this software?
Many thanks, Henk

**Comment by SQLiteFlow** [comment]
What platform at you currently on, iOS or macOS?
And what can you currently see, could you add some description or attach a screenshot?

**Comment by SQLiteFlow** [comment]
Anyway, there's an "In-App Purchases" section in App Store's SQLiteFlow page, the price is there.

**Comment by carlsonorozco** [comment]
@SQLiteFlow price increased? I am planning to purchase it although the price changed before it was $9.99.

**Comment by SQLiteFlow** [comment]
@carlsonorozco 
The price on iOS and macOS are different, which platform are you on? 
And which country's currency are you mentioned?

**Comment by carlsonorozco** [comment]
I am using macOS and I live in the Philippines.

**Comment by SQLiteFlow** [comment]
@carlsonorozco  I see, on macOS, it's never been $9.99 USD recent days.
However, SQLiteFlow(macOS) had a limited time discount in Oct 12 - Oct 20, 
so what you saw may be this price.

If you prefer a discount price, we may offer a discount at Black Friday this year.
