### ISSUE TITLE
SQLite version for iOS app

### ISSUE THREAD

**Issue by somelinguist** [SQLiteFlow/SQLiteFlow-Issues#198]
Hi,

What’s the version of SQLite used in the current (5.8.3) iOS app? 

Thanks!

**Comment by somelinguist** [comment]
I figured it out by executing `select sqlite_version()` in the app, which reports 3.37.0 (at least on iPadOS 15.7).

Is there any possibility of updating to a more recent version, or is it tied to the system version?

I was hoping to use some of the new json features from 3.38.0 +.

Thanks!

**Comment by SQLiteFlow** [comment]
In iOS, SQLiteFlow uses the system embedded SQLite library, 
so the version of SQLite lib may vary from iOS version to version.

For example:
In iOS 15, the SQLite lib version is 3.37.0.
In iOS 16, the SQLite lib version is 3.39.0.

You can also run `SELECT sqlite_version()` to check which SQLite lib version that is currently being used by SQLiteFlow or iOS system.

**Comment by SQLiteFlow** [comment]
(Seems like we post the last comment at the same time, haha)

> Is there any possibility of updating to a more recent version, or is it tied to the system version?
> I was hoping to use some of the new json features from 3.38.0 +.

Yes, if you want SQLite 3.38.0+, then in iOS, you may need  run SQLiteFlow in iOS 16.

**Comment by somelinguist** [comment]
Thanks for the info! I’ll wait a few days for it on my iPad. :)
