### ISSUE TITLE
Unable to purchase

### ISSUE THREAD

**Issue by carlsonorozco** [SQLiteFlow/SQLiteFlow-Issues#199]
**Version**
 - Platform: macOS Ventura 13.0
 - SQLiteFlow: 5.8.5

**Steps to Reproduce**
Click Purchase Full App

**Expected behavior**
Able to proceed

**Screen shots**

<img width="464" alt="Screenshot 2022-10-28 at 21 54 59" src="https://user-images.githubusercontent.com/2333279/198630005-d5f504e9-7f03-4616-94ae-b2b405cf059c.png">

**Comment by SQLiteFlow** [comment]
Maybe it's a network issue or a glitch of the App Store.
Since when you click the "Purchase Full App" button, SQLiteFlow uses Apple's In-App Purchase SDK to connect App Store server.
Maybe you could try to restart you Mac then try again or check if other app's IAP function also has this error.

**Comment by SQLiteFlow** [comment]
And I tested with SQLiteFlow(macOS) 5.8.5 in macOS 13.0 just now, the purchase function work fine at my side.
Please let me know if the error still appears at your side, so maybe I could offer some help if I can.

**Comment by carlsonorozco** [comment]
Hi @SQLiteFlow, able to purchase now. Thanks.
