### ISSUE TITLE
table counts

### ISSUE THREAD

**Issue by scrooks** [SQLiteFlow/SQLiteFlow-Issues#2]
I would really love an option to show table row counts for all the tables when I open the database.  Maybe in parentheses after the table name on the left?  Even something like a "Count" button on the right to issue the SQL to get the row count would be okay (but not as good as automatically showing the number of rows for all tables).

**Comment by SQLiteFlow** [comment]
Thank you for the feature request @scrooks, and can I know that what you are suggesting is for the iOS version of SQLiteFlow or for the macOS version of SQLiteFlow?

**Comment by SQLiteFlow** [comment]
@scrooks I am considering this feature right now. What if this feature behave like that, can this satisfy your requirement?
1. Open a database, right click database name.
2. Then a context menu shows, and there's a new item 'Statistics' in context menu.
3. Click 'Statistics', a new tab will open, and the data (number of rows for all tables) you may want to see will in this tab, more like a report.

**Comment by SQLiteFlow** [comment]
@scrooks And additionally, in this 'Statistics' report, you can do almost everything for a table in database list like 'Select Rows', 'Alter Table', 'Drop Table' too of course.

**Comment by scrooks** [comment]
That would work okay.  Often I find that I just need to open a database so I can tell that it was created correctly based on row counts for the tables.  So the context menu option would work fine, it would just be an extra step.  I understand that it's not optimal to go out and get the row counts for all tables everytime a database is opened, so a compromise makes sense.

**Comment by SQLiteFlow** [comment]
@scrooks Okay, now I see your scenario. And to let the 'extra step' easier, I can make this happen: hit enter on database name or double click database name to open the 'Statistics' report. So the workflow could be either
1. Open a database then hit enter to view 'Statistics' report
or 2. Open a database then double click database name to view 'Statistics' report.

**Comment by scrooks** [comment]
That sounds great.

**Comment by SQLiteFlow** [comment]
@scrooks A new version of SQLiteFlow released with the initial version of 'Show Statistics' feature, and now you can get the update from the Mac App Store.

Here is a demo for 'Show Statistics' feature.
![Demo.gif](https://user-images.githubusercontent.com/38027540/43807159-c2e2a4de-9ad9-11e8-8da2-313ff98d3b76.gif)

Hope you like it. And if not, please tell me.

**Comment by scrooks** [comment]
I love it!  Fulfills my need just fine.  One small change I would make is to format the Records number so it's grouped according to the user's regional preference.  For example, instead of the hard to read "1322883" (is that one million?  13 million?  Let me carefully count the digits…), I'd like to see "1,322,883" (immediately obvious it's one million).

And even smaller improvement would be to automatically expand the "Table Name" column to fit the widest table name.  I have some longer names and they get cut off with the default width.

The statistics pane is a good solution, and I really like that I can just hit Enter to open it up quickly.

**Comment by SQLiteFlow** [comment]
@scrooks Thank you, I'm glad you like it. And for the two improvements, coming very soon.

**Comment by SQLiteFlow** [comment]
@scrooks A new version of SQLiteFlow released with the two improvements mentioned above.

**Comment by scrooks** [comment]
Looks terrific, thanks!

**Comment by SQLiteFlow** [comment]
@scrooks You are welcome.
