### ISSUE TITLE
CMD + RETURN to close text entry field

### ISSUE THREAD

**Issue by matthewjschultz** [SQLiteFlow/SQLiteFlow-Issues#200]
As a person who prefers to use the keyboard as much as possible, it'd be very useful to be able to close the text editor with CMD + RETURN.

**Comment by SQLiteFlow** [comment]
Assuming you are using macOS. 
Have you aware that there's already a hotkey to close a window which is  CMD+W?

**Comment by SQLiteFlow** [comment]
If "close the text editor" means close the query editor window of course.

**Comment by SQLiteFlow** [comment]
Close for now caused by lack of response for a period of time.

The issue is welcome to reopen at anytime of course.
