### ISSUE TITLE
Trigger Using 23 Updates for Quick LookUp Runs too Slowly when Database has Too Many Records

### ISSUE THREAD

**Issue by fmenkin** [SQLiteFlow/SQLiteFlow-Issues#201]
**Version**
 - Platform: [e.g. macOS 13.0]
 - SQLiteFlow: [e.g. 5.8.0]

My Category field can be filled in correctly during entry by entering part of the name of the item I need to fill-in.
For most of the year, the trigger has run quickly enough.  Now that there are over 1000 records in my Journal DB, it is taking about 30 seconds for the lookup!

Perhaps building an Expression to execute on-the-fly would be the best solution, if it can be done. Or is there a better way to speed-up the lookup?

![Screen Shot 2022-12-16 at 1 49 19 PM](https://user-images.githubusercontent.com/59176186/208168322-1467b4c6-4150-4fd8-b713-10292551611e.png)

Thanks,
Frank Menkin

**Comment by SQLiteFlow** [comment]
When you say "Quick LookUp", what do you mean specifically? Any steps?

**Comment by SQLiteFlow** [comment]
Close for now. This issue is welcome to open again.

**Comment by fmenkin** [comment]
My quick entry approach (that unfortunately runs slower as the database grows) is to use a trigger that triggers when the first characters of the entry match one of the steps in the trigger. (For example, enter “con”in the Category field, then press Enter twice, and the trigger will pop up “Contribution” as your entry (assuring database consistency in entries).    
 I assume that you made a change in your code that sped things up significantly, for I noticed an improvement in speed.     
 Thanks so much,
  
Frank Menkin
  

  
  

  
  
>

**Comment by SQLiteFlow** [comment]
Does it also slow when you execute an update SQL in Query Editor like 
`UPDATE Journal SET Category = 'Con' WHERE XXXID = xxx;`?

**Comment by fmenkin** [comment]
(https://github.com/SQLiteFlow/SQLiteFlow-Issues/issues/201#issuecomment-1402294630)SQLiteFlow (https://github.com/SQLiteFlow)   commented   3 hours ago (https://github.com/SQLiteFlow/SQLiteFlow-Issues/issues/201#issuecomment-1402294630)
  
  
  
  
  
  
  
  

 Does it also slow when you execute an update SQL in Query Editor like
   UPDATE Journal SET Category = 'Con' WHERE XXXID = xxx;?

  

  

  

 It does not slow when the suggested updating in Query Editor is run. It is evidently related to the trigger.   

  

 (I think it is possibly calls exiting to the OS during the Trigger execution.)

  
  
  
  
  
  
  
  
 Frank Menkin’s Email
  
  
  

  
  
>

**Comment by SQLiteFlow** [comment]
1. Okay, I see. Then it will slow when you execute an insert SQL in Query Editor like
`INSERT INTO Journal (xxx1, xxx2, xxx3, Category) VALUES('xx', 'xx', 'xx', 'Con');`
right?

2. 

> I think it is possibly calls exiting to the OS during the Trigger execution.

You mean app crash?

**Comment by fmenkin** [comment]
1. The on-insert or on-update trigger will check an entry against all possibilities listed in the trigger looking for the one that fits and using it if found.   
 2. No app crashes are involved. Depending on the program and/or operations used, individual steps in a procedure or program may invisibly exit the code to let the operating system    perform necessary operations and then invisibly return to executing the code. This can cause significant delays under some circumstances.  

  
Currently, I have started a new database for a new year and have instant response to my triggers because the Journal table will have few entries in it to burden operations.   
  

  
I am happy enough with the response time.   
  

  
Thanks for whatever improvement comes easily as time goes on,
  
Frank Menkin
  

  
  
 Frank Menkin’s Email
  
  
  

  
  
>

**Comment by SQLiteFlow** [comment]
I think the trigger you write can be improved easily to handle inserting at microseconds level even if your database contains millions of records.
For references, please check https://www.sqlite.org/lang_createtrigger.html#some_example_triggers, in section 4. Some Example Triggers, search 

> new.

**Comment by fmenkin** [comment]
I may be missing something but I don’t see how this addresses my need to use partial entries (the beginning of the searched for Category name) and have the searched for Category appear. I don’t see how the reference shown indicates how a partial entry will be replaced programmatically by the sought for Category name.   
  
Please enlighten me.   
  
Thanks,
  
Frank Menkin
  
  
  
 Frank Menkin’s Email
  
  
  

  
  
>

**Comment by SQLiteFlow** [comment]
Sure. Though it's now my job but I'm happy to assist you.
Here's an example.

```
CREATE TRIGGER YourTrigger AFTER INSERT ON Journal
BEGIN

UPDATE Journal
SET
    Name = CASE
               WHEN new.Category LIKE 'B%'
               THEN 'DBN'
               WHEN new.Category = 'CE%'
               THEN 'Cell Phones'
               ELSE Category
           END
WHERE YourJournalID = new.YourJournalID
;

END
```
