### ISSUE TITLE
Help on how to import a CSV file and save the database

### ISSUE THREAD

**Issue by sjoob** [SQLiteFlow/SQLiteFlow-Issues#202]
Hi SQLite:

I am new in database and in SQLite that I just bought.

I am trying to create a simple database  containing 1 table which is created by importing a CSV file.

From the menu "Tools" I managed to import the CSV file. The table is shown in SQLite right away.

My problem is: I cannot save the database: the items "Save" and "Save as" under the menu "File" are grayed all the time.

Could you please add to the documentation a few line for beginners on how to create and save a simple database from a CSV file?

Thanks in advance!

Best regards!

**Comment by SQLiteFlow** [comment]
When you finish import your CSV data to SQLite database, the data is already in your database, that is it's already be saved.

The "Save" menu item and "Save as" menu item in "File" menu is there for SQL File, not SQLite database.

**Comment by sjoob** [comment]
Thanks a lot for this answer!

**Comment by SQLiteFlow** [comment]
You're welcome.
