### ISSUE TITLE
Dark mode broken for BLOB data view

### ISSUE THREAD

**Issue by ReagentX** [SQLiteFlow/SQLiteFlow-Issues#203]
**Version**
 - macOS 13.1 (22C65)
 - SQLiteFlow 5.9.0

**Steps to Reproduce**
Open a blob data column

**Expected behavior**
The popover window displays in dark mode

**Screen shots**
The popover window displays in light mode (except for line numbers, which become invisible):

<img width="675" alt="image" src="https://user-images.githubusercontent.com/1920666/211261501-cdaef174-f2d2-4d78-8a0f-40f11229f575.png">

**Comment by SQLiteFlow** [comment]
Thank you for the report, will fix it.

**Comment by SQLiteFlow** [comment]
This issue has been fixed.
SQLiteFlow(macOS) 5.9.1 is available on App Store now.

**Comment by ReagentX** [comment]
Yep, looks good! 

<img width="493" alt="image" src="https://user-images.githubusercontent.com/1920666/211423294-26fea08a-85f4-47f1-b57c-5be004118e34.png">
