### ISSUE TITLE
Support for Shift-Tab and tabbing multiple selected lines

### ISSUE THREAD

**Issue by rhult** [SQLiteFlow/SQLiteFlow-Issues#206]
**Version**
 - Platform: macOS 13.2.1
 - SQLiteFlow: 5.9.3

The query editor would be even better if it had those two features, matching many other editors:

- Shift-Tab (removing a tab if there is one under the cursor)
- Selecting multiple rows and pressing Tab or Shift-Tab works on all selected lines

**Comment by SQLiteFlow** [comment]
`Shift-Tab (removing a tab if there is one under the cursor)`
`Selecting multiple rows and pressing Tab or Shift-Tab works on all selected lines`

I tried these two in Xcode, when you say inserting or removing tab, you mean inserting or removing the prefix tab, right?

**Comment by rhult** [comment]
Yes, exactly, the prefix tab (for changing the indentation).

**Comment by SQLiteFlow** [comment]
Accept.

**Comment by SQLiteFlow** [comment]
SQLiteFlow(macOS) 5.9.8 has been released.
It contains these two features now. 
Please let me know if you experience any issues.

**Comment by rhult** [comment]
I've tested it and it seems to work as expected. Thanks!

**Comment by SQLiteFlow** [comment]
You're welcome!
