### ISSUE TITLE
Is there a manual or videos to help me use the features of your awesome software?

### ISSUE THREAD

**Issue by 2b1ask1** [SQLiteFlow/SQLiteFlow-Issues#207]
**Version**
 - Platform: [e.g. macOS 13.0]
 - SQLiteFlow: [e.g. 5.8.0]

For example, I want to edit table data - no idea how to do that without using SQL commands.

I assumed your software lets me do this.

Because on the iOS version (which I also purchased), I simply click the table and I can edit directly in the cell.

**Comment by SQLiteFlow** [comment]
> I simply click the table and I can edit directly in the cell.

You can also do that in macOS of course. 
What happened when you tried do this in macOS?

**Comment by 2b1ask1** [comment]
I appreciate the fast response.

When I click on fields, I get field information... not data.

Here's a screenshot:
<img width="1226" alt="SCR-20230223-b5f" src="https://user-images.githubusercontent.com/25638532/220913977-c73a67f9-c758-4576-8cdd-969c25fdef60.png">

I click the various tabs - I can't see any data.

(I know I'm probably doing something stupid:>)

**Comment by SQLiteFlow** [comment]
What you're seeing is Table Schema.

To view/edit table's data, you can double click a table name to open the Data Editor.

Screenshot attached.

<img width="1226" alt="220913977-c73a67f9-c758-4576-8cdd-969c25fdef60" src="https://user-images.githubusercontent.com/38027540/220916755-b99ae472-5cac-4e5b-9792-1f7f24cd3fc6.png">

**Comment by 2b1ask1** [comment]
Ah ha!

This is why I was looking for a manual... didn't want to bother you with such silly questions.

Thank you for the super fast response.

And thank you for making software that doesn't look like shitty Windows :>

One last question... how do we check for updates on the Mac version (I purchased both Mac and iOS... I know to UPDATE on iOS... will an update notice show up in the Mac App Store?)

**Comment by SQLiteFlow** [comment]
I'm in a point of view that if an app's UI is intuitive enough, the app itself is a user manual.
And I was think double clicking a table name to view table's data is quite straightforward.
Anyway, you're always welcome to ask.

> how do we check for updates on the Mac version

Screenshot attached.
To check if there're any app updates,
1. Open App Store - Updates section
2. Menu - Reload Page
<img width="1431" alt="1" src="https://user-images.githubusercontent.com/38027540/220923059-5a2194ff-7dd9-4bd9-98f5-8786910c24d7.png">

**Comment by 2b1ask1** [comment]
Once again, I super appreciate your fast reply - this is why I LOVE SUPPORTING independent devs (instead of BIG corps).

Onward...

FYI: I'm a VERY good front-end developer and new to backend coding.

I agree with having a great UI/UX doubling as a manual. I'm with you on that.

I never give advice (instead I give personal experiences)... with the web software I develop, I use tooltips on everything... so when my visitors hover over an icon, it pops open a speech bubble. I tried that with your software but didn't see that offered.

I have 2 remaining questions:

1) Can I add a field to a table using your software (or do I need to do it using SQL query)?

2) Is there an option to auto increment by 11 instead of 1?


UPDATE: I just updated your software, and now the tooltips are working!

**Comment by SQLiteFlow** [comment]
> I use tooltips on everything...

Thank you for your supporting. Maybe I should add more tooltips too.

> Can I add a field to a table using your software (or do I need to do it using SQL commands?

In table schema, click the "+" button to add a table field.
Then click "Apply" button to open a Query Editor popup to save changes.
<img width="1226" alt="220913977-c73a67f9-c758-4576-8cdd-969c25fdef60" src="https://user-images.githubusercontent.com/38027540/220928372-2d2ef110-0d6a-482d-8b6c-e92e0d7ee7e4.png">

> Is there an option to auto increment by 11 instead of 1?

I'm not quite understand the question. Do you mean when you add a record, an auto increment field can be auto filled with a value that incremented by 11 by SQLite?
Hmm, I don't think there's a straightforward approach (in my knowledge). You can go to https://sqlite.org/forum/forum to ask a SQLite specific question, there're more professional people here to discuss that kind of questions.

**Comment by 2b1ask1** [comment]
Yes... to further secure table data, I thought increasing the id by 11 vs. 1 would be more secure.

I understand this is the SQL:
ALTER TABLE users AUTO_INCREMENT = 11;

Maybe I'm overthinking things.

And cool... I see I can add a new database or table with the +. Excellent.

However, I got this error trying to add a `test` field:

<img width="1201" alt="SCR-20230223-czy" src="https://user-images.githubusercontent.com/25638532/220934399-5f94d30f-1d2f-4c02-bfac-9e3d509737c4.png">

**Comment by SQLiteFlow** [comment]
Give the `test` field a default value if you want to make the new adding column NOT NULL.
<img width="1226" alt="220913977-c73a67f9-c758-4576-8cdd-969c25fdef60" src="https://user-images.githubusercontent.com/38027540/220936005-f417c7ab-604a-4e6e-867f-82036a9d0c20.png">

**Comment by 2b1ask1** [comment]
Cool. That worked. Thank you.

Back to the autoincrement by 11...

I just found out this SQL command does the trick:
ALTER TABLE users AUTO_INCREMENT = 11;

Is there any way to build this into your software as a future feature (I hate using SQL commands... it's not intuitive.)

**Comment by SQLiteFlow** [comment]
`ALTER TABLE users AUTO_INCREMENT = 11;`

I think that's a MySQL command, does SQLite support it too?

**Comment by 2b1ask1** [comment]
Ah, great point. It's not supported in SQLite it seems. (At least that's what ChatGPT Plus said :>)

Super appreciate all your help today!

**Comment by SQLiteFlow** [comment]
You're welcome.
