### ISSUE TITLE
Select which database to run query against

### ISSUE THREAD

**Issue by pontusntengnas** [SQLiteFlow/SQLiteFlow-Issues#208]
**Version**
 - Platform: 13.0.1
 - SQLiteFlow: 5.9.8

Hi,

First off, thanks for an amazing product, really does its thing perfectly.

One thing that I have been missing recently is the possibility to select which database to run a query against when I am connected to more than one. Now I have to open a new tab that is targeting each db, or am I missing something? 

I believe Azure Data studio is having something similar to this functionality using a dropdown where you can select database.

Regards,
Pontus

**Comment by SQLiteFlow** [comment]
You're right, this is feature is missing in SQLiteFlow.
And I will implement it.

**Comment by SQLiteFlow** [comment]
SQLiteFlow(macOS) 5.9.9 has been released, and it available on App Store now.
In query editor, it supports select the database the run query against now.

Please let me know if you experience any problems.

<img width="1026" alt="1" src="https://user-images.githubusercontent.com/38027540/222380895-1df8890d-5484-4d84-aa8c-31d337f4d55c.png">

**Comment by pontusntengnas** [comment]
Works perfectly, thank you for such a swift response!

**Comment by SQLiteFlow** [comment]
You're welcome!
