### ISSUE TITLE
General Q's: open source, extensibility, primary source language, how did you make it so portable (etc)?

### ISSUE THREAD

**Issue by johnnyutahh** [SQLiteFlow/SQLiteFlow-Issues#211]
SQLiteFlow looks impressive. I learned of it because https://github.com/ReagentX/imessage-exporter developer(s) used it to reverse-engineer macOS iMessage database... which seems quite impressive.

General questions before I explore further:

1. is it open-sourced?  (https://github.com/SQLiteFlow/sqliteflow.github.io reads "SQLite Editor for Mac & iOS"...but it looks more like a website source)
2. how "extensible" is it (plugins if that's meaningful, pull requests, etc)? totally fine if it's not, I'm not expecting/needing anything here, just curious.
3. primary source language/environment/context: I'm interested in part because my team seeks to create additional, future projects which have excellent macOS-and-iPadOS(?)/iOS portability. Do you single-source this software base across these platforms?

Thanks for any help with above, and thank you for creating what seems to be such a great product.

**Comment by SQLiteFlow** [comment]
It's a closed source project developed with Xcode and using Swift. Different code bases for different platforms. 
No plugin supported yet.

**Comment by johnnyutahh** [comment]
Got it, thanks. Helpful. [closing this issue]
