### ISSUE TITLE
Diff by primary key

### ISSUE THREAD

**Issue by pontusntengnas** [SQLiteFlow/SQLiteFlow-Issues#212]
**Version**
 - Platform: macOS 13.0.1
 - SQLiteFlow: 6.0.1

Hi,

I would like to be able to do the database diff by Primary key instead of by rowid. This is possible in the sqldiff tool today (which I suppose is used), see argument `--primarykey`.

https://www.sqlite.org/sqldiff.html

Would be awesome to have a checkbox for this.

Thanks again for a great product!

**Comment by SQLiteFlow** [comment]
Accepted.

**Comment by SQLiteFlow** [comment]
This feature has been implemented in SQLiteFlow(macOS) 6.0.2, and it's available on App Store now.
Please let me know if you see any issues.

**Comment by pontusntengnas** [comment]
Works great! The message feature is also nice and it looks like multi-query support got better as well :D
