### ISSUE TITLE
what is the price after 2 week trial?

### ISSUE THREAD

**Issue by qb-00** [SQLiteFlow/SQLiteFlow-Issues#213]
**Version**
 - Platform: [e.g. macOS 13.0]
 - SQLiteFlow: [e.g. 5.8.0]

**Comment by SQLiteFlow** [comment]
No charges.

**Comment by qb-00** [comment]
the full app price is free?

**Comment by SQLiteFlow** [comment]
> the full app price is free?

No, the full app is not free. 

After the trial, there's no automatically subsequent charges.

After the trial, the app can no longer be used unless you purchase the "Full App" life time license.

**Comment by SQLiteFlow** [comment]
And the price of the "Full App" displays both in the app and App Store's "In-App Purchase" section.
