### ISSUE TITLE
Is there a whole example to use the shortcut of "Run Query" ?

### ISSUE THREAD

**Issue by satchelwu** [SQLiteFlow/SQLiteFlow-Issues#214]
**Version**
 - Platform: [e.g. ios 16.3.1]
 - SQLiteFlow: [e.g. 6.0.0]

I tried many times, but always got the error: 

Conversion Error
Run Query failed because Shortcuts couldn't convert from Folder to Intent Folder

Thanks

**Comment by SQLiteFlow** [comment]
Can I get a screenshot?

**Comment by satchelwu** [comment]
![image](https://github.com/SQLiteFlow/SQLiteFlow-Issues/assets/6259509/a0ea5fda-3c60-48e9-9cf6-fb4085ab311d)

**Comment by satchelwu** [comment]
![image](https://github.com/SQLiteFlow/SQLiteFlow-Issues/assets/6259509/2fbe8189-59bb-453e-8ccf-019232cb0a66)

**Comment by SQLiteFlow** [comment]
I see. I attached a video. 
Try choose the folder and database directly in the Run Query action, not by passing a variable to it.

https://github.com/SQLiteFlow/SQLiteFlow-Issues/assets/38027540/9d55ec2b-85c5-4b8a-aaca-a22840188dbe

**Comment by satchelwu** [comment]
got it ，thanks very much

**Comment by SQLiteFlow** [comment]
You're welcome.
