### ISSUE TITLE
Check for concurrent updates

### ISSUE THREAD

**Issue by petsva** [SQLiteFlow/SQLiteFlow-Issues#216]
**Version**
 - Platform: macOS 13.4.1
 - SQLiteFlow: 6.0.3

I tested to edit the same file stored on Icloud concurrently via Mac and Iphone and found that some simultaneous changes of the same row could be lost. I didn't expect anything else, given the principles of Sqlite. But maybe there are fairly simple ways to warn the user about it – lock file, check file stamps, read-only for second opener or others?

**Comment by SQLiteFlow** [comment]
**The caution that operate SQLite files which are able to sync to cloud:**

There's potential risk that the version of SQLite main database file and temp journal file mismatch during syncing to cloud process when operate SQLite database. **So be careful (or don't) access a SQLite database simultaneously on Mac and iPhone.**

Unfortunately, based on the fact that even if the SQLite main database file and temp journal file mismatch, they are all legal file to SQLite library, there seems no way to detect if SQLite main database file and temp journal file mismatch, the two files are just separate independent pieces.

So what you mentioned 

> lock file, check file stamps, read-only for second opener or others

They will just not work in this situation or there're no APIs for this situation.

**Comment by petsva** [comment]
Interesting, thanks for the warning. What would a mismatch lead to? How can it be reset/fixed?

I suppose you mean that the Sqlite library doesn't have support for this. And that the implementation doesn't allow Sqliteflow to interfere with that?

Checked https://www.sqlite.org/c3ref/funclist.html now – not possible via sqlite3_preupdate_hook?

Then one way to help conscious Sqliteflow users to avoid this problem could be to provide the option to open the database connection read-only.

**Comment by SQLiteFlow** [comment]
You can get a better sense about what I mean by having a look at this link.
https://www.sqlite.org/howtocorrupt.html

As a developer using SQLite, and maybe also a developer using SQLiteFlow or some other SQLite tools, she/he needs to know exactly what she/he is doing when access SQLite database in cloud disk. If you access it not simultaneously, in most of time it works. But if you access it simultaneously, you're corrupting your database.

**Comment by petsva** [comment]
Okay, now I get it better. The reason I didn't get any error was probably that I didn't write to the db concurrently. But I made changes to the same cell with seconds between, and hence the latest change was the result, maybe causing data confusion but nor necessary db corruption. But I see the problem. (There maybe should be a way to lock the file during a whole connection, not just when writing?)

But, if the network stored db is opened read-only by all but one of all possibly concurrent users, there shouldn't be any problem, I suppose.

**Comment by petsva** [comment]
(Sorry, mistake.)

**Comment by SQLiteFlow** [comment]
>But, if the network stored db is opened read-only by all but one of all possibly concurrent users, there shouldn't be any problem, I suppose.

Garbage data can be read by a reader, or if a reader delete a journal file(by SQLite lib automatically with some reason), etc, there will have problems.

SQLite itself is just not designed for that situation, it was designed to be a offline embedded database engine, so just don't use it like that if you're building a App that needs to sync database.

If you need to sync database in your App, you should consider another level of abstraction, such as CoreData https://developer.apple.com/documentation/coredata or SwiftData https://developer.apple.com/documentation/swiftdata, etc.
