### ISSUE TITLE
Allow smaller window width without hiding the left sidebar on macOS

### ISSUE THREAD

**Issue by somelinguist** [SQLiteFlow/SQLiteFlow-Issues#218]
**Version**
 - Platform: macOS 13.5.2
 - SQLiteFlow: 6.0.6

Hi. On macOS, it looks like the left sidebar is set to automatically hide if the width of the window is adjusted below a certain size. Would it be possible to disable this?

For context: I was trying to have an SQLiteFlow window adjusted to half of the width of the display of my 16in MacBook Pro. However, the sidebar automatically hides when the SQLiteFlow is slightly wider than half of the display. I would like to be able to see the sidebar with a smaller window.

Thanks for this great app!

**Comment by SQLiteFlow** [comment]
I will take a try.

**Comment by SQLiteFlow** [comment]
A new version of SQLiteFlow(macOS) (6.0.7) has been released.
A window now will have a min window size base on the window's content to prevent the sidebar from auto hiding. 
Please check whether the new behavior of window's sidebar fits your need.

**Comment by somelinguist** [comment]
Thanks! That works great. It makes it much easier to work with multiple windows/apps. Thanks again!

**Comment by SQLiteFlow** [comment]
You're welcome.
