### ISSUE TITLE
Import JSON/ascii

### ISSUE THREAD

**Issue by benyn** [SQLiteFlow/SQLiteFlow-Issues#219]
**Version**
 - Platform: [e.g. macOS 13.0]
 - SQLiteFlow: [e.g. 5.8.0]

It'd be great to be able to import files as just an ASCII, like you'd do with the [`sqlite3` command line tool](https://sqlite.org/cli.html#importing_files_as_csv_or_other_formats) as in `sqlite3 "$db_path" .import --ascii "$json_file"`. This'd be very useful when using Shortcuts, after you've downloaded some data via an API call.

At the minimum, it'd be helpful to suppress dequoting and import the content of a file as TEXT. I tried to import a JSON as if it was a single-cell CSV, but it works only if the JSON content doesn't have any characters set as the delimiter. More critically, even if the content is successfully imported into a single-column record, the imported text is stripped off of double quotes, and is no longer a valid JSON.

**Comment by SQLiteFlow** [comment]
So your final goal is to import a arbitrary text to one table's cell (or one field) right?

**Comment by benyn** [comment]
> So your final goal is to import a arbitrary text to one table's cell (or one field) right?

Pretty much.

It'd be convenient to be able to apply a JSON_EACH on the imported text, but if we're replicating what `sqlite3` does, importing text without dequoting seems to be what the `--ascii` flag does.

**Comment by SQLiteFlow** [comment]
Wait, I am a little confused. You want eventually import one column one row, or one column multiple rows?
Could you offer an example?

**Comment by benyn** [comment]
Either works for me.

With `sqlite3`, I often import a JSON containing an array into a single cell (single row, single column) of a temporary table, then I'd apply a `JSON_EACH` on that column to access elements of the imported array, and put them in main tables. Thought it'd be nice to have that `JSON_EACH` baked into the Shortcuts action, especially because we can't use temporary tables via Shortcuts (or can we?). If a `JSON_EACH` option is baked in, the resulting table would have multiple columns and multiple rows, since `JSON_EACH` creates multiple columns such as `value`, `key`, etc. But that's certainly a nice-to-have convenience feature, which may not need to be supported directly by SQLiteFlow.

**Comment by SQLiteFlow** [comment]
Of course SQLiteFlow supports it!

Have you forget there's another Shortcut action offered by SQLiteFlow which is "Run Query", so you can do basically whatever you want with this action.

A demo screenshot attached to show how to implement SELECT * FROM json_each() using Shortcut actions.


<img width="862" alt="1" src="https://github.com/SQLiteFlow/SQLiteFlow-Issues/assets/38027540/34cba46d-c246-40a6-9d25-33328058d2cf">

**Comment by benyn** [comment]
Thanks! The Run Query action works for me. I was curious if the Shortcuts Text action would truncate a large text, but it worked with a 4.5 MB JSON file.

It might still be worth considering a no-delimiter option for the Import CSV action for very large files, but I could work with the Run Query action.

**Comment by SQLiteFlow** [comment]
You’re welcome.

> It might still be worth considering a no-delimiter option for the Import CSV action for very large files, but I could work with the Run Query action.

Good to hear that the Run Query action solution work for you.

Importing CSV with no-delimiter sounds a weird behavior to me, since it’s equivalent to run a query like `INSERT INTO MyTable(Col1) VALUES('a piece of plain text')`.

**Comment by SQLiteFlow** [comment]
SQLiteFlow(macOS, iOS) 6.2.0 now supports import JSON to a table shortcut action.

The supported format is an array of objects where each object contains a value for every column name. Here’s an example with two columns “id” and “name”:
```
[{"id": 1, "name": "A"},
{"id": 2, "name": "B"}]
```

I'm not sure if this could let you remove the json_each steps in your importing routine.

If this can simplifier your development  process, you can feel free to use it.
