### ISSUE TITLE
Sending a database from an OS10 MacBook to an iOS12 iPhone 

### ISSUE THREAD

**Issue by Dionysu** [SQLiteFlow/SQLiteFlow-Issues#22]
I have a SQLiteFlow on my Macbook (OS10) which I want to send to my iOSFlow (iOS12).  I opened both apps and entered the appropriate address only to be faced with a window asking me to pick a database, but there was no database available to pick.

**Comment by SQLiteFlow** [comment]
@Dionysu 
Well, to send a database from macOS to iOS, the easiest way is using AirDrop. 
Use iTunes File Sharing or iCould Drive to send databases from macOS to iOS are also supported.

I think what you are using is the 'Open Remote' feature on SQLiteFlow(macOS), this feature is designed for opening remote databases that already existed in SQLiteFlow(iOS). The iOS side behave like a SQLite Server, the macOS side behave like a control center, the iOS side receive commands like SQL, then send specific data like query result back to macOS side.
An example use case is, previously if iOS developers want to debug query performance issue on iOS, they may have to change their code and run their app on an iOS device again and again. Now they can send a database to SQLiteFlow(iOS), and use SQLiteFlow(macOS) to debug the query performance issue if they like.

**Comment by Dionysu** [comment]
Thank you for your quick answer to my question.  I suppose there is no way to affect both DBs from a single entry in an iOS or OS device.  If I store a DD in iCloud, how do I bring it to the attention of the iOS app. Also:  How do I move a DD to an iOS device so that it is useable by the iOS SQLiteFlow app there?

Dionysu

**Comment by Dionysu** [comment]
Answered!  Thanks again for the help
