### ISSUE TITLE
iOS 17 simulator support

### ISSUE THREAD

**Issue by ogrodnek** [SQLiteFlow/SQLiteFlow-Issues#220]
Love the app! The access simulator feature has been great, but it doesn't seem like it's been updated to show simulators for ios17?  Would be great to have that.

thanks!

**Version**
 - Platform: 13.6
 - SQLiteFlow: 6.0.9

**Comment by SQLiteFlow** [comment]
Thank you for loving the app.

I'm on macOS Sonoma 14.0, Xcode 15.0.1, and it looks to show simulators for iOS 17.0 fine at my side. A screenshot attached.

What's your side displaying?

![Untitled](https://github.com/SQLiteFlow/SQLiteFlow-Issues/assets/38027540/b3b1144d-e7d2-45fe-a0bf-11f689bcacc2)

**Comment by ogrodnek** [comment]
Thanks for looking into this.

I only see:

![Screenshot 2023-10-20 at 10 48 31 AM](https://github.com/SQLiteFlow/SQLiteFlow-Issues/assets/17552/30eb45b1-f0a0-4cfa-83fd-d5be1c93b470)

And I do have the simulator running w/ 17.0

![Screenshot 2023-10-20 at 10 49 11 AM](https://github.com/SQLiteFlow/SQLiteFlow-Issues/assets/17552/b1aaae36-a3ee-4894-810e-f0a620a4790c)

I am on Ventura (13.6), XCode Version 15.0.1 (15A507)

**Comment by SQLiteFlow** [comment]
I added a iPhone 14 Pro (iOS 17.0) simulator, and this issue has been reproduced.
I will find a way to fix it.

Before I release a fix, a workaround is to use simulators listed below to run iOS 17 simulator:

![1](https://github.com/SQLiteFlow/SQLiteFlow-Issues/assets/38027540/ffe31029-9b63-4f72-8949-f1a6061e8442)

**Comment by ogrodnek** [comment]
Thanks! Yes, I hadn't tried the 15 yet, but it does work for that simulator.  Thanks!

**Comment by SQLiteFlow** [comment]
You're welcome, thank you for the bug report.

**Comment by SQLiteFlow** [comment]
SQLiteFlow(macOS) 6.2.0 has been released. This bug has been fixed.
