### ISSUE TITLE
Request for more English-language shortcuts

### ISSUE THREAD

**Issue by Jason-Abbott** [SQLiteFlow/SQLiteFlow-Issues#221]
Hi. This is a follow-up to my Apple Store comment.

I really appreciate the attention to detail in the application. I’m using it every day for a project right now.

One thing that would make it a little quicker for me is a keyboard shortcut (binding) on some things. For example, several screens let you add a new item with a plus icon:

<img width="202" alt="image" src="https://github.com/SQLiteFlow/SQLiteFlow-Issues/assets/6289308/bce549ec-a151-4621-85c5-4100d35ebf2a">

It would be great if, instead of needing to click the icon, I could press, for example, the Ctrl (control) key together with the plus (+) key to add a new row, foreign key, constraint or whatever is on the screen.

(I suggested Ctrl-+ only as an example. I don’t really care what the shortcut or binding is.)

If you feel very motivated, you could make a shortcut customizer like in XCode, but I don’t think that’s necessary 🙂

<img width="585" alt="image" src="https://github.com/SQLiteFlow/SQLiteFlow-Issues/assets/6289308/f33af573-f16a-4688-a7ac-127e173b2b46">

**Comment by SQLiteFlow** [comment]
Okay I get it.
1. In Database List, supports Option-Double Click a table name/view name or Option-Return a table name/view name to open Table Schema/Alter View.
2. In Table Schema, give the '+' and '-' button a hotkey, possibly Ctrl-+ and Ctrl--.

> If you feel very motivated ...

I do feel actually, maybe in some future version of SQLiteFlow I will implement it.

And any other hotkeys you prefer to add to a near future version of SQLiteFlow?

**Comment by SQLiteFlow** [comment]
Status update:

I reviewed the whole app where the "-" and "+" buttons could appears, these are the hotkeys that I currently preferred.

For where the "-" remove button could appears:
Data Editor, Statistics, Table Schema, Font and Color Settings, Load Extension Settings, 
they can use the same hotkey: ⌫ (Delete).

For where the "+" add button could appears:
Data Editor, Statistics, Table Schema, Font and Color Settings, Load Extension Settings, 
they can use the same hotkey: ⇧⌘N (Same as the hotkey that used to create a new folder in macOS Finder).

**Comment by SQLiteFlow** [comment]
SQLiteFlow(macOS) 6.2.0 has been released. These feature have been implemented.
