### ISSUE TITLE
Export Type "Plain Text" for Run Query Shortcuts action

### ISSUE THREAD

**Issue by benyn** [SQLiteFlow/SQLiteFlow-Issues#222]
**Version**
 - Platform: iOS 17.1
 - SQLiteFlow: 6.1.0

In the Export Type dropdown of the Run Query Shortcuts action, I see three options now. Can a "Plain Text" be added?

All three existing options present challenges for queries returning `JSON_GROUP_OBJECT()` aggregation function results:
- **CSV** escapes every double quote in the text, requiring a post-query de-escaping.
- **JSON** buries results in a JSON array of JSON objects, making it hard to access the actual results in Shortcuts.
- **MarkDown** wraps the result in a Markdown table.

A **Plain Text** option that escapes or adds nothing to the resulting text would be nice.

**Comment by SQLiteFlow** [comment]
> JSON buries results in a JSON array of JSON objects, making it hard to access the actual results in Shortcuts.

Looks like you want to handle a query result (which itself is in JSON format) subsequently in the Shortcuts app. 

Actually the Shortcuts app is fully capable to handle JSON text now. So you can benefit it to get the "Plain Text" you mentioned.

I attach two screenshots to demonstrate it, combining with the query result of `JSON_GROUP_OBJECT()`, and the "Plain Text" you expected is outputted.

Can this satisfy your needs?

<img src="https://github.com/SQLiteFlow/SQLiteFlow-Issues/assets/38027540/e101706e-ec6a-415a-b91c-f528356aecea" width="320">
<img src="https://github.com/SQLiteFlow/SQLiteFlow-Issues/assets/38027540/0248daf4-2eeb-48e7-863b-b4805984d5a4" width="320">

**Comment by benyn** [comment]
I'm familiar with Shortcuts' JSON capabilities as I use them extensively.

SQLiteFlow's JSON export type buries results in a JSON array of JSON objects. In your example, you'd first have to get the `MyName` value before you're able to access `StudentID` and `FirstName` values. If you were using `sqlite3`, which defaults to the `list` mode, which what I called the Plain Text mode in my original post, you wouldn't have to go through that unnecessary step.

It's not the end of the world but it'd be much easier if SQLiteFlow just provided plain text output. Given SQLiteFlow is not a universal app, I find myself having to use conditionals based on the OS like below, and it gets tiring to post-process the output -- be it a Get Value from Dictionary action like in your example or de-escaping in my screenshot below. Is it difficult to implement?
![escaping](https://github.com/SQLiteFlow/SQLiteFlow-Issues/assets/105991837/7c51ba59-6e76-49f5-8e64-4b2a7b62c8d6)

**Comment by SQLiteFlow** [comment]
My previous post is based on the plain text mode you described in your original post.

I was thinking if I'm going to add feature to SQLiteFlow, I need to have a sense that it has a little broader use case.

In your original post, the plain text mode looks only suitable for the query result that has only one row and one column, for example, if there're two columns of result, then the two columns would be merged together. 
This is why I offered an alternate solution to ask you if it could fulfill your needs, to avoid implement a feature arbitrary that not have a broader use case.

The `sqlite3` terminal example you mentioned above is better, looks like it has a separator `|` between columns. But if a content of a cell also has a `|` character, then two columns may become three columns from the post process's view.

I understand that your query result only contains one row and one column, the `sqlite3`'s list mode would just works great for you. But the mode still has a chance that may let the post process get a unstable or a wrong answer, this behavior bugs me from implementing it.

And I believe the export format of the `sqlite3`'s list mode is not design for post data processing at all, it is just happen to fit your needs.

I'm currently in a position that the export format of SQLiteFlow should have a general use case for post data processing, not that only useful for processing a query result that has to be exactly one row and one column.

This post is not a rejection, but more like a discussion.

Maybe you can describe a little more detail or give me a whole picture that what you are doing, so I can see if I can offer a better solution that from another angle.

Like, noticed that you're using `JSON_GROUP_OBJECT()` to generate JSON text, so is it possible that you let SQLiteFlow generate the json text directly for you (by using the JSON export type)?

**Comment by benyn** [comment]
I wrote about `JSON_GROUP_OBJECT()` because that happened to be the use case I was dealing with, but I can think of other non-one-row-one-column use cases, too. For a simple example, consider a list of text values fetched from a database. `sqlite3`'s list mode will faithfully return the original string values; SQLiteFlow's CSV mode will escape double quotes and whatnot, necessitating some post-processing.

I agree that there are many workarounds, whether it's using SQLiteFlow's JSON mode instead of `JSON_GROUP_OBJECT()`, using the Get Value from Dictionary action, or manual de-escaping. But why not just let the users retrieve their data without any escaping or formatting imposed by SQLiteFlow?

I wouldn't pretend to know what mode would have the broadest range of use cases. You might consider my use case a niche one, and I wouldn't argue with that because it might as well be the case. I don't know. But there must be a good reason why Dr. Hipp chose the `list` mode as the default mode for `sqlite3` out of 14 modes available, including `csv` and `json`. And it's usually not a bad idea to defer to the benevolent dictator of SQLite.

**Comment by SQLiteFlow** [comment]
> consider a list of text values fetched from a database. sqlite3's list mode will faithfully return the original string values;

Really? Let me show a counterexample:
The content of MyTable contains two rows:
| Col1 |
|:-----|
| a<br/>b  |
| b    |

The `sqlite3` `list` mode will output
```
a
b
b
```
Now from the post data processor's view, the result contains three rows, which is wrong.

I agree with you that the author of SQLite chose to use the `list` mode as the default mode for `sqlite3` terminal app may for a good reason, but that can't change the fact that the format of `list` mode is a very bad format for data processing, and maybe that's somewhat why other `sqlite3` output mode exist.

If the goal of your proposal is accessing the original field values directly, maybe I could find a way to let you do that.
But the way of the implementation in my head (currently) requires you adding more shortcut actions to access the original field values. It's efficiency guaranteed but may be less convenient than the workaround mentioned before. Like, adding a action to specify the row index and column index to be accessed.

Though for me, that's require a total rewriting of the Run Query action, I still wondering whether this solution looks good to you.

**Comment by benyn** [comment]
We can come up with examples and counter-examples all day long. No output mode is perfect, and that's why most SQLite clients including SQLiteFlow provide multiple output modes in the first place.

I don't agree with your assessment that the `list` mode is a very bad format for data processing. It _IS_ designed to be used in conjunction with an additional program for further processing. From the SQLite official documentation:

> The default output mode is "list". In list mode, each row of a query result is written on one line of output and each column within that row is separated by a specific separator string. The default separator is a pipe symbol ("|"). List mode is especially useful when you are going to send the output of a query to another program (such as AWK) for additional processing.

In the context of Shortcuts, it is certainly more useful than CSV for sure since there are no readily available CSV parsing module you can just import like you'd do if you were using a more fully featured programming language. In Shortcuts, the less post-processing required, the better. I'd consider regular-expression-based Actions such as "Replace Text" and "Match Text" as equivalents to shell's `awk`. To me, a plain text output not encumbered with escaping and formatting for JSON, CSV, or Markdown is immensely easier to apply regular expressions on.

I don't know why specifying row and column indexes is necessary. If the user needed only one cell's worth of data, they would have written the query to return just that. Why can't SQLiteFlow just return the data as it is and trust that users will know how to deal with that? If they need to avoid the `a b b` example you cited above, they'll simply choose another output mode that's better suited to that data format.

**Comment by SQLiteFlow** [comment]
Okay, maybe I was too overthinking before, I will add the `list` export type to the app.

**Comment by benyn** [comment]
Thanks!

**Comment by SQLiteFlow** [comment]
SQLiteFlow(iOS) 6.2.1 has been released. 

Adds an export type: List. The List type behaves similar with the list output mode in sqlite3 command line shell, but show BLOB data as empty. Available on Data Editor, Query Editor and Run Query Shortcuts action.

Please report back if it's working as expected.
