### ISSUE TITLE
Count() aggregate function?

### ISSUE THREAD

**Issue by marceyebeam** [SQLiteFlow/SQLiteFlow-Issues#223]
**Version**
 - Platform: iOS 17.1.1
 - SQLiteFlow: 6.2.0
 - I might have missed whether this has been answered in previous posts, but I seem not to be able to run the Count aggregate function in SQLiteflow, at least not as i can in SQLITE on my Mac. Is this a missing feature or a different syntax?
 - 
( A great app btw even without it)

**Comment by SQLiteFlow** [comment]
It supports. What's displaying?

**Comment by marceyebeam** [comment]
Hi, thanks for the response. I am looking to count for duplicate rows grouped by an ID code having a count(ID)>1. COUNT doesn't show as a keyword in the preemptive word list and i encounter an error. I have used the same syntax which works on my Mac as follows:

SELECT ID and Itemname from MyTable
GROUP BY ID having COUNT(ID)>1

**Comment by marceyebeam** [comment]
Ah, user error on my part,sorry. Once you indicated it was available i tried a few different methods and i have it working. Many thanks for the confirmation.

**Comment by SQLiteFlow** [comment]
You're welcome. Have a good time on your journey with working with SQLite.🙂
