### ISSUE TITLE
Support for JSONB?

### ISSUE THREAD

**Issue by nvkelso** [SQLiteFlow/SQLiteFlow-Issues#225]
I was excited to [read](https://sqlite.org/forum/forumpost/fa6f64e3dc1a5d97) about JSONB landing in SQLite trunk earlier in December. 

When can we expect support in SQLiteFlow? Love your software, thanks :)

**Version**
 - Platform: macOS 14.1.2
 - SQLiteFlow: 6.2.3

**Comment by SQLiteFlow** [comment]
> Love your software, thanks :)

Thank you!

> When can we expect support in SQLiteFlow?

Maybe soon after the JSONB feature releases.

Currently I'm still in the stage that trying to figure out what SQLiteFlow could do with it.

Here's some thinking:
1. Based on the fact that the backend storage type of JSONB is the existing type BLOB, so SQLiteFlow is already able to display or edit it as hex values, but I believe user may not want to do that.
2. So SQLiteFlow needs to let user at least have the ability to view JSONB as JSON text in Data Editor and Query Result.
3. And also SQLiteFlow needs to let user have the ability to save JSON text as JSONB in Data Editor.

Do you have anything else that you expect SQLiteFlow to do with it?

**Comment by nvkelso** [comment]
I create and use very large SQLite files (https://geocode.earth/data/whosonfirst/combined/) for the Who's On First gazetteer. Several of the tables have full JSON text, but it can be very slow to query and transform this data across millions of records in these 40 GB files. So a 3x speed enhancement is very appealing!

What you describe matches my expectations :)

**Comment by SQLiteFlow** [comment]
Understand. Thank you for the information.

**Comment by SQLiteFlow** [comment]
The implementation part has been finished.
A demo video has been attached, let me know if you have any questions.

https://github.com/SQLiteFlow/SQLiteFlow-Issues/assets/38027540/d56c6629-4949-4c7c-8203-be6d5dd2eaa3

**Comment by nvkelso** [comment]
Excellent work, I'm excited to try it out :)

**Comment by SQLiteFlow** [comment]
I'm glad to hear. Guess what's next is awaiting for the SQLite 3.45.0 releases.🙂

**Comment by SQLiteFlow** [comment]
SQLiteFlow(macOS) 6.2.4 with this feature implemented is available on the App Store now!

**Comment by nvkelso** [comment]
Amazing, thank you!

**Comment by SQLiteFlow** [comment]
My pleasure, let me know if you have any questions.
