### ISSUE TITLE
What is keybind to run the query?

### ISSUE THREAD

**Issue by nikivdev** [SQLiteFlow/SQLiteFlow-Issues#226]
Just bought SQLiteFlow but I don't get how to run the query from keybind. Tried `cmd+return`, did nothing.

Need to do this but from hotkey:

![CleanShot 2024-02-14 at 15 41 50@2x](https://github.com/SQLiteFlow/SQLiteFlow-Issues/assets/6391776/b4b60497-e7e2-40dd-b29b-d93b7b3047e9)

Thanks 🖤

**Comment by SQLiteFlow** [comment]
The hotkey is CMD+R.
Screenshot attached.
<img width="341" alt="Screenshot 2024-02-14 at 8 45 26 PM" src="https://github.com/SQLiteFlow/SQLiteFlow-Issues/assets/38027540/990f65c2-5ac6-4fc1-aee5-475b97bc3a01">
