### ISSUE TITLE
Table does not get shown in UI after creation

### ISSUE THREAD

**Issue by nikivdev** [SQLiteFlow/SQLiteFlow-Issues#227]
Just ran this query:

<img width="1512" alt="image" src="https://github.com/SQLiteFlow/SQLiteFlow-Issues/assets/6391776/072cabdc-c972-4eba-9866-4a04fef5ae55">

it did create the table:
 
<img width="449" alt="image" src="https://github.com/SQLiteFlow/SQLiteFlow-Issues/assets/6391776/03af4dad-5da1-43e7-9507-3306ed47fd10">

But as can be seen above, the UI does not reflect it.

Also I tried to create table through app itself, nothing got updated in UI either.

Also when I do `cmd+w` I see this:

<img width="1512" alt="image" src="https://github.com/SQLiteFlow/SQLiteFlow-Issues/assets/6391776/5d2228df-076c-4924-9189-dc40c384a61f">

What does that mean. What document?

**Comment by SQLiteFlow** [comment]
> the UI does not reflect it.

When you create a table through running a SQL in Query Editor, you will need to right click the database name - Refresh to let the UI show the new created table.

<img width="349" alt="1" src="https://github.com/SQLiteFlow/SQLiteFlow-Issues/assets/38027540/b6ea8c15-baae-4b5f-93fc-faa1d73a7e68">


> What document?

The temp SQL file Untitled.sql
