### ISSUE TITLE
Support connecting to Turso SQLite

### ISSUE THREAD

**Issue by nikivdev** [SQLiteFlow/SQLiteFlow-Issues#228]
I use https://turso.tech/ to deploy SQLite. I want to be able to connect to Turso through the app to run queries on deployed Turso instance.

**Comment by SQLiteFlow** [comment]
I took couple hours to let myself getting some knowledge about turso, so I'm not professional to it.

Beside just running queries, SQLiteFlow require a web server offer many other interfaces listed in https://sqlite.org/c3ref/funclist.html to be a SQLite editor, but looks like only few interfaces are supported by libsql https://github.com/tursodatabase/libsql/blob/main/bindings/c/include/libsql.h, maybe the interface they offered is good enough to serve a normal app, but looks like it's too few to serve SQLiteFlow as a SQLite editor.

**Comment by nikivdev** [comment]
All right, thank you.

I think what I will do is have Turso live sync data into some local SQLite and I will have SQLiteFlow run SQL queries on it instead.

**Comment by nikitavoloboev** [comment]
1.
