### ISSUE TITLE
SQLiteFlow(iOS), supports database diff.

### ISSUE THREAD

**Issue by SQLiteFlow** [SQLiteFlow/SQLiteFlow-Issues#23]
Let SQLiteFlow(iOS) has ability to make diff between two SQLite databases.

**Comment by SQLiteFlow** [comment]
This feature will available on next release.

**Comment by LetMorning** [comment]
SQLiteFlow(iOS) 3.2.0 has been released.

**Comment by SQLiteFlow** [comment]
SQLiteFlow(iOS) 3.2.0 has been released.
