### ISSUE TITLE
Entity-Relationship Diagram (ERD) feature request

### ISSUE THREAD

**Issue by lethefrost** [SQLiteFlow/SQLiteFlow-Issues#230]
**Version**
 - Platform: macOS Sonoma 14.3.1
 - SQLiteFlow: 6.3.2

Hi,

I recently started using your application, exploring its features to determine my interest in making a purchase. Overall, the application seems to meet my expectations, which is encouraging. One feature I'm particularly interested in is whether the application includes an Entity-Relationship Diagram (ERD) feature. Could you please confirm if this feature is available?

I understand there are independent tools available for generating/exporting ERDs from existing databases. However, having this functionality built into your GUI client would significantly enhance efficiency. The ability to edit entity fields and relations through an interactive and visualized view directly within the app would not only streamline the database design process but also improve the overall user experience.

Should the ERD feature not currently be part of your application, I strongly suggest considering its addition in a future update. ERDs are invaluable for visually representing data models, aiding significantly in database design and comprehension. Incorporating such a feature would extend the app's utility to those involved in database design and management, and attract a wider audience that values efficient data organization and analysis.

Thank you for considering my suggestion and for your assistance! 😊

**Comment by SQLiteFlow** [comment]
Thank you for trying the app, it's not available yet. 

I will consider it, however I aware this is a feature requires a very heavy work to implement, please don't expect it will available in the short future.

**Comment by SQLiteFlow** [comment]
Looks like it's not quite hard to implement if the app only supports viewing the ER diagram.
A screenshot attached. Does it looks good to you? 😄

<img width="1192" alt="ERDiagram_Demo" src="https://github.com/SQLiteFlow/SQLiteFlow-Issues/assets/38027540/40417c0b-2861-4b5e-ac5e-196b06196f82">

**Comment by SQLiteFlow** [comment]
It's available on the App Store now.

**Comment by lethefrost** [comment]
> Looks like it's not quite hard to implement if the app only supports viewing the ER diagram. A screenshot attached. Does it looks good to you? 😄
> 
> <img alt="ERDiagram_Demo" width="1192" src="https://private-user-images.githubusercontent.com/38027540/318159942-40417c0b-2861-4b5e-ac5e-196b06196f82.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE4NTc1ODYsIm5iZiI6MTcxMTg1NzI4NiwicGF0aCI6Ii8zODAyNzU0MC8zMTgxNTk5NDItNDA0MTdjMGItMjg2MS00YjVlLWFjNWUtMTk2YjA2MTk2ZjgyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzMxVDAzNTQ0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRmOTNlMDdmNWQzODg2OGMyNjkxZmZmMzhmZDU0OTgwM2FlYzAwNjY1NTJjYTFhYTk1ZjY2NzRkMzExOWU3YTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Fn-pYAf4V1JHBzL6wryn6Kqp2iUP-P8j1FlMs5S5Pao">

It looks cool! Thank you for this superfast response & implementation! I'd definitely purchase the product in support of your commitment and efforts. It's very impressive and I really appreciate it! Thank you again 😊

I think the graph can briefly represent the fields of each table schema and the relationship among the tables, and it's very nice to give the users a visualized glimpse & general grasp of the whole database they are working on. The graph feature you just implemented can be an especially helpful and awesome tools in the following scenarios:

- When you need to show your team members around the structure of your DB, or 
- you just take over a new DB and need to familiarize yourself, 
- or you just designed some new tables but haven't yet had a clear picture of how they will work together, and the visualization can help you review design more easily.

However, there might be more things that an interactive ERD could do. For example:

- Now it's relatively schematic and rough, and it could certainly be more informatic. 
	- One possible thing is to improve the styling, make the field name and type more distinguishable at the first glance.
		- They could have different font weight, size, color, or etc. 
		- Or aligning strategies could also be considered. 
			- For example, the types might be right-justified. 
			- Or, space padding could be given to emulate a table-like alignment/justification.
	- Special fields (e.g. primary key fields, foreign keys, candidate keys, etc.) could have distinct text styling, or just give them some icon badge, background color, border, or something similar to easily identify them
- If the ERD can eventually be interactive, it could be even more informatic, and handy in designing, revising and refactoring the database.
	- When hovering over each table, field, or foreign key link between tables, it could show a tooltip/balloon/popup window of more details. For instance, 
		- for a field or key it could show the related constraints, rules, references, or other features such as `AUTOINCREMENT`.
		- for a table, it could show the triggers
		- for a foreign key link, it could show the cascade rules, and while hovering the link, the related field at both side could be highlighted
	- When clicking on each element, 
		- it could let you directly modify it (such as rename or change type),
		- or lead you to the schema editor page that allows more sophisticated operations.

Let me know if those detailed proposal or suggestions sound sensible to you, or you could also consult the other DBMS GUI tools for reference.

Just by the way, is the graph rendered by mermaid.js? It looks somewhat familiar 😂 I thought it only works in js environment.

**Comment by SQLiteFlow** [comment]
Yes, it's rendered by mermaid.js. That' why I can implement it so quickly, what I did is basically generate the mermaid markdown and let a webview render it locally.

I believe a lot of what you mentioned do make sense to me. I will keep improving it, but I'm not quite good at writing H5 app, I will see how far I can go with using mermaid.js. To me, mermaid.js itself also have a lot of limitations, and I don't feel at home there.

Maybe in the long term, I will re-implement this feature by myself (which is my original thought) so I can have more control with it.

But currently let's stick with the current tech route and see what I can do with it.

**Comment by lethefrost** [comment]
> Yes, it's rendered by mermaid.js. That' why I can implement it so quickly, what I did is basically generate the mermaid markdown and let a webview render it locally.
> 
> I believe a lot of what you mentioned do make sense to me. I will keep improving it, but I'm not quite good at writing H5 app, I will see how far I can go with using mermaid.js. To me, mermaid.js itself also have a lot of limitations, and I don't feel at home there.
> 
> Maybe in the long term, I will re-implement this feature by myself (which is my original thought) so I can have more control with it.
> 
> But currently let's stick with the current tech route and see what I can do with it.

I can totally relate to your feelings! When I worked with mermaid, trying to figure out the limitations and workarounds, I was also so frustrated and hoped that I could have more controls. Now what you get for SQLiteFlow is far better than nothing, and I believe you can keep improving it or find a way to create your own implementation. Looking forward to your amazing work, and please let me know if there's any update on it!

**Comment by SQLiteFlow** [comment]
Thank you for your support.
And sure, I will keep you posted on any further major update by adding new post here.

**Comment by SQLiteFlow** [comment]
A new version of ER Diagram landed, and with totally reimplemented.

What's new:
- Add an icon to primary key field to indicate a table's primary key.
- Add an icon to foreign key field to indicate a table's foreign key.
- Field name and type now has different text styling.
- When select a foreign key field, foreign key referenced field, or relation path, related elements will be highlighted.
- Supports open Table Schema (by clicking the button beside the table name) to edit table schema structure.
- Supports open Data Editor (by right clicking a table name - Select Rows) to edit table's data.


<img width="1336" alt="ERDiagram 2 0" src="https://github.com/SQLiteFlow/SQLiteFlow-Issues/assets/38027540/a638a5f1-6200-4327-979d-806df067b841">

**Comment by lethefrost** [comment]
> A new version of ER Diagram landed, and with totally reimplemented.
> 
> What's new:
> 
> * Add an icon to primary key field to indicate a table's primary key.
> * Add an icon to foreign key field to indicate a table's foreign key.
> * Field name and type now has different text styling.
> * When select a foreign key field, foreign key referenced field, or relation path, related elements will be highlighted.
> * Supports open Table Schema (by clicking the button beside the table name) to edit table schema structure.
> * Supports open Data Editor (by right clicking a table name - Select Rows) to edit table's data.
> 
> <img alt="ERDiagram 2 0" width="1336" src="https://private-user-images.githubusercontent.com/38027540/322330688-a638a5f1-6200-4327-979d-806df067b841.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMxNTMwMjYsIm5iZiI6MTcxMzE1MjcyNiwicGF0aCI6Ii8zODAyNzU0MC8zMjIzMzA2ODgtYTYzOGE1ZjEtNjIwMC00MzI3LTk3OWQtODA2ZGYwNjdiODQxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE1VDAzNDUyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM2MWQyZDQ3YzQ5ZDhjNTk5YzhiMDQ3MTYyOGRkM2RiYThkOTk3Mjk2MDlmYjg0NmVmMzE3MTY5NDgxMzAyMmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.TmzMPOkmwquVos2bfZyy8V4QBcYcjUnIMWn1L6SojHg">

Thank you for updating me! I have to say, that's so impressive and amazing! Thank you for all the efforts keeping improving it and make it so great. Can't wait to try out the new version!! ☺️

**Comment by SQLiteFlow** [comment]
It's already released.
