### ISSUE TITLE
Syncing between Macbook and iPhone/iPad

### ISSUE THREAD

**Issue by david-gibson** [SQLiteFlow/SQLiteFlow-Issues#231]
**Version**
 - Platform: [e.g. macOS 13.0]
 - SQLiteFlow: [e.g. 5.8.0]
I am using a trial version so I am new at this. I use SQLiiteFlow to create a test database in a folder in my iCloud drive on my Mac, then connected to it with my iPhone, but I don't see changes I make from one platform on the other. Can this be done?

**Comment by SQLiteFlow** [comment]
Thank you for trying the app.

The database files is just normal files in iCould drive, so they should synced automatically by OS.

However, you should pay attention to the tips that the app gives to you when operating SQLite databases on a network device.

Screenshot attached.
![Untitled](https://github.com/SQLiteFlow/SQLiteFlow-Issues/assets/38027540/2bd0aefb-c8fe-404f-87a1-d69fa6c29afe)
