### ISSUE TITLE
Dead-end in UI preventing creating and running a query

### ISSUE THREAD

**Issue by radioflyer28** [SQLiteFlow/SQLiteFlow-Issues#235]
**Version**
 - Platform: iOS 17.5.1
 - SQLiteFlow: 6.3.7

**Steps to Reproduce**
- Open database (in app or from external source)
- Open "queries"
- Try to select a database

**Expected behavior**
It's not possible to get to the part of the UI for creating and running a query. When opening "Queries" it asks to select a database but the only options given are to delete or create a database.

**Comment by SQLiteFlow** [comment]
After you open "Queries", you can create a SQL file by pressing the + button, then "New SQL File".

![image](https://github.com/SQLiteFlow/SQLiteFlow-Issues/assets/38027540/82d0ddca-a463-4273-8bd6-623e3242be44)

![image](https://github.com/SQLiteFlow/SQLiteFlow-Issues/assets/38027540/a78aed7d-8726-487d-b827-2466c42491d3)

Does the UI at your side looks different?

**Comment by radioflyer28** [comment]
Thanks, the UI looks the same on my side and your steps work. My confusion was I thought the "choose an action" menu, with the "New SQL file" option, was asking if I wanted to create a new database, so I never selected it.

**Comment by SQLiteFlow** [comment]
I see. 
And you're welcome.🙂
