### ISSUE TITLE
Duplicate a record

### ISSUE THREAD

**Issue by hush-today** [SQLiteFlow/SQLiteFlow-Issues#237]
**Version**
 - Platform: [e.g. macOS 13.0]
 - SQLiteFlow: [e.g. 5.8.0]

Hi,
I'm wanting to duplicate/modify records:

A) Is there a way to copy a whole table entry record rather than just copy each data item
B) How do I copy a binary 'blob' - I can copy/paste other entries but not a blob - is this possible, if so, how. If not - how can I get a binary blob into another record.

Thank you

**Comment by SQLiteFlow** [comment]
A.1
If you want to copy multiple rows, I believe CMD+C or Mouse Right Click - Copy will do the job, this action will copy your data to CSV (but no blob data will be included). 
To insert the CSV data to a new table, use the feature Import - CSV Text.

<img width="400" alt="A1" src="https://github.com/SQLiteFlow/SQLiteFlow-Issues/assets/38027540/8447de51-8ce3-4ab4-8afb-dd8d8b68b0fc">
<img width="400" alt="A1 1" src="https://github.com/SQLiteFlow/SQLiteFlow-Issues/assets/38027540/4ff7cc21-169d-4348-8b24-dcfc0e444892">

A.2
If you want to duplicate a whole table, it's more easier to use SQL like:
```
INSERT INTO DestinationTable
SELECT
    *
FROM SourceTable;
```
B
After you click a BLOB cell and bring up the Hex Editor, you can also use CMD+C or Mouse Right Click - Copy to copy the data to clipboard.
If you want to put it to another cell, click the destination cell, then Mouse Right Click - Edit as Hex to bring up a Hex Editor, then use CMD+V or Mouse Right Click - Paste to paste the data to the Hex Editor, then click Apply to save.

<img width="400" alt="B1" src="https://github.com/SQLiteFlow/SQLiteFlow-Issues/assets/38027540/976647fd-55aa-4645-95bc-5a03e7b8b38b">
<img width="400" alt="B2" src="https://github.com/SQLiteFlow/SQLiteFlow-Issues/assets/38027540/3f2fc34e-6819-40dd-b629-a96a83db68c0">
<img width="400" alt="B3" src="https://github.com/SQLiteFlow/SQLiteFlow-Issues/assets/38027540/f0a497c8-5ef2-4108-a00d-661483d1b64b">
