### ISSUE TITLE
Change name of db in app

### ISSUE THREAD

**Issue by RyanDurk** [SQLiteFlow/SQLiteFlow-Issues#239]
**Version**
 - Platform: [e.g. macOS 13.0]
 - SQLiteFlow: [e.g. 5.8.0]

2 open databases are on the left. Could you add the option to "rename" databases in the app without actually changing the filename? This way users can open and keep track of databases with the same filename (db.sqlite in this instance) that are in different directories . Perhaps showing the parent directory in a slightly grayed color would accomplish the same thing.

![CleanShot 2024-08-10 at 10 49 43@2x](https://github.com/user-attachments/assets/43a4dfd7-64e6-4e55-aea6-d2a237fc54bf)

**Comment by SQLiteFlow** [comment]
Thank you for the suggestion. 
I prefer the second like approach, I will see what I can do.🙂

**Comment by SQLiteFlow** [comment]
In addition, currently you can use mouse hover at the database name or any opened tab bar to see a database's full path.

**Comment by SQLiteFlow** [comment]
SQLiteFlow(macOS) 6.4.1 has been released.
