### ISSUE TITLE
SQLiteFlow(iOS), supports import data to table from CSV format.

### ISSUE THREAD

**Issue by SQLiteFlow** [SQLiteFlow/SQLiteFlow-Issues#24]

**Comment by SQLiteFlow** [comment]
Working on it.

**Comment by SQLiteFlow** [comment]
This feature will available on next release.

**Comment by SQLiteFlow** [comment]
Released.

**Comment by Dionysu** [comment]
This is about importing from a CVS list into a database table. (1) The title line (naming the fields) is included in the import, making me find and delete the record of headers. (2) The CVS file contained five records.  Only four were downloaded into the table.

**Comment by SQLiteFlow** [comment]
Hello @Dionysu 
1) To let the first line in CSV be treated as the title line (naming the fields), you can set the option 'First Line in CSV is Header' to ON state.
![Image](https://user-images.githubusercontent.com/38027540/59558274-04c74700-9021-11e9-95e1-9ac1d0f4db3b.jpg)

2) If not all records has been imported, may be this is caused by a bug, can I have a look to the CSV text you tested with?
