### ISSUE TITLE
Save/Load filters

### ISSUE THREAD

**Issue by rene-aguirre** [SQLiteFlow/SQLiteFlow-Issues#241]
**Version**
 - Platform: [e.g. macOS 13.0]
 - SQLiteFlow: [e.g. 5.8.0]

The filtering is so convenient (thanks for taking the improvements though!), that resist to create deal with bare queries, this is good :D 

It'd be nice if after an open ended filtering data mining tweak session I could just save them, so I can open another database and apply it.

I'd be nice if the persisted format is "human friendly" so I could manually copy/paste sections of the filters from multiple files.

Cherry on top: ideally the persisted format could be actually an SQL query, but I'd take anything that you think would be easy to scale, example, a text file with a specific delimited or JSON, that'd still allow to manually copy/paste sections across different filter files.

**Comment by rene-aguirre** [comment]
Another usability part of this, once filters are persisted and shared, it'd be nice to have a way to add comments to specific top level filters, these comments could be shown when hovering over the filter. 

If this is implemented as SQL queries, this could use immediate SQL comment above the next parsed filter, example:

```
--- Manhattan project (1234) January data
OR Month LIKE "%jan%"
AND Project = "1234"
```

In that sense, any format that'd allow to insert headers or sections (like JSON with any specific "summary" dictionary item) would work.

**Comment by SQLiteFlow** [comment]
This feature is available on iOS side, it allows you load or save filter as a file like `My_Project_January_Data.dflexp`, and the format of backend storage is JSON.
I think I can make this feature available on macOS in future version of SQLiteFlow.

For the top level comments part, maybe just set it as the file name is fine?

**Comment by SQLiteFlow** [comment]
SQLiteFlow(macOS) 6.4.1 has been released.
