### ISSUE TITLE
Hiding table columns

### ISSUE THREAD

**Issue by rene-aguirre** [SQLiteFlow/SQLiteFlow-Issues#242]
**Version**
 - Platform: [e.g. macOS 13.0]
 - SQLiteFlow: [e.g. 5.8.0]

It'd be nice to have a way to toggle data visibility for specific columns, this will help in two different flows:
* packed data, some DBs I use have a lot of columns, I'd be nice to visually focus on what matters
* VERY IMPORTANT: Copying specific data, once columns are hidden I could control what data is copied to my system clipboard, no more manual tuning after I paste.

**Comment by SQLiteFlow** [comment]
Accepted.

**Comment by SQLiteFlow** [comment]
SQLiteFlow(macOS) 6.4.1 has been released.
