### ISSUE TITLE
Clipboard Copy format setting

### ISSUE THREAD

**Issue by rene-aguirre** [SQLiteFlow/SQLiteFlow-Issues#243]
**Version**
 - Platform: [e.g. macOS 13.0]
 - SQLiteFlow: [e.g. 5.8.0]

Last one today, I promise :D 

This is a follow up to the capability to hide columns and use visibility to copy to clipboard.

The feature request is:
* Have a setting or "Copy as..." menu option that'd allow me to change the copied data format
* currently the data is copied as CSV, but I'd like to have other options like controlling the delimiter format but most imporantly, options what allow to show the data as a table like HTML, Markdown or even text with spaces for a quick nice view on my email or chat.

**Comment by SQLiteFlow** [comment]
The feature (copying specific data to supported format to clipboard) already exist, it's just not in context menu.
Screenshots attached, it's in Export.
Currently the supported formats are: CSV, JSON, Markdown, List, Insert Statement, Update Statement, if you really need more format in practice, please let me know.

<img width="1237" alt="1" src="https://github.com/user-attachments/assets/61354152-ebed-4c4d-8169-dfeca982d8ee">
<img width="1237" alt="2" src="https://github.com/user-attachments/assets/1772c967-2639-4711-a599-dad3749c5787">

**Comment by SQLiteFlow** [comment]
SQLiteFlow(macOS) 6.4.1 has been released.
