### ISSUE TITLE
Can't run trial or purchase

### ISSUE THREAD

**Issue by AlfredLarsen** [SQLiteFlow/SQLiteFlow-Issues#244]
Hi,

I can't seem to run the trail or even purchase a license. Also, it says "Trial complete" but I have never downloaded this app before.

I full internet access, no VPN, etc.

**Version**
 - Platform: [e.g. macOS 13.0]
 - SQLiteFlow: [e.g. 5.8.0]

**Steps to Reproduce**

Install the app from App Store.
Open it.

**Expected behavior**

Ability to have the trial or to purchase a licence.

**Screen shots**

<img width="732" alt="Screenshot 2024-08-31 at 12 51 24" src="https://github.com/user-attachments/assets/3c2891cc-4bc8-49e1-add5-5ef570c4f239">

<img width="732" alt="Screenshot 2024-08-31 at 12 56 51" src="https://github.com/user-attachments/assets/435024b5-d1b8-40dd-a513-7a6502f214f5">

**Comment by SQLiteFlow** [comment]
Please let me know what's your macOS version and SQLiteFlow version.

**Comment by AlfredLarsen** [comment]
Sure,

MacOS 14.2.1
SQLiteFlow version 6.4.0

<img width="392" alt="Screenshot 2024-08-31 at 14 15 45" src="https://github.com/user-attachments/assets/d0998de5-4c3e-469f-8893-0dded4cde9a8">

<img width="664" alt="Screenshot 2024-08-31 at 14 15 58" src="https://github.com/user-attachments/assets/0ad22ee4-e2a5-484f-b870-5feaee3922df">

**Comment by SQLiteFlow** [comment]
Okay, seems like you're using the latest version of SQLiteFlow, but some earlier version of macOS Sonoma 14.
What happens if you clicking the Reload Plan button?
And have you try if deleting the app then re-download it from the App Store would fix the issue?

**Comment by AlfredLarsen** [comment]
I will delete the app, update to the latest Mac OS, and try downloading it again.

**Comment by SQLiteFlow** [comment]
What happens if you clicking the Reload Plan button?

**Comment by AlfredLarsen** [comment]
Thank you, after updating MacOS, everything appears to be working great.

Thank you for your quick responses.

<img width="981" alt="Screenshot 2024-08-31 at 14 42 24" src="https://github.com/user-attachments/assets/ae4e4021-a576-491e-bfdb-631adb659183">

**Comment by SQLiteFlow** [comment]
You're welcome, then that's seems like a bug of earlier version of macOS Sonoma 14.
