### ISSUE TITLE
Add DROP VIEW when using the Alter View option

### ISSUE THREAD

**Issue by flintcreek** [SQLiteFlow/SQLiteFlow-Issues#245]
**Version**
 - Platform: [e.g. macOS 14.6.1]
 - SQLiteFlow: [e.g. 6.4.0]

This app has been quite helpful for my db development efforts!  Nice job.

My request:

When right-clicking a view name in the left panel, there is an "Alter view" command.  This opens a query window with a CREATE VIEW command in it.  

Since Sqlite doesn't have an ALTER VIEW command, it would be nice if a DROP VIEW command was prepended to the CREATE VIEW script in the query window.  This way, the user could modify the view script and run it to drop and re-create the view without having to separately drop the view, run the create view script, and refresh the left panel from the database menu.

**Comment by SQLiteFlow** [comment]
Accepted.

**Comment by SQLiteFlow** [comment]
SQLiteFlow(macOS) 6.4.1 has been released.
