### ISSUE TITLE
Restore Previous Purchase issue

### ISSUE THREAD

**Issue by widgt** [SQLiteFlow/SQLiteFlow-Issues#250]
**Version**
 - Platform: [e.g. macOS 14.7]
 - SQLiteFlow: [e.g. 6.5.0]

**Steps to Reproduce**
Hi, bought the app a couple of years ago and it has worked very well, but today, from out of the blue on launch, I got the Purchase Plan screen and Trial Mode. 

I tried Restore Previous Purchase; got no error, but after the progress spinner nothing happened, and the 14-day Trial header remained. 

Quit and relaunch still shows header and on the SQLiteFlow > Purchase Plan screen, there's no indication I ever bought the app. Unlimited Annual is selected as a suggestion, but I believe I bought Lifetime. 

Any idea what could be wrong?

**Expected behavior**
Restore previous purchase

**Screen shots**
Will upload if needed

**Comment by SQLiteFlow** [comment]
Relate issue: https://github.com/SQLiteFlow/SQLiteFlow-Issues/issues/246#issuecomment-2393555826

Does restart your Mac could fix the issue?

**Comment by widgt** [comment]
No, but logging out of the Mac App Store, then back in, seems to have done the trick. Thanks!

**Comment by SQLiteFlow** [comment]
You're welcome, and that's nice to hear.
