### ISSUE TITLE
Transfer purchase?

### ISSUE THREAD

**Issue by lynns** [SQLiteFlow/SQLiteFlow-Issues#255]
I bought the Lifetime License earlier this year using an apple id that I've been sharing with my wife for more than 10 years now. We recently decided to bite the bullet and use different apple ids. I've started to use a new apple id and I wondered if it's possible to transfer my lifetime license to that apple id since my wife (who's using the old id) has no use for an application like this.

**Comment by SQLiteFlow** [comment]
I don't think there's any way to do that.

Relative link:
https://www.bing.com/search?q=transfer+purchases+from+one+Apple+ID+to+another&form=QBLH&sp=-1&ghc=1&lq=0&pq=transfer+purchases+from+one+apple+id+to+another&sc=12-47&qs=n&sk=&cvid=8CBA618833B445A0B2E7D86CDE7F93F0&ghsh=0&ghacc=0&ghpl=

**Comment by lynns** [comment]
I thought it was worth asking. Thanks for the response. I'll just buy it again. You've done a great job creating an app that is crazy useful for anyone using sqlite databases.

**Comment by SQLiteFlow** [comment]
Thank you for your support.

And using a new Apple ID is not an easy decision, since you may re-buy lots of apps you purchased before.
