### ISSUE TITLE
[macOS] no records are displayed

### ISSUE THREAD

**Issue by stephanblaurock** [SQLiteFlow/SQLiteFlow-Issues#27]
Hello,
SQLiteFlow has been updated to version 3.5.0 today. Although I can still open databases, I can not see the records in the tables anymore. Although the status bar says "7 records OK, Time: 0.000345s", there are no records in the list. Yesterday it worked!
Could you please fix that very quickly, I need the tool very urgently!

**Comment by SQLiteFlow** [comment]
Hello @stephanblaurock,
I just tested in my side with version 3.5.0, it can show records correctly, a screenshot has been attached.
Is it convince for you to attach a sample database(with sensitive information removed) for me to test?
![ScreenShot](https://user-images.githubusercontent.com/38027540/56641850-c6f51480-66a8-11e9-95b5-df3d419bc9a9.png)

**Comment by cjwisniewski** [comment]
Same problem for me: macOS 10.14.5 beta + dark mode. You can see that the sample database in my screen shots contains three records, which even SQLiteFlow reports (see its status line) -- but no record content is rendered.

![SQLiteFlow main window after opening database](https://user-images.githubusercontent.com/3946553/56682503-85507380-6680-11e9-89e8-87881480752a.png)

![SQLiteFlow select results](https://user-images.githubusercontent.com/3946553/56682510-87b2cd80-6680-11e9-9dc7-8385867a0b74.png)

![DB Browser for SQlite](https://user-images.githubusercontent.com/3946553/56682518-8aadbe00-6680-11e9-8cb9-c032401e3539.png)

![sqlite commandline](https://user-images.githubusercontent.com/3946553/56682525-8c778180-6680-11e9-9189-e83bd0c1f504.png)

**Comment by SQLiteFlow** [comment]
Issue reproduced.

**Comment by SQLiteFlow** [comment]
Fixed. Testing now.

**Comment by SQLiteFlow** [comment]
@stephanblaurock @cjwisniewski 
Issue reproduced and fixed, thanks for the reporting. A fix version 3.5.2 has just been submitted to Apple's App Review team.

**Comment by SQLiteFlow** [comment]
@stephanblaurock @cjwisniewski 
A new version 3.5.2 is available on Mac App Store, this issue should be fixed in this version, you can update it and have a look now.
