### ISSUE TITLE
[MacOS] Though clicking on column titles results in toggling the ascending and descending symbols, column content does not sort

### ISSUE THREAD

**Issue by cjwisniewski** [SQLiteFlow/SQLiteFlow-Issues#28]
Commentary on issue 19 in this tracking database suggests that this feature should work as does a remark in the product's 3.1.0 release notes on macOS --but I cannot get it to work at all in version 3.5.2.

**Comment by SQLiteFlow** [comment]
@cjwisniewski 
This is a bug, fixed in version 3.5.3 which is pending release now, you can get it once it available on Mac App Store.

**Comment by SQLiteFlow** [comment]
@cjwisniewski 
SQLiteFlow(macOS) 3.5.3 has been released. The sorting column content by clicking column feature should work as expected now.
