### ISSUE TITLE
[MacOS suggestion] Improvements to the dismissible trial notice and related content

### ISSUE THREAD

**Issue by cjwisniewski** [SQLiteFlow/SQLiteFlow-Issues#29]
![SQLIteFlow 05](https://user-images.githubusercontent.com/3946553/56816990-76410100-67f9-11e9-8bae-b8bf41f76f65.png)
A white-colored font on an ivory-colored background, which is used in the dismissible note that's displayed for users who are running the trial version, is a poor choice: for it makes the copy in the message exceedingly difficult to read. 

Additionally, at least for English-language users, the verbiage "Full Unlock" on the button that's positioned on the right of the dissmissible trial notice is a bit misleading. As the statement shown in the dialog that results if one clicks the "Full Unlock" button makes clear, the product's trial mode permits ALL of its features to work (not some subset), though for two weeks only. It's clearer, therefore, to use the term "Purchase" rather than "Full Unlock."  And here's a suggestion for a more concise and direct way to convey the product's trial vs. purchased mode:

Trial

All of the product's features can be used during your trial. After the trial has expired, you'll need to purchase the product to continue to use it. 

[Restore previous purchase] [Purchase $9.99]

**Comment by SQLiteFlow** [comment]
@cjwisniewski 
Thank you very much for the suggestion! I will do the improvement.
1. Make the dismissible note trial note's background color more suitable to dark mode.
2. You are right, the term 'Purchase' and the way to convey the product's trial vs. purchased mode you mentioned is a lot better than the current one, I will make the change.

**Comment by SQLiteFlow** [comment]
@cjwisniewski Attached 4 screenshots, looks good? 

![1](https://user-images.githubusercontent.com/38027540/56823242-e8f7be00-6885-11e9-84e9-8fc72330f066.png)
![2](https://user-images.githubusercontent.com/38027540/56823243-e8f7be00-6885-11e9-81c9-b91d6428118b.png)
![3](https://user-images.githubusercontent.com/38027540/56823244-e8f7be00-6885-11e9-8311-8b84af83ea9f.png)
![4](https://user-images.githubusercontent.com/38027540/56823246-e9905480-6885-11e9-9955-c11303976a00.png)

**Comment by SQLiteFlow** [comment]
@cjwisniewski 
SQLiteFlow(macOS) 3.5.3 has been released. 
In this version I update the trial note's background more comfortable in dark mode, and make the purchase description more clearer.
Thank you for the feedback again.

**Comment by cjwisniewski** [comment]
You're welcome!

    On Friday, April 26, 2019, 10:24:57 PM EDT, SQLiteFlow <notifications@github.com> wrote:  
 
 
@cjwisniewski
SQLiteFlow(macOS) 3.5.3 has been released.
In this version I update the trial note's background more comfortable in dark mode, and make the purchase description more clearer.
Thank you for the feedback again.
