### ISSUE TITLE
使用中文作为字段名称时出现输入异常

### ISSUE THREAD

**Issue by wangtwoji** [SQLiteFlow/SQLiteFlow-Issues#3]
![cfd1ef59-8d29-4ad5-9058-4f8721fecd4d](https://user-images.githubusercontent.com/42517524/44310368-49855000-a407-11e8-8d1c-08f77b159fb0.png)

使用的是苹果原生输入法

**Comment by SQLiteFlow** [comment]
您好@wangtwoji，请问您提到的”出现输入异常”具体是只什么呢，因为我有点看不太懂这个问题。
另外，我注意到键盘没有显示，是因为您连接了一个外置物理键盘对吗？

Hello @wangtwoji, could you tell us what the exception actual is? Cause we can't quite understand the question. 
And we notice that the keyboard didn't appear, is this because of a physical keyboard was connected to the iPad?

**Comment by SQLiteFlow** [comment]
您好，@wangtwoji，请问视频在哪里呢，我只看到了一副截图，并且什么是“内容识别问题“？

关于您提出这个Issue，可以详细描述一下吗，比如
您期望SQLiteFlow行为是：
实际上SQLiteFlow行为是：

Hello @wangtwoji, where is the video? What I can get is only a screen shot. And what is the meaning for 'an issue in content detection'? 

And could you answer the following two questions?
What's your expected behavior that SQLiteFlow should have:
What's the actual behavior that SQLiteFlow have:

**Comment by wangtwoji** [comment]
期望的行为：可以使用中文作为字段名称实际的行为：输入一个字母，会出现多个（随机数量）个字母，中文输入法无法正常工作。我尝试在附件中添加了一段压缩的视频，如果可以下载播放你可以看到具体的现象。—————————————————
愿你一生平安健康
和你一起终身学习的 王喆@太古森林
—————————————————
            在2018年08月20日 23:36，SQLiteFlow 写道： 您好，@wangtwoji，请问视频在哪里呢，我只看到了一副截图，并且什么是“内容识别问题“？
关于您提出这个Issue，可以详细描述一下吗，比如
您期望SQLiteFlow行为是：
实际上SQLiteFlow行为是：
Hello @wangtwoji, where is the video? What I can get is only a screen shot. And what is the meaning for 'an issue in content detection'?
And could you answer the following two questions?
What's your expected behavior that SQLiteFlow should have:
What's the actual behavior that SQLiteFlow have:

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/SQLiteFlow/SQLiteFlow-Issues","title":"SQLiteFlow/SQLiteFlow-Issues","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/SQLiteFlow/SQLiteFlow-Issues"}},"updates":{"snippets":[{"icon":"PERSON","message":"@SQLiteFlow in #3: 您好，@wangtwoji，请问视频在哪里呢，我只看到了一副截图，并且什么是“内容识别问题“？\r\n\r\n关于您提出这个Issue，可以详细描述一下吗，比如\r\n您期望SQLiteFlow行为是：\r\n实际上SQLiteFlow行为是：\r\n\r\nHello @wangtwoji, where is the video? What I can get is only a screen shot. And what is the meaning for 'an issue in content detection'? \r\n\r\nAnd could you answer the following two questions?\r\nWhat's your expected behavior that SQLiteFlow should have:\r\nWhat's the actual behavior that SQLiteFlow have:"}],"action":{"name":"View Issue","url":"https://github.com/SQLiteFlow/SQLiteFlow-Issues/issues/3#issuecomment-414361704"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/SQLiteFlow/SQLiteFlow-Issues/issues/3#issuecomment-414361704",
"url": "https://github.com/SQLiteFlow/SQLiteFlow-Issues/issues/3#issuecomment-414361704",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [SQLiteFlow/SQLiteFlow-Issues] 使用中文作为字段名称时出现输入异常 (#3)",
"sections": [
{
"text": "",
"activityTitle": "**SQLiteFlow**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@SQLiteFlow",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"SQLiteFlow/SQLiteFlow-Issues\",\n\"issueId\": 3,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"SQLiteFlow/SQLiteFlow-Issues\",\n\"issueId\": 3\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/SQLiteFlow/SQLiteFlow-Issues/issues/3#issuecomment-414361704"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 369886960\n}"
}
],
"themeColor": "26292E"
}
]

**Comment by SQLiteFlow** [comment]
@wangtwoji 可以把附件添加到这里吗，我看不到您提到的附件视频。
https://github.com/SQLiteFlow/SQLiteFlow-Issues/issues/3

Could you attach your video file at here?

**Comment by SQLiteFlow** [comment]
@wangtwoji 可以通过我们的Issue页面添加附件，通过邮件回复我们看起来收不到。
这里是连接：https://github.com/SQLiteFlow/SQLiteFlow-Issues/issues/3

Could you attach your video file to our Issue page, we may not get any attach file through a email reply.
This is the link: https://github.com/SQLiteFlow/SQLiteFlow-Issues/issues/3

**Comment by SQLiteFlow** [comment]
@wangtwoji 这是我们根据您的描述录制的视频，似乎没有出现您提到的现象？

This is a video that recorded based on your description, seems the issue not appeared? 

[ScreenRecording_08-20-2018 20-57-44.zip](https://github.com/SQLiteFlow/SQLiteFlow-Issues/files/2304679/ScreenRecording_08-20-2018.20-57-44.zip)

**Comment by wangtwoji** [comment]
我是用网盘把录像分享了出来，您可以看一下。https://cloud.189.cn/t/jQnqQffIB3Mf (访问码:8255)—————————————————
愿你一生平安健康
和你一起终身学习的 王喆@太古森林
—————————————————
            在2018年08月21日 11:05，SQLiteFlow 写道： @wangtwoji 这是我们根据您的描述录制的视频，似乎没有出现您提到的现象？
This is a video that recorded based on your description, seems the issue not appeared?
ScreenRecording_08-20-2018 20-57-44.zip

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/SQLiteFlow/SQLiteFlow-Issues","title":"SQLiteFlow/SQLiteFlow-Issues","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/SQLiteFlow/SQLiteFlow-Issues"}},"updates":{"snippets":[{"icon":"PERSON","message":"@SQLiteFlow in #3: @wangtwoji 这是我们根据您的描述录制的视频，似乎没有出现您提到的现象？\r\n\r\nThis is a video that recorded based on your description, seems the issue not appeared? \r\n\r\n[ScreenRecording_08-20-2018 20-57-44.zip](https://github.com/SQLiteFlow/SQLiteFlow-Issues/files/2304679/ScreenRecording_08-20-2018.20-57-44.zip)\r\n"}],"action":{"name":"View Issue","url":"https://github.com/SQLiteFlow/SQLiteFlow-Issues/issues/3#issuecomment-414534858"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/SQLiteFlow/SQLiteFlow-Issues/issues/3#issuecomment-414534858",
"url": "https://github.com/SQLiteFlow/SQLiteFlow-Issues/issues/3#issuecomment-414534858",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [SQLiteFlow/SQLiteFlow-Issues] 使用中文作为字段名称时出现输入异常 (#3)",
"sections": [
{
"text": "",
"activityTitle": "**SQLiteFlow**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@SQLiteFlow",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"SQLiteFlow/SQLiteFlow-Issues\",\n\"issueId\": 3,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"SQLiteFlow/SQLiteFlow-Issues\",\n\"issueId\": 3\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/SQLiteFlow/SQLiteFlow-Issues/issues/3#issuecomment-414534858"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 369886960\n}"
}
],
"themeColor": "26292E"
}
]

**Comment by SQLiteFlow** [comment]
@wangtwoji 我们试了一下您提供的链接，下载这个文件似乎需要一个这个网站的一个账号，而我们在注册账号时遇到了一些麻烦。如果您方便的话，可以直接将文件发到我们的邮箱么，邮箱地址是
sqliteflow_feedback@outlook.com

We tried your link, but got some trouble when trying to download the file. Could you send the file to our email sqliteflow_feedback@outlook.com?

**Comment by wangtwoji** [comment]
已经发送，请您查看。—————————————————
愿你一生平安健康
和你一起终身学习的 王喆@太古森林
—————————————————
            在2018年08月21日 16:10，SQLiteFlow 写道： @wangtwoji 我们试了一下您提供的链接，下载这个文件似乎需要一个这个网站的一个账号，而我们在注册账号时遇到了一些麻烦。如果您方便的话，可以直接将文件发到我们的邮箱么，邮箱地址是
sqliteflow_feedback@outlook.com
We tried your link, but got some trouble when trying to download the file. Could you send the file to our email sqliteflow_feedback@outlook.com?

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/SQLiteFlow/SQLiteFlow-Issues","title":"SQLiteFlow/SQLiteFlow-Issues","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/SQLiteFlow/SQLiteFlow-Issues"}},"updates":{"snippets":[{"icon":"PERSON","message":"@SQLiteFlow in #3: @wangtwoji 我们试了一下您提供的链接，下载这个文件似乎需要一个这个网站的一个账号，而我们在注册账号时遇到了一些麻烦。如果您方便的话，可以直接将文件发到我们的邮箱么，邮箱地址是\r\nsqliteflow_feedback@outlook.com\r\n\r\nWe tried your link, but got some trouble when trying to download the file. Could you send the file to our email sqliteflow_feedback@outlook.com?"}],"action":{"name":"View Issue","url":"https://github.com/SQLiteFlow/SQLiteFlow-Issues/issues/3#issuecomment-414589310"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/SQLiteFlow/SQLiteFlow-Issues/issues/3#issuecomment-414589310",
"url": "https://github.com/SQLiteFlow/SQLiteFlow-Issues/issues/3#issuecomment-414589310",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [SQLiteFlow/SQLiteFlow-Issues] 使用中文作为字段名称时出现输入异常 (#3)",
"sections": [
{
"text": "",
"activityTitle": "**SQLiteFlow**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@SQLiteFlow",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"SQLiteFlow/SQLiteFlow-Issues\",\n\"issueId\": 3,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"SQLiteFlow/SQLiteFlow-Issues\",\n\"issueId\": 3\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/SQLiteFlow/SQLiteFlow-Issues/issues/3#issuecomment-414589310"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 369886960\n}"
}
],
"themeColor": "26292E"
}
]

**Comment by SQLiteFlow** [comment]
@wangtwoji 已收到，谢谢。

File received, thank you.

**Comment by SQLiteFlow** [comment]
![img_1285](https://user-images.githubusercontent.com/38027540/44390443-dc390280-a55f-11e8-9f71-52ce14d43787.GIF)

**Comment by SQLiteFlow** [comment]
@wangtwoji SQLiteFlow 1.3.4 修复了您描述的问题，可以从App Store获取更新了。

Fixed the issue you described here in SQLiteFlow 1.3.4, an update on App Store is available now.

**Comment by wangtwoji** [comment]
经过验证，已经可以使用了。很棒，加油！—————————————————
愿你一生平安健康
和你一起终身学习的 王喆@太古森林
—————————————————
            在2018年08月22日 11:40，SQLiteFlow 写道： @wangtwoji SQLiteFlow 1.3.4 修复了您描述的问题，可以从App Store获取更新了。
Fixed the issue you described here in SQLiteFlow 1.3.4, an update on App Store is available now.

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/SQLiteFlow/SQLiteFlow-Issues","title":"SQLiteFlow/SQLiteFlow-Issues","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/SQLiteFlow/SQLiteFlow-Issues"}},"updates":{"snippets":[{"icon":"PERSON","message":"@SQLiteFlow in #3: @wangtwoji SQLiteFlow 1.3.4 修复了您描述的问题，可以从App Store获取更新了。\r\n\r\nFixed the issue you described here in SQLiteFlow 1.3.4, an update on App Store is available now."}],"action":{"name":"View Issue","url":"https://github.com/SQLiteFlow/SQLiteFlow-Issues/issues/3#issuecomment-414899534"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/SQLiteFlow/SQLiteFlow-Issues/issues/3#issuecomment-414899534",
"url": "https://github.com/SQLiteFlow/SQLiteFlow-Issues/issues/3#issuecomment-414899534",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [SQLiteFlow/SQLiteFlow-Issues] 使用中文作为字段名称时出现输入异常 (#3)",
"sections": [
{
"text": "",
"activityTitle": "**SQLiteFlow**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@SQLiteFlow",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"SQLiteFlow/SQLiteFlow-Issues\",\n\"issueId\": 3,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"SQLiteFlow/SQLiteFlow-Issues\",\n\"issueId\": 3\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/SQLiteFlow/SQLiteFlow-Issues/issues/3#issuecomment-414899534"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 369886960\n}"
}
],
"themeColor": "26292E"
}
]

**Comment by SQLiteFlow** [comment]
@wangtwoji 谢谢。

Thank you.
