### ISSUE TITLE
[macOS] Click to open files from Finder may have no effect when app has not been launched yet.

### ISSUE THREAD

**Issue by TheRealStarone** [SQLiteFlow/SQLiteFlow-Issues#30]
After the update my app database I download from my phone show nothing when opened.

**Comment by SQLiteFlow** [comment]
Hello @TheRealStarone 
Can I get more detail about this issue?
1) Which version are you using? (eg: SQLiteFlow(macOS) 3.3.0, SQLiteFlow(iOS) 3.3.0)
2) The issue appeared after you update SQLiteFlow or update a SQLite database?
3) What's 'show nothing' mean here, not showing any tables or open a table not showing any records?
4) Can I get a screenshot?

**Comment by TheRealStarone** [comment]
Hello,


  1.  SQLLiteFlow 3.5.3 MacOS
  2.  After the update to SQLLiteFlow, it worked perfectly until the update.  I have several copies of my app’s database saved on my Mac, now some of them open, some don’t.
  3.  SQLLiteFlow opens as if I just left clicked it…. The “Open Database” button is shown instead of the tables.  I usually right click the icon and tap a recently opened database, now when I do that its like I just opened the app.

Thanks,
Scott

**Comment by SQLiteFlow** [comment]
@TheRealStarone 
So the issue is right click a file in Finder, choose Open With - SQLiteFlow, the file not open.
Issue reproduced, plan to fix it in next version.

**Comment by SQLiteFlow** [comment]
Issue fixed. Pending release.

**Comment by TheRealStarone** [comment]
Thanks!

It happens when I double click the database file in Finder as well… so right now it doesn’t work at all.

Take care,
Scott

**Comment by TheRealStarone** [comment]
Awesome!  Thank you very much for such a quick fix!

Take care,
Scott

**Comment by SQLiteFlow** [comment]
@TheRealStarone 
> It happens when I double click the database file in Finder as well… so right now it doesn’t work at all.
It's a same bug that cause the issue. So the fix should also fix the issue in this scenario.

**Comment by SQLiteFlow** [comment]
@TheRealStarone 
The fixed version 3.5.4 released.

**Comment by TheRealStarone** [comment]
Great!  Thank you!

-Scott

**Comment by SQLiteFlow** [comment]
@TheRealStarone 
You are welcome!

**Comment by TheRealStarone** [comment]
When will it be in the app store?

Thanks,
Scott

**Comment by SQLiteFlow** [comment]
@TheRealStarone 
Yes, It's already in App Store 2 days ago. The latest version is 3.5.4.
If you are not got any update (may cause by Mac App Store's bug?), will re-download it(that is delete then download it again from App Store) help?

![screenshot](https://user-images.githubusercontent.com/38027540/57109904-4cdc2400-6d69-11e9-876b-a406bfa91792.png)

**Comment by SQLiteFlow** [comment]
@TheRealStarone 
Found a way may also work.
In App Store app - select 'Updates' section - select menu item 'Store' - Reload Page(⌘+R), usually apps that have updating version will appear in a minute. If this doesn't work, you can have a look at my previous post.
![screenshot](https://user-images.githubusercontent.com/38027540/57116157-e6b1ca00-6d85-11e9-9580-b7a4f14be846.png)

**Comment by TheRealStarone** [comment]
Works great now, thanks!

Take care,
Scott
