### ISSUE TITLE
I cannot open the file with a custom file extension

### ISSUE THREAD

**Issue by YOnoda** [SQLiteFlow/SQLiteFlow-Issues#37]
**Version**
 - Platform: [e.g. macOS 10.14.5]
macOS 10.15 beta
 - SQLiteFlow: [e.g. 3.6.0]
3.6.1

**Steps to Reproduce**
Hi,

I downloaded the app but I could not open a file if it uses a wrong extension, even if the file is valid. When I renamed my sqlite file to `-.sqlite3`. the file can be opened successfully.

**Expected behavior**
The file is openable irrespective of the file extension.

**Screen shots**

**Comment by SQLiteFlow** [comment]
Hello @YOnoda 
If you are using a custom sqlite extension (that is not db, db3, sqlite, sqlite3 or no extension), there are two ways to open it.
1. Drag the sqlite file from Finder and drop it into SQLiteFlow, then the file will be opened.
2. Or, if you prefer open the file from Finder when SQLiteFlow is not launched yet, you can right click the file in Finder - Get Info - Open with - Other - Enable: All Applications - Choose SQLiteFlow - Add - Change All. Then you can double click the file in Finder to open the file. A screenshot has been attached.

![Screenshot](https://user-images.githubusercontent.com/38027540/59954863-a505eb80-94b9-11e9-9cbe-05da0a852034.png)

**Comment by YOnoda** [comment]
OK, thanks for the very quick response. The question got resolved. Feel free to close it if you want.

**Comment by SQLiteFlow** [comment]
@YOnoda 
You are welcome!

**Comment by SQLiteFlow** [comment]
@YOnoda 
In addition, if your database file has a custom file extension which is .sql, then if SQLiteFlow can't open this file, this is a bug. And it will be fixed in version 3.6.2, the relate issue is https://github.com/SQLiteFlow/SQLiteFlow-Issues/issues/38

Thank you for your feedback.
