### ISSUE TITLE
[iOS] Move from local iPhone or iCloud

### ISSUE THREAD

**Issue by breezehillret** [SQLiteFlow/SQLiteFlow-Issues#39]
I would like to move my dB from the iPhone to the iCloud. Please advise.

**Comment by SQLiteFlow** [comment]
@breezehillret Yes, you can.

To copy databases in the SQLiteFlow to iCloud, steps are:
1. Tap 'Select' in the database list page.
2. Select database.
3. Tap 'Share'.
4. Choose 'Save to Files'.

Images have been attached.

<img width="518" alt="1  Tap 'Select'" src="https://user-images.githubusercontent.com/38027540/61840458-d6f8dc00-aec3-11e9-8a8a-989a37738cca.png">
<img width="518" alt="2  Select database; 3  Tap 'Share'" src="https://user-images.githubusercontent.com/38027540/61840459-d7917280-aec3-11e9-9f8a-df4524297c62.png">
<img width="518" alt="4  Choose 'Save to Files'" src="https://user-images.githubusercontent.com/38027540/61840460-d7917280-aec3-11e9-9d37-31278e07c490.png">
