### ISSUE TITLE
Unable to Save (or Save As) Queries

### ISSUE THREAD

**Issue by billywizzz** [SQLiteFlow/SQLiteFlow-Issues#4]
After creating a query there is no way to save it because the Save and Save As menu items on the File menu are greyed out. The query is lost when the SQLiteFlow session is closed.
How are queries Saved? (MacOS version).

**Comment by SQLiteFlow** [comment]
@billywizzz The query is lost when the SQLiteFlow session is closed, that is not a good behavior and need to be improved. And saving queries to a file inside SQLiteFlow is not supported yet, that need to be fixed too.

And to solve these issues, what I would like to do in future version, probably version 2.2, are:
1. Supports saving queries to a file, and supports opening queries from a file.
2. Add 'Recent' submenu menu item in query editor's context menu. 'Recent' submenu shows recent closed query sessions as menu items which could let user bring queries back to query editor.

These are what I thought currently, may have differences in future. What do you think about it?

**Comment by billywizzz** [comment]
Excellent, thanks!

**Comment by SQLiteFlow** [comment]
@billywizzz 
SQLiteFlow 2.2.0 has been released.

It contains updates:
• Supports paste recent query sessions.
• Supports save the query to a file.
• Supports load the query from a file.

You can take a try now to see if you are satisfied with these updates. 
And if not, please don't hesitate to tell me.
