### ISSUE TITLE
[iOS] 1000 record max

### ISSUE THREAD

**Issue by breezehillret** [SQLiteFlow/SQLiteFlow-Issues#40]
How do I continue after I reach max records? Is there any way to increase from 1000?

**Comment by SQLiteFlow** [comment]
Hello @breezehillret 

To display unlimited records in data editor, steps are:
1. Tap 'LIMIT 1000' in data editor page.
2. Choose 'NO LIMIT'.

Images have been attached.

<img width="553" alt="1  Tap 'LIMIT 1000'" src="https://user-images.githubusercontent.com/38027540/61840769-df9de200-aec4-11e9-8344-2677f3e9d0a5.png">
<img width="553" alt="2  Choose 'NO LIMIT'" src="https://user-images.githubusercontent.com/38027540/61840770-e0367880-aec4-11e9-8151-f8b9b42fe6c7.png">
