### ISSUE TITLE
[iOS] Copy to windows desktop 

### ISSUE THREAD

**Issue by breezehillret** [SQLiteFlow/SQLiteFlow-Issues#41]
Can I move the dB file to a windows desktop?

**Comment by breezehillret** [comment]
If so how?

**Comment by SQLiteFlow** [comment]
@breezehillret 
Yes, you can. SQLiteFlow(iOS) supports iTunes File Sharing.
You can just drag database files from iTunes File Sharing and drop them to your windows desktop folder.
An image has been attached. 
![iTunes File Sharing](https://user-images.githubusercontent.com/38027540/61842035-5210c100-aec9-11e9-85aa-92a1874b36c6.png)
