### ISSUE TITLE
Update Problem

### ISSUE THREAD

**Issue by McWare** [SQLiteFlow/SQLiteFlow-Issues#48]
I'm unable update my purchased version 3.7 to 3.8 on AppStore
The update button in store is visible, but after pressing it the download indicator is spinning indefinitely... please fix it with Apple!

![Screen Shot 2019-08-17 at 13 07 05](https://user-images.githubusercontent.com/16985927/63210690-61fa7a00-c0f0-11e9-83af-734f4263f4d6.png)

**Comment by SQLiteFlow** [comment]
@McWare Is delete then re-download work?

**Comment by SQLiteFlow** [comment]
Hello @McWare, I see some people update to 3.8.0 from App Store successfully, is this still an issue for you?

**Comment by McWare** [comment]
No problem, I could finally update after deleting the app first.. thx again :)

**Comment by SQLiteFlow** [comment]
@McWare You are welcome.
