### ISSUE TITLE
default directory for database

### ISSUE THREAD

**Issue by Dionysu** [SQLiteFlow/SQLiteFlow-Issues#49]
When I open SqliteFlow and click on "open", I often get a menu of files that does not include my databases.  I know where they are and can get to them, but it would be better if the app "knew" where to find them.  If I am not available and an another person needs to get to a database, I want her to get to it without knowing all about my arrangement of files on my computer.

**Comment by SQLiteFlow** [comment]
@Dionysu  Currently after you click 'Open', the directory that the open dialog will show is the directory of the file that the last time you use 'Open' to open. And the 'open' behavior is the current default behavior across the whole macOS system.

So basically what you want is that after another person click 'Open', he or she can get a specific directory very easily, am I right?

**Comment by Dionysu** [comment]
I think so.  What I want is for the app to open pointing to the directory where I keep the databases.  Every time I click on “open” the dialog opens to that direcrtory — setable in the “preferences” file.

dennis tuchler

**Comment by SQLiteFlow** [comment]
@Dionysu Okay, then what do you think about this approach, is it better(without the messy setting thing in SQLiteFlow): 
Add the specific folder to Finder sidebar's Favorites section, so when you click 'Open' in SQLiteFlow, if this folder is not the folder that the last time you use, you can click to choose this folder in the sidebar. A screenshot has been attached.
<img width="946" alt="Screen Shot" src="https://user-images.githubusercontent.com/38027540/63389349-0a088f80-c3de-11e9-922f-6187e01b6cd3.png">

**Comment by SQLiteFlow** [comment]
@Dionysu  And in case I didn’t described clearly, I describe more here.
SQLiteFlow not only supports to use ‘Open’ dialog to open databases, but also supports double click database files in Finder to open them, and supports drag files from Finder to SQLiteFlow to open them. So with the approach that adding a specific folder to Finder’s sidebar, you can also get benefit from that.

**Comment by Dionysu** [comment]
Adds steps and therefore too complicafed.  One expect complictios to be resolved by the app publisher.

dennis tuchler

**Comment by Dionysu** [comment]
I looked af my Fdinder/preferenfces/ sidebar menu and could not find “Favorite’

**Comment by Dionysu** [comment]
I can’t fiond ‘Favorites” as a menu iems under Finder/Preferences/Sidebar

**Comment by SQLiteFlow** [comment]
Hello @Dionysu, you can just drag the folder to Finder's sidebar to achieve the adds.
A GIF has been attached.
![Add Folder to Sidebar](https://user-images.githubusercontent.com/38027540/63393626-78ede480-c3ee-11e9-8764-b11f784fdb6f.gif)

**Comment by SQLiteFlow** [comment]
Hello @Dionysu, I’m wondering is the solution in previous post looks good to you?

**Comment by Dionysu** [comment]
No, it didn’t.  I could not find a way do what you suggested, under  OS 10.14.6.  I know where my databases are stored, so I suppose I have to live with the current situation.  It seems that changing the preferences file to include a default for data should not be insurmountable.

dennis

**Comment by SQLiteFlow** [comment]
@Dionysu Well, you can actually do what I suggested in literally one second.

Can you see the animated GIF that I attached in this [comment](https://github.com/SQLiteFlow/SQLiteFlow-Issues/issues/49#issuecomment-523247593)?  It shows how you can do it.

If the GIF is not showing in your side, I also attached two pictures below in this comment to show you how to do it. Basically all what you need to do is drag a folder from Finder and drop it to Finder's sidebar. 

If you still have questions about that, you are welcome to ask me.

![1](https://user-images.githubusercontent.com/38027540/63972236-dcf16680-cada-11e9-882b-df0292d1781b.png)
![2](https://user-images.githubusercontent.com/38027540/63972237-dcf16680-cada-11e9-957c-beb19ef8c018.png)

**Comment by Dionysu** [comment]
Thanks for the answer to my e-mail.  I missed a step, which I just took with my “dagabase” folder.  Thanks

dennis

**Comment by SQLiteFlow** [comment]
@Dionysu You are welcome.
