### ISSUE TITLE
一个小建议

### ISSUE THREAD

**Issue by yang-zw** [SQLiteFlow/SQLiteFlow-Issues#5]
你好，能否在New Query的时候显示上一次关闭时写的SQL语句呢？(甚至显示所有写过的SQL语句)。
如果退出软件之后每次都需要重新输入重复的语句，这样很不方便。

**Comment by SQLiteFlow** [comment]
@Bruce-Romance Yeah, I know this is inconvenient. 
This is the issue that I am working on currently, may relative to your advice.
https://github.com/SQLiteFlow/SQLiteFlow-Issues/issues/4#issuecomment-430464318

The plan is 
Add 'Recent' submenu menu item in query editor's context menu. 'Recent' submenu shows recent closed query sessions as menu items which could let user bring queries back to query editor.

是的，这样的确很不方便。
我现在在着手处理与您的建议应该相关的一个Issue, 
https://github.com/SQLiteFlow/SQLiteFlow-Issues/issues/4#issuecomment-430464318

目前的计划是在查询编辑器的右键菜单里增加一个'Recent'的子菜单，子菜单里的每一项是曾经关闭过的查询会话（一个查询会话的内容即为一个查询编辑器里的内容），用户可以选择把曾经关闭过的查询会话粘贴到查询编辑器里。

您觉得如何呢？

**Comment by Bruce-Romance** [comment]
我觉得这样就方便很多了,期待这个版本的更新.谢谢.

**Comment by SQLiteFlow** [comment]
@yang-zw 
SQLiteFlow 2.2.0 has been released, you can take a try now.
SQLiteFlow 2.2.0 已发布，可以试试了。

**Comment by yang-zw** [comment]
好的，已经更新了。目前用起来很不错！

**Comment by SQLiteFlow** [comment]
@yang-zw Thank you. If you found something that you are not satisfied, please let me know.
谢谢。如果遇到了不满意的地方，尽管告诉我们。
