### ISSUE TITLE
[macOS] Supports rename table without writing query.

### ISSUE THREAD

**Issue by SQLiteFlow** [SQLiteFlow/SQLiteFlow-Issues#57]

**Comment by ftrotter** [comment]
This is pretty basic UX functionality, and should not be considered an "enhancement" but rather part of the MVP for a database management tool.

**Comment by SQLiteFlow** [comment]
@ftrotter Fair enough, I plan to implement it in next version.

**Comment by SQLiteFlow** [comment]
Finished.

**Comment by SQLiteFlow** [comment]
SQLiteFlow(macOS) 4.0.0 has been released.
