### ISSUE TITLE
[iOS] Add the ability to enable foreign key constraints in Data Editor.

### ISSUE THREAD

**Issue by wilpert** [SQLiteFlow/SQLiteFlow-Issues#62]
@SQLiteFlow In the iPhone app SQLiteFlow it is possible to define foreign keys. To test how they work I added one row to the table with the foreign key constraint inserting a value that should have triggered an error, but this was not the case. Then I thought that this was due to the fact that I inserted the new row directly in the table. So I tried then to insert the data via a SQL query. I again did not get any error message.

[Researching a bit more](https://www.sqlitetutorial.net/sqlite-foreign-key/), I found out that foreign key support is implemented since SQLite v3.6.19 and that in addition the SQLite library must be compiled omitting certain flags. In that page it is also mentioned that the foreign key support can be checked by excecuting the following query:

PRAGMA foreign_keys;

After excuting it in SQLiteFlow I got the result of 0, which should mean that SQLiteFlow does not support foreign keys constraint.

My question: is it true that there is no support for foreign keys in the current Version of SQLiteFlow?

**Comment by SQLiteFlow** [comment]
Hello @wilpert, short answer is, it supports.

1. To check the version of SQLite library that SQLiteFlow uses, you can execute this query: 
`SELECT sqlite_version();`
In iOS 13, the result should be 3.28.0

2. To make foreign key constraints work, from the official [SQLite documentation](https://sqlite.org/foreignkeys.html)
> it must still be enabled by the application at runtime, using the PRAGMA foreign_keys command. For example: `PRAGMA foreign_keys = ON;`
So, after you execute `PRAGMA foreign_keys = ON`, the result of `PRAGMA foreign_keys;` will should be 1 in that database connection.
So to test foreign key constraints in Query Editor, you can add `PRAGMA foreign_keys = ON;` before other queries. Like
```
PRAGMA foreign_keys = ON;
... INSERT/UPDATE values...;
```

If you have more questions about this, I'm here to listen.
And for more detail about the foreign key constraints, you can check the documentation mentioned above.

Have a good day!

**Comment by SQLiteFlow** [comment]
@wilpert 
Oh, in addition, if you are curious, though it's possible for you to testing the foreign key constraints in Query Editor, it's not possible yet to testing it in Data Editor, because there's no option in UI that let you enable it in runtime.
Currently SQLiteFlow(macOS) has an option in Data Editor that can let users enable it in runtime, and a screen shot of it has been attached. And I think I can add it to SQLiteFlow(iOS) too in a future version.

![Screen Shot](https://user-images.githubusercontent.com/38027540/66195194-af46a100-e6c8-11e9-9568-69e39824bda8.png)

**Comment by wilpert** [comment]
@SQLiteFlow Thanks for the answer. I was just going to ask you exactly that (foreign key constraint in data editor) :-) Yes, it would a nice thing to have, but using a query to insert data is for me equally useful.

**Comment by SQLiteFlow** [comment]
@wilpert Okay, I change this issue's title to '[iOS] Add the ability to enable foreign key constraints in Data Editor'. 
Will let you know when it's available.

**Comment by SQLiteFlow** [comment]
Data Editor now supports enable foreign key constraints.
Screen shots have been attached.

![1](https://user-images.githubusercontent.com/38027540/71137709-0e39a200-2244-11ea-9001-8ca5bbb1da2a.png)
![2](https://user-images.githubusercontent.com/38027540/71137715-109bfc00-2244-11ea-8a8a-3b202ae9a0a6.png)

**Comment by SQLiteFlow** [comment]
SQLiteFlow(iOS) 4.0.0 has been released.
Happy new year!

**Comment by wilpert** [comment]
@SQLiteFlow Many thanks also for this enhancement!
