### ISSUE TITLE
[MacOS] RANK() function fails with Syntax error

### ISSUE THREAD

**Issue by TG-Hobart** [SQLiteFlow/SQLiteFlow-Issues#63]
**Version**
 - macOS 10.14.6
 - SQLiteFlow: 3.8.1

open chinook sample database / New Query /  run query copied from https://www.sqlitetutorial.net/sqlite-window-functions/sqlite-rank/

SELECT
    Name,    Milliseconds,    AlbumId,
    RANK () OVER ( 
        PARTITION BY AlbumId
        ORDER BY Milliseconds DESC
    ) LengthRank 
FROM
    tracks;

**Expected behavior**    Should not fail.

Rank() function failed in a query on my own database, so I downloaded the sample database and tested the Rank() query from the sqlite tutorial.

![Screen Shot 2019-10-10 at 12 22 51 am](https://user-images.githubusercontent.com/56352546/66485245-34c8b780-eaf4-11e9-9a83-3258dc3b34b6.png)

**Comment by SQLiteFlow** [comment]
@TG-Hobart,
I think the reason that you see the error is that the RANK() function is a window function, and window function is introduced in SQLite 3.25.0, which is later than the SQLite version 3.24.0 in macOS 10.14.6.

The SQLite version in macOS 10.15 is 3.28.0, so to make this query work, you may need to update macOS to the latest version 10.15 which window functions like RANK() are available here.

And to check the SQLite version you are currently working on, you can run this query: `SELECT sqlite_version();`

And there is [SQLite 3.25 release notes link](https://sqlite.org/releaselog/3_25_2.html).

**Comment by SQLiteFlow** [comment]
@TG-Hobart 
Does the answer looks good to you?

**Comment by TG-Hobart** [comment]
Is OK

**Comment by SQLiteFlow** [comment]
@TG-Hobart
Thanks. Then I will close this issue.
