### ISSUE TITLE
Request for adding “favorite filter” or filter saved function for IOS Sqliteflow

### ISSUE THREAD

**Issue by w-tim** [SQLiteFlow/SQLiteFlow-Issues#64]
I purchased one copy of your Sqliteflow on IOS platform.

Frequently I search item based on filters but found there is no way to save filter or have favorite function.

I am seeking for quick method to accessing one of my tables while execuating corresponding filter.

**Comment by SQLiteFlow** [comment]
@w-tim Thank you for the request, and that's an interesting suggestion. 
Since searching item in Data Editor can be easier when there're saved filters, so I will implement it in SQLiteFlow.

**Comment by SQLiteFlow** [comment]
Finished coding.
Now, filter is file based.

1. In Data Editor, supports tap 'Filter' button to open or create a filter file.
2. After opened a filter file, users can edit and apply a filter to Data Editor.
3. After applied a filter in Data Editor, tap 'Filter' button, you can choose 'Edit Filter', 'Remove Filter' or 'Choose Another Filter'.

Screenshots have been attached.

![1](https://user-images.githubusercontent.com/38027540/71139569-7d65c500-2249-11ea-8809-4492e07b5add.png)
![2](https://user-images.githubusercontent.com/38027540/71139570-7dfe5b80-2249-11ea-96bc-c114004f861f.png)
![3](https://user-images.githubusercontent.com/38027540/71139571-7dfe5b80-2249-11ea-94ca-43cb2ba4322f.png)
![4](https://user-images.githubusercontent.com/38027540/71139573-7e96f200-2249-11ea-9506-7cc98b4c1540.png)
![5](https://user-images.githubusercontent.com/38027540/71139572-7e96f200-2249-11ea-83a5-757b583afc98.png)

**Comment by w-tim** [comment]
> Finished coding.
> Now, filter is file based.
> 
> 1. In Data Editor, supports tap 'Filter' button to open or create a filter file.
> 2. After opened a filter file, users can edit and apply a filter to Data Editor.
> 3. After applied a filter in Data Editor, tap 'Filter' button, you can choose 'Edit Filter', 'Remove Filter' or 'Choose Another Filter'.
> 
> Screenshots have been attached.
> 
> ![1](https://user-images.githubusercontent.com/38027540/71139569-7d65c500-2249-11ea-8809-4492e07b5add.png)
> ![2](https://user-images.githubusercontent.com/38027540/71139570-7dfe5b80-2249-11ea-96bc-c114004f861f.png)
> ![3](https://user-images.githubusercontent.com/38027540/71139571-7dfe5b80-2249-11ea-94ca-43cb2ba4322f.png)
> ![4](https://user-images.githubusercontent.com/38027540/71139573-7e96f200-2249-11ea-9506-7cc98b4c1540.png)
> ![5](https://user-images.githubusercontent.com/38027540/71139572-7e96f200-2249-11ea-83a5-757b583afc98.png)

Great job! Waiting for updates.

**Comment by SQLiteFlow** [comment]
SQLiteFlow(iOS) 4.0.0 has been released.
Happy new year!
