### ISSUE TITLE
[iOS] SQLiteFlow ver 3.9.3 copy query result issue

### ISSUE THREAD

**Issue by gagan7489** [SQLiteFlow/SQLiteFlow-Issues#73]
**Version**
 - Platform: [IOS 13.2.3 ]
 - SQLiteFlow: [3.9.3]

**Steps to Reproduce**
There is some bug in the above cited version which does come with with an option to copy result to clipboard as can be done in previous versions.

**Expected behavior**

**Screen shots**

**Comment by SQLiteFlow** [comment]
@gagan7489 
Thank you for the report. Will fix it in next version.

**Comment by SQLiteFlow** [comment]
Fixed.

**Comment by gagan7489** [comment]
When should the fixed copy be available on app store

With Best Regards,
Gagandeep Singh

**Comment by SQLiteFlow** [comment]
@gagan7489 
Next version will be 4.0.0 which we plan to release it in 2~3 weeks.

**Comment by SQLiteFlow** [comment]
SQLiteFlow(iOS) 4.0.0 has been released.
Happy new year!

**Comment by gagan7489** [comment]
Thanks for adding wonderful features, if possible plz make query editor like Sqlite mobile client, The query writing experience in editor of SQLite mobile client is very simple and designed for layman, you are requested to work on it to make your app rated best

With Best Regards,
Gagandeep Singh,
+91 94191 25505

**Comment by SQLiteFlow** [comment]
@gagan7489 
Thank you for the advice. I will see what I can do about it. 

However maybe not by the way that make it like the app you mentioned above does. 

Instead, my thinking is enhance it by making code auto completion more intelligent, or more accurate, so words that could benefit user's inputing can appear in the lead of the candidate area based on the context.

So please give me a chance to win this in that _dimension_.

I also created a [issue](https://github.com/SQLiteFlow/SQLiteFlow-Issues/issues/80) for this, more advice is welcome, and I will keep you posted when it's finished.

Thank you again.
