### ISSUE TITLE
[macOS] How do I use the 'Views' feature?

### ISSUE THREAD

**Issue by Dionysu** [SQLiteFlow/SQLiteFlow-Issues#74]
How do I use the "view" or "views" feature in SQLiteFlow?

**Comment by SQLiteFlow** [comment]
@Dionysu You mean how to use the 'Views' section in database list?
![screenshot](https://user-images.githubusercontent.com/38027540/70871574-5a35de00-1fdb-11ea-9a3a-8f8296298786.png)

**Comment by Dionysu** [comment]
Yes, I want to know what a view is and how to make one.

dennis j tuchler

**Comment by SQLiteFlow** [comment]
@Dionysu Will this help?
 https://sqlite.org/lang_createview.html

**Comment by Dionysu** [comment]
So a view is simply a packaged search term. right? I have some search scripts stored under my “open” menu.  How do I get them stored as views to be accessed under the “views” menu?

dennis j tuchker

**Comment by SQLiteFlow** [comment]
@Dionysu Yes, it's kind of like that.

To create a View:
1. Open a database.
2. New Query - Write SQL like 'CREATE VIEW SampleView AS SELECT ...' to create your View.
3. Right click the database in database list -  Refresh.
4. Then the 'SampleView' will show up in Views section in database list.

In addition, get review the 'SampleView' create statement, you could right click the 'SampleView' in Views section - Alter View

You can also get a demo database that contains a View through File - New Sample Database to get a sense of how a View work.
