### ISSUE TITLE
[macOS] How to create a trigger.

### ISSUE THREAD

**Issue by fmenkin** [SQLiteFlow/SQLiteFlow-Issues#76]
I have not found a way to create a trigger in SQLiteFlow on my MAC Air and need to know how soon. (I assume that there is no documentation available.)

**Comment by SQLiteFlow** [comment]
Hello @fmenkin,

To create a trigger, you can following these steps:

1. Open a database.
2. New Query - Enter your trigger creating SQL. 
3. Execute the query.
4. If everything goes right, you will get a trigger that just created.

And there's the document of how to construct a trigger creating SQL available now on SQLite official website:
https://sqlite.org/lang_createtrigger.html
