### ISSUE TITLE
[macOS] Replacing or revising an existing trigger.

### ISSUE THREAD

**Issue by fmenkin** [SQLiteFlow/SQLiteFlow-Issues#77]
I cannot revise or replace a trigger once it has been created.
Dropping the trigger drops use of the trigger until I run a revised trigger, then the old trigger is still being used.

**Comment by SQLiteFlow** [comment]
Hello @fmenkin, can I get more detail about the issue? Like:

**Version**
 - Platform: [e.g. macOS 10.14.5]
 - SQLiteFlow: [e.g. 3.6.0]


**Steps to Reproduce**


**Expected behavior**


**Screen shots**

**Comment by fmenkin** [comment]
Mac Air running 10.15.2.
SQLiteFlow 3.8.1 downloaded very recently from the App Store.
Create a trigger with SQL, but it can't be modified or replaced. 
I expect to be able to delete the trigger or modify the trigger where there is an EDIT available in the Trigger tab.
I finally copied the trigger listings from DDL into a query and it is working but the Trigger tab 
remains unchanged, and edits to it do not appear to make a difference.m 
Why does the DDL revert to "main." for the last TRIGGER listed?
Thanks for your help.

**Comment by SQLiteFlow** [comment]
@fmenkin 

You can edit or delete a trigger through SQL.
For SQLite, if you want to edit a trigger, you need to delete it first through 'DROP TRIGGER' statement, then use 'CREATE TRIGGER' statement to create a new trigger with the same name. 
And that's how you edit a trigger.

If the trigger has been successfully edited or deleted through SQL, the Alter Table tab will not automatically be refreshed, you may need to press the 'Revert' button or close and reopen the Alter Table tab to refresh it.

**Comment by SQLiteFlow** [comment]
Or right click the database name in database list, then click 'Refresh' to refresh it.

**Comment by SQLiteFlow** [comment]
@fmenkin 
So, did I answer your question?

**Comment by SQLiteFlow** [comment]
Close for now. If this is an issue for you, you are welcome to reopen this issue, thank you.
