### ISSUE TITLE
Print from SQLiteFlow

### ISSUE THREAD

**Issue by fmenkin** [SQLiteFlow/SQLiteFlow-Issues#79]
Although my reports are short enough to capture part of the screen and paste it into an editor for printing...
The ability to Print reports larger than the screen directly from SQLiteFlow would be very helpful.

**Comment by SQLiteFlow** [comment]
@fmenkin Based on your description, looks like you are taking a screenshot or a picture of the app, and print the picture to do the printing job?

**Comment by SQLiteFlow** [comment]
Close for now. If this is an issue for you, you are welcome to reopen this issue, thank you.
