### ISSUE TITLE
Entering Data into a table

### ISSUE THREAD

**Issue by davidkirby007** [SQLiteFlow/SQLiteFlow-Issues#8]
Is it possible to enter data more quickly into a table say from a CSV file?

**Comment by SQLiteFlow** [comment]
@davidkirby007 Can't yet. 
I realize importing data to a table from another format like CSV is a very useful feature, and I would like to implement it in recent updates, importing from CSV file may coming first.

**Comment by SQLiteFlow** [comment]
Status update:
Working on it.

**Comment by SQLiteFlow** [comment]
@davidkirby007 
Importing data to a table from a CSV file has been implemented in SQLiteFlow(macOS) 3.1.0 which is available on App Store now.
