### ISSUE TITLE
Keybindings to run query

### ISSUE THREAD

**Issue by jmcd** [SQLiteFlow/SQLiteFlow-Issues#84]
Would it be possible to add a keybinding (eg command-r) to run the current query please?

**Comment by SQLiteFlow** [comment]
@jmcd For SQLiteFlow(iOS)?

**Comment by jmcd** [comment]
@SQLiteFlow macOS (apologies if this is the wrong place to request this)

**Comment by SQLiteFlow** [comment]
@jmcd You are in the right place!
SQLiteFlow(macOS) already support CMD + R to run query and Shift + CMD + R to run selected query in Query Editor. 
Are these shortcuts work for you?

Screenshots:
![RunQuery](https://user-images.githubusercontent.com/38027540/72209137-24a2e880-34e6-11ea-9716-b612a0685879.png)
![RunSelectedQuery](https://user-images.githubusercontent.com/38027540/72209179-91b67e00-34e6-11ea-942f-174b4a8c142a.png)

**Comment by SQLiteFlow** [comment]
@jmcd 
Hey there, so, is the run query hotkey work for you?
If it works, then I will close this issue, if it's not, then it might be a bug.

**Comment by jmcd** [comment]
Apologies - I did not notice the too-tip. Sorry to have wasted your time. Closing issue.

**Comment by SQLiteFlow** [comment]
@jmcd You are welcome. Thank you.
