### ISSUE TITLE
Call SQL functions in Data Editor

### ISSUE THREAD

**Issue by roolo** [SQLiteFlow/SQLiteFlow-Issues#86]
Is there a special way in SQLiteFlow to call SQLite functions? I am trying to insert current date, but it doesn’t seems to work. 

![8998B69D-E70F-4004-A0C0-646FFB842FA3](https://user-images.githubusercontent.com/173141/73890264-d7f6c700-4871-11ea-9688-477177a3b4d7.png)
![D9852A10-42FD-482D-9FB7-5C54E2577B61](https://user-images.githubusercontent.com/173141/73890343-0bd1ec80-4872-11ea-9b42-581719cee591.png)
![88573A26-CA77-4888-8E58-3FB0FB2C4295](https://user-images.githubusercontent.com/173141/73890269-daf1b780-4871-11ea-90ac-b59e96e997f2.png)

**Comment by SQLiteFlow** [comment]
@roolo 
It can't yet in Data Editor, but that's an interesting suggestion for me. 
Data Editor now supports edit a field as text or hex, I will consider add supports for editing a field as expression (or function).

**Comment by roolo** [comment]
So it’s just a thing of the table editor? I mean if I write the insert as a query, functions should work?

**Comment by SQLiteFlow** [comment]
@roolo Yes. Here are two screenshots when executing `SELECT data('now')` in Query Editor.
So if you write query correctly, functions would work.

![1](https://user-images.githubusercontent.com/38027540/73947674-cfb29080-4932-11ea-8229-f76746ad8c45.png)
![2](https://user-images.githubusercontent.com/38027540/73947689-d5a87180-4932-11ea-8ead-5f721a427825.png)

**Comment by dcaruelle** [comment]
Here is an example of inserting a date in SQLiteFlow
![9AA1B28D-420B-453B-A9EB-AB9EC52CC72E](https://user-images.githubusercontent.com/10288196/74094358-2f01d380-4ae0-11ea-8869-2ff1830d8eca.png)
![29D7873A-6375-455A-8292-02D2092EB632](https://user-images.githubusercontent.com/10288196/74094360-345f1e00-4ae0-11ea-9619-5f1ce369627a.png)

**Comment by SQLiteFlow** [comment]
After some investigation, editing a field in Data Editor as expression not likely bring more convenient than directly input the final text. And may bring some unexpected behavior, suck like user can even drop a table in a Data Editor's editing field.
And if user wants input a date in Data Editor, maybe supports edit it in a date picker will be more practical.
Since actually no one request the feature yet, we close this issue, for now.
