### ISSUE TITLE
[macOS] Tiny typo

### ISSUE THREAD

**Issue by natebeaty** [SQLiteFlow/SQLiteFlow-Issues#87]
**Version**
 - Platform: [e.g. macOS 10.14.5]
 - SQLiteFlow: [e.g. 3.6.0]

**Steps to Reproduce**
Click Import.

**Expected behavior**
"Fisrt Line in CSV" should be "First Line in CSV." Tiniest of bugs, but every bit of polish helps. Really appreciate the software.

**Screen shots**
<img width="246" alt="image" src="https://user-images.githubusercontent.com/981306/74262050-28cf4b00-4cca-11ea-87e4-16b39dfb800c.png">

**Comment by SQLiteFlow** [comment]
@natebeaty Thank you for the feedback. I will fix it.

**Comment by SQLiteFlow** [comment]
Fixed.

**Comment by SQLiteFlow** [comment]
SQLiteFlow(macOS) 4.0.0 has been released.
