### ISSUE TITLE
Import CSV - last row is not imported when the CSV text's last field on the last record is not populated

### ISSUE THREAD

**Issue by macrotech5** [SQLiteFlow/SQLiteFlow-Issues#88]
**Version** 
 - Platform: macOS 10.14.6
 - SQLiteFlow: [3.8.1

Import any csv file, specifying there is a header row, into an existing table.
The last row is not imported.
The import message says one less row than expected is imported.

My table is small. I have tried with 77 rows, 1 row and 2 rows (all with header)
76, 0 and 1 rows are imported.

**Comment by SQLiteFlow** [comment]
Hello, @macrotech5

I try to import the CSV text below into to an existing table '_csv_20200216' , set the option First Line is Header on:
```
c1,c2,c3
3,2,1
6,4,5
```
Then I got 2 rows imported successfully. Screenshot has been attached.

The issue may probably related to some specific CSV text. So could you offer me a piece of sample CSV text that causing the issue, so I can investigate it? 

Thank you.

![Import](https://user-images.githubusercontent.com/38027540/74604598-7993d900-50fa-11ea-903c-257a8de9b0d8.png)

**Comment by macrotech5** [comment]
Hi

Thanks for the very speedy reply. I've done some further investigation and
I believe it's a problem when the last field or fields on the last record
are not populated.
I've attached an example csv file with two records, only one of which is
imported unless I populate the final field in the second record.

Shall I update the title of the report?

Thanks

Kevin

**Comment by SQLiteFlow** [comment]
@macrotech5 Thank you for the additional information. 

I may not see the example CSV file you attached because it may be attached through e-mail. I can see it if you attach it through Github website.

And there's no need to attach an example CSV file now because I reproduce the issue based on your description, thank you. I will fix it.

A workaround for this issue:
Append a 'return' character at the end of the CSV text which the last field on the last record is not populated, then the last line will be imported.

Thank you for the reply. I will update the title.

**Comment by macrotech5** [comment]
Hi

Thanks for the update.

I'm writing my first app using a SqLite database and have been very
impressed with your app and support so far!

Cheers

Kevin

**Comment by SQLiteFlow** [comment]
@macrotech5 You are welcome! And good luck with your first app!

**Comment by Dionysu** [comment]
Is there a work-around for the failure of the app to pick up the last line of a CSV file?  Is there some progress on the bug fix?

**Comment by SQLiteFlow** [comment]
Fixed.

**Comment by Dionysu** [comment]
Is it inn an updte?  I checked the updates to my Macbook OS and found none.

Dennis J.Tuchler

**Comment by SQLiteFlow** [comment]
Hello @Dionysu, there’s not an update yet, may have one in a couple of weeks.

**Comment by SQLiteFlow** [comment]
SQLiteFlow(macOS) 4.0.0 has been released.
