### ISSUE TITLE
[macOS] Avoid focus to go out of the form

### ISSUE THREAD

**Issue by GT85** [SQLiteFlow/SQLiteFlow-Issues#89]
Hello.
My table has many columns, that are not all displayed in table edit mode. I create a new line, I set the first column value, then TAB to go to the next column, and so on. After many TABs, the focused textbox is on the right of the screen. The line should be translated to the left so that the focused column is always inside the form.
And many thanks for the tool.
Gilbert

**Comment by SQLiteFlow** [comment]
@GT85 
Thank you for the suggestion, I will do the enhancement for SQLiteFlow(macOS).

**Comment by SQLiteFlow** [comment]
Finished.

**Comment by SQLiteFlow** [comment]
SQLiteFlow(macOS) 4.0.0 has been released.

**Comment by GT85** [comment]
Thanks for both enhancements.

Regards,
Gilbert

**Comment by SQLiteFlow** [comment]
You are welcome!
