### ISSUE TITLE
Sorting (ORDER BY) by click on column?

### ISSUE THREAD

**Issue by hibernat** [SQLiteFlow/SQLiteFlow-Issues#9]
Maybe I have just have not discovered the feature, but it would be nice, when clicking on column header, the data would be sorted (ascending/descending) by the column. Just to add ORDER BY to the query...

**Comment by SQLiteFlow** [comment]
@hibernat Sorting by click on a column is a feature that SQLiteFlow does not have yet. However, I will implement it as soon as I can, probably in the next version.
And yeah, the internal implementation detail will more likely be adding an ORDER BY to the query.

**Comment by SQLiteFlow** [comment]
@hibernat 
This feature has been implemented in SQLiteFlow(macOS) 3.1.0 which is available on App Store now.

**Comment by waveslice** [comment]
In SQLiteFlow (IOS), please add the feature to save queries for later re-use.

**Comment by SQLiteFlow** [comment]
@waveslice Sure. I created an issue for this. [Issue](https://github.com/SQLiteFlow/SQLiteFlow-Issues/issues/13)
