### ISSUE TITLE
Query editor: Tab key does not work as expected

### ISSUE THREAD

**Issue by JorgePadron** [SQLiteFlow/SQLiteFlow-Issues#92]
**Version**
 - Platform: [e.g. macOS 10.14.5]
 - SQLiteFlow: [e.g. 3.6.0]

**Steps to Reproduce**
Type the following...
UPDATE camera SET purchase_date = '2020-04-01' WHERE camera_id = 2;
Then press the Tab key after the ; at the end of the code line above. The Tab key does not work as expected, it jumps to the next line instead.

**Expected behavior**
The Tab key is expected to behave like, well, like the Tab key works everywhere else.

**Screen shots**

**Comment by SQLiteFlow** [comment]
@JorgePadron Looks like this is a display issue too, the Tab character is there but rendered as a new line by the text view.
I will investigate it and fix it in next version.

**Comment by SQLiteFlow** [comment]
Fixed.

**Comment by SQLiteFlow** [comment]
SQLiteFlow(macOS) 4.0.0 has been released.
