### ISSUE TITLE
Minor formatting bug in field CHECK constraint after applying changes

### ISSUE THREAD

**Issue by JorgePadron** [SQLiteFlow/SQLiteFlow-Issues#93]
![CHECK Constraint](https://user-images.githubusercontent.com/633087/79582334-9d8f7e80-8099-11ea-90e3-6135a4048695.png)
**Version**
 - Platform: [e.g. macOS 10.14.5]
 - SQLiteFlow: [e.g. 3.6.0]

**Steps to Reproduce**
Add a DATETIME column 'datetime_column' to a table. Then add this column CHECK constraint...
DATETIME(datetime_column , '+0 days') IS datetime_column
...Apply the changes to update the table. Than, go back to that table's Alter Table, select the 'dateime_column' field, watch the formatting below...
DATETIME( datetime_column , '+0 days') IS datetime_column
There is a blank space after DATETIME(

**Expected behavior**
The CHECK constraint is supposed to be...
DATETIME(datetime_column , '+0 days') IS datetime_column
...instead of...
DATETIME( datetime_column , '+0 days') IS datetime_column

**Screen shots**

**Comment by SQLiteFlow** [comment]
@JorgePadron Thank you for reporting the bug.
This bug has been reproduced. It's a displaying issue for the Check constraint.
I will fix it in next version.

**Comment by SQLiteFlow** [comment]
Fixed.

**Comment by SQLiteFlow** [comment]
SQLiteFlow(macOS) 4.0.0 has been released.
