### ISSUE TITLE
SQL Jargon Suggestion: Table Schema... instead of Alter Table...

### ISSUE THREAD

**Issue by JorgePadron** [SQLiteFlow/SQLiteFlow-Issues#94]
This is just a minor suggestion to use the more common SQL jargon  "Table Schema" instead of "Alter Table", as seen on the attached screenshot.

![Table Schema](https://user-images.githubusercontent.com/633087/79610134-f83ecf80-80c5-11ea-836e-3c8044d79e18.png)

**Comment by SQLiteFlow** [comment]
@JorgePadron Looks good, I will make the change.
Thank you.

**Comment by SQLiteFlow** [comment]
Finished.

**Comment by SQLiteFlow** [comment]
SQLiteFlow(macOS) 4.0.0 has been released.
